= `criterion` codelist
:navtitle: Codelists

This table provides criteria used for public procurement procedures.
[horizontal]
Version:: 20230614-0
URI:: http://publications.europa.eu/resource/dataset/criterion
Tailored by:: xref:code-lists/exclusion-ground.adoc[`exclusion-ground`]
Structure:: flat

== Codes
[horizontal]
  `bankr-nat`::: Analogous situation like bankruptcy under national law
  `bankruptcy`::: Bankruptcy
  `corruption`::: Corruption
  `cred-arran`::: Arrangement with creditors
  `crime-org`::: Participation in a criminal organisation
  `distorsion`::: Agreements with other economic operators aimed at distorting competition
  `envir-law`::: Breaching of obligations in the fields of environmental law
  `finan-laund`::: Money laundering or terrorist financing
  `fraud`::: Fraud
  `human-traffic`::: Child labour and other forms of trafficking in human beings
  `insolvency`::: Insolvency
  `labour-law`::: Breaching of obligations in the fields of labour law
  `liq-admin`::: Assets being administered by liquidator
  `misrepresent`::: Guilty of misrepresentation, withheld information, unable to provide required documents and obtained confidential information of this procedure
  `nati-ground`::: Purely national exclusion grounds
  `partic-confl`::: Conflict of interest due to its participation in the procurement procedure
  `prep-confl`::: Direct or indirect involvement in the preparation of this procurement procedure
  `prof-misconduct`::: Guilty of grave professional misconduct
  `sanction`::: Early termination, damages or other comparable sanctions
  `socsec-law`::: Breaching of obligations in the fields of social law
  `socsec-pay`::: Payment of social security contributions
  `susp-act`::: Business activities are suspended
  `tax-pay`::: Payment of taxes
  `terr-offence`::: Terrorist offences or offences linked to terrorist activities
