= `eforms-currency` codelist
:navtitle: Codelists

List of currency codes allowed in eforms
[horizontal]
Version:: 20230315-0
Subset of:: xref:code-lists/currency.adoc[`currency`]
Structure:: flat

== Codes
[horizontal]
  `AED`::: UAE dirham
  `AFN`::: Afghani
  `ALL`::: Lek
  `AMD`::: Dram
  `ANG`::: Netherlands Antillean guilder
  `AOA`::: Kwanza
  `ARS`::: Argentine peso
  `AUD`::: Australian dollar
  `AWG`::: Aruban guilder
  `AZN`::: Azerbaijan manat
  `BAM`::: Convertible mark
  `BBD`::: Barbados dollar
  `BDT`::: Taka
  `BGN`::: Lev
  `BHD`::: Bahraini dinar
  `BIF`::: Burundi franc
  `BMD`::: Bermuda dollar
  `BND`::: Brunei dollar
  `BOB`::: Boliviano
  `BRL`::: Real
  `BSD`::: Bahamian dollar
  `BTN`::: Ngultrum
  `BWP`::: Pula
  `BYN`::: Belarusian rouble
  `BZD`::: Belize dollar
  `CAD`::: Canadian dollar
  `CDF`::: Congolese franc
  `CHF`::: Swiss franc
  `CLP`::: Chilean peso
  `CNY`::: Renminbi-yuan
  `COP`::: Colombian peso
  `CRC`::: Costa Rican colon
  `CUC`::: Convertible peso
  `CUP`::: Cuban peso
  `CVE`::: Cabo Verde escudo
  `CZK`::: Czech koruna
  `DJF`::: Djibouti franc
  `DKK`::: Danish krone
  `DOP`::: Dominican peso
  `DZD`::: Algerian dinar
  `EGP`::: Egyptian pound
  `ERN`::: Nakfa
  `ETB`::: Birr
  `EUR`::: Euro
  `FJD`::: Fiji dollar
  `FKP`::: Falkland Islands pound
  `GBP`::: Pound sterling
  `GEL`::: Lari
  `GHS`::: Ghana cedi
  `GIP`::: Gibraltar pound
  `GMD`::: Dalasi
  `GNF`::: Guinean franc
  `GTQ`::: Quetzal
  `GYD`::: Guyana dollar
  `HKD`::: Hong Kong dollar
  `HNL`::: Lempira
  `HTG`::: Gourde
  `HUF`::: Forint
  `IDR`::: Rupiah
  `ILS`::: Shekel
  `INR`::: Indian rupee
  `IQD`::: Iraqi dinar
  `IRR`::: Iranian rial
  `ISK`::: Iceland króna
  `JMD`::: Jamaica dollar
  `JOD`::: Jordanian dinar
  `JPY`::: Yen
  `KES`::: Kenyan shilling
  `KGS`::: Som
  `KHR`::: Riel
  `KMF`::: Comorian franc
  `KPW`::: North Korean won
  `KRW`::: South Korean won
  `KWD`::: Kuwaiti dinar
  `KYD`::: Cayman Islands dollar
  `KZT`::: Tenge
  `LAK`::: Kip
  `LBP`::: Lebanese pound
  `LKR`::: Sri Lankan rupee
  `LRD`::: Liberian dollar
  `LSL`::: Loti
  `LYD`::: Libyan dinar
  `MAD`::: Moroccan dirham
  `MDL`::: Moldovan leu
  `MGA`::: Ariary
  `MKD`::: Denar
  `MMK`::: Kyat
  `MNT`::: Tugrik
  `MOP`::: Pataca
  `MRU`::: Ouguiya
  `MUR`::: Mauritian rupee
  `MVR`::: Rufiyaa
  `MWK`::: Malawian kwacha
  `MXN`::: Mexican peso
  `MYR`::: Ringgit
  `MZN`::: Metical
  `NAD`::: Namibian dollar
  `NGN`::: Naira
  `NIO`::: Córdoba oro
  `NOK`::: Norwegian krone
  `NPR`::: Nepalese rupee
  `NZD`::: New Zealand dollar
  `OMR`::: Omani rial
  `OP_DATPRO`::: Provisional data
  `PAB`::: Balboa
  `PEN`::: Sol
  `PGK`::: Kina
  `PHP`::: Philippine peso
  `PKR`::: Pakistani rupee
  `PLN`::: Zloty
  `PYG`::: Guaraní
  `QAR`::: Qatari rial
  `RON`::: Romanian leu
  `RSD`::: Serbian dinar
  `RUB`::: Russian rouble
  `RWF`::: Rwandese franc
  `SAR`::: Saudi riyal
  `SBD`::: Solomon Islands dollar
  `SCR`::: Seychelles rupee
  `SDG`::: Sudanese pound
  `SEK`::: Swedish krona
  `SGD`::: Singapore dollar
  `SHP`::: Saint Helena pound
  `SLE`::: Leone
  `SLL`::: Leone
  `SOS`::: Somali shilling
  `SQS`::: Somaliland shilling
  `SRD`::: Surinamese dollar
  `SSP`::: South Sudanese pound
  `STN`::: Dobra
  `SVC`::: Salvadorian colón
  `SYP`::: Syrian pound
  `SZL`::: Lilangeni
  `THB`::: Baht
  `TJS`::: Somoni
  `TMT`::: Turkmen manat
  `TND`::: Tunisian dinar
  `TOP`::: Pa’anga
  `TRY`::: Turkish lira
  `TTD`::: Trinidad and Tobago dollar
  `TVD`::: Tuvaluan dollar
  `TWD`::: New Taiwan dollar
  `TZS`::: Tanzanian shilling
  `UAH`::: Hryvnia
  `UGX`::: Uganda shilling
  `USD`::: US dollar
  `USN`::: US dollar
  `UYU`::: Uruguayan peso
  `UZS`::: Sum
  `VES`::: Bolívar soberano
  `VND`::: Dong
  `VUV`::: Vatu
  `WST`::: Tala
  `XAF`::: CFA franc (BEAC)
  `XCD`::: East Caribbean dollar
  `XOF`::: CFA Franc (BCEAO)
  `XPF`::: CFP franc
  `YER`::: Yemeni rial
  `ZAR`::: Rand
  `ZMW`::: Zambian kwacha
