= `eu-programme` codelist
:navtitle: Codelists

List of codes for programmes created and coordinated by the European Union and financially supported by the European Union or, in a few cases, by the contributions from the Member States.
[horizontal]
Version:: 20231213-0
URI:: http://publications.europa.eu/resource/dataset/eu-programme
Structure:: flat
Used in:: xref:business-terms/BT-722.adoc[`BT-722`] Contract EU Funds Programme, xref:business-terms/BT-7220.adoc[`BT-7220`] EU Funds Programme

== Codes
[horizontal]
  `AFIS2020`::: Anti Fraud Information System (AFIS) (2014/2020)
  `AGR`::: European Agricultural Guarantee Fund (after transfers between EAGF and EAFRD) (2014/2020)
  `AMF`::: Asylum and Migration Fund (AMF) (2014/2020)
  `AMIF`::: Asylum, Migration and Integration Fund (AMIF) (2021/2027)
  `ANTIFRAUD`::: EU Anti-Fraud Programme (2021/2027)
  `BMVI`::: Integrated Border Management Fund (IBMF) – instrument for border management and visa (BMVi) (2021/2027)
  `CCEI`::: Integrated Border Management Fund (IBMF) – Instrument for financial support for customs control equipment (CCEi) (2021/2027)
  `CDF2020`::: Rights, equality and citizenship programme (2014/2020)
  `CEF`::: Connecting Europe Facility (CEF) (2014/2020)
  `CEF_2021`::: Connecting Europe Facility (CEF) (2021/2027)
  `CERV`::: Citizens, Equality, Rights and Values (2021/2027)
  `CF`::: Cohesion Fund (CF) (2014/2020)
  `CF_2021`::: Cohesion Fund (CF) (2021/2027)
  `CF_DET`::: Contribution from the Cohesion Fund to the CEF programme (2014/2020)
  `CFSP_2021`::: Common Foreign and Security Policy (CFSP) (2021/2027)
  `CFSP2020`::: Common foreign and security policy (CFSP) (2014/2020)
  `CIFP_07_13`::: Competitiveness and Innovation Framework Programme (2007/2013)
  `CIT2020`::: Europe for Citizens (2014/2020)
  `COMPREG`::: Competitiveness (more developed regions) (2014/2020)
  `CONS`::: Consumer programme (2014/2020)
  `COPERNICUS`::: European Earth Observation Programme (Copernicus) (2014/2020)
  `COSME`::: Programme for the competitiveness of enterprises and small and medium-sized enterprises (COSME) (2014/2020)
  `CPM_H3`::: Union Civil Protection Mechanism — Member States (2014/2020)
  `CPM_H4`::: Union Civil Protection Mechanism — Outside EU (2014/2020)
  `CREA`::: Creative Europe programme (2014/2020)
  `CREATIVEEU`::: Creative Europe (2021/2027)
  `CUST2020`::: Action programme for customs in the European Union (Customs 2020) (2014/2020)
  `CUSTOMS`::: Cooperation in the field of customs (CUSTOMS) (2021/2027)
  `DCI2020`::: Development Cooperation Instrument (DCI) (2014/2020)
  `DIGITALEU`::: Digital Europe Programme (2021/2027)
  `E4A`::: The Union programme for education, training, youth and sport (Erasmus+) (2014/2020)
  `EAFRD`::: European Agricultural Fund for Rural Development (after transfers between EAGF and EAFRD) (2014/2020)
  `EAFRD_2021`::: European Agricultural Fund for Rural Development (EAFRD) (2021/2027)
  `EAFRD2020`::: European Agricultural Fund for Rural Development (EAFRD) (2014/2020)
  `EAGF_2021`::: European Agricultural Guarantee Fund (EAGF) (2021/2027)
  `EAGF2020`::: European Agricultural Guarantee Fund (EAGF) (2014/2020)
  `EAR2020`::: Emergency Aid Reserve (EAR) (2014/2020)
  `EDF`::: European Defence Fund (EDF) (2021/2027)
  `EDIDP`::: European Defence Industrial Development Programme (2019/2020)
  `EFSD`::: European Fund for Sustainable Development (EFSD) (2017/2020)
  `EFSI`::: European Fund for Strategic Investments (EFSI) (2015/2020)
  `EGF_2021`::: European Globalisation Adjustment Fund (EGF) (2021/2027)
  `EGF2020`::: European Globalisation Adjustment Fund (EGF) (2014/2020)
  `EIDHR2020`::: European Instrument for Democracy and Human Rights (EIDHR) (2014/2020)
  `EINS`::: European Instrument for Nuclear Safety (EINS) (2021/2027)
  `EMFAF`::: European Maritime, Fisheries and Aquaculture Fund (EMFAF) (2021/2027)
  `EMFF_2021`::: European Maritime and Fisheries Fund (EMFF) (2021/2027)
  `EMFF2020`::: European Maritime and Fisheries Fund (EMFF) (2014/2020)
  `ENI`::: European Neighbourhood Instrument (ENI) (2014/2020)
  `EPF`::: European Peace Facility (2021/2027)
  `ERASMUS_PLUS`::: Erasmus+ (2021/2027)
  `ERDF`::: European Regional Development Fund (ERDF) (2014/2020)
  `ERDF_2021`::: European Regional Development Fund (ERDF) (2021/2027)
  `ESC`::: European Solidarity Corps (ESC) (2018/2020)
  `ESC_2021`::: European Solidarity Corps (ESC) (2021/2027)
  `ESF`::: European Social Fund (ESF) (2014/2020)
  `ESF_PLUS`::: European Social Fund Plus (ESF+) (2021/2027)
  `ESI_2021`::: Instrument for emergency support within the Union (ESI) (2021/2027)
  `ESP2017`::: European statistical programme (ESP) (2013/2017)
  `ESP2020`::: European statistical programme (ESP) (2013/2020)
  `EU4HEALTH`::: EU4Health Programme (2021/2027)
  `EUAV`::: EU Aid Volunteers initiative (EUAV) (2014/2020)
  `EURATOM`::: Euratom research and training programme (2014/2018)
  `EURATOM_07_13`::: Euratom Research and Training Programme (2007/2013)
  `EURATOM_19_20`::: Euratom Research and Training Programme (2019/2020)
  `EURATOM_21_27`::: Euratom Research and Training Programme (2021/2027)
  `EURI`::: European Union Recovery Instrument (EURI) (2021/2027)
  `EURODAC2020`::: Comparison of fingerprints for the effective application of the Dublin Convention (EURODAC) (2014/2020)
  `EUSF_2021`::: European Union Solidarity Fund (EUSF) (2021/2027)
  `EUSF_H3`::: European Union Solidarity Fund (EUSF) — Member States (2014/2020)
  `EUSF_H4`::: European Union Solidarity Fund (EUSF) — Countries negotiating for accession (2014/2020)
  `EUSF2020`::: European Union Solidarity Fund (EUSF) (2014/2020)
  `FEAD`::: Fund for European Aid to the Most Deprived (FEAD) (2014/2020)
  `FF2020`::: Food and feed (2014/2020)
  `FINSER2020`::: Specific activities in the field of financial reporting and auditing (2014/2020)
  `FISC2020`::: Action programme for taxation in the European Union (Fiscalis 2020) (2014/2020)
  `FISCALIS`::: Cooperation in the field of taxation (FISCALIS) (2021/2027)
  `FP6`::: Sixth Framework Programme for Research and Innovation (2001/2006)
  `FP7`::: Seventh Framework Programme for Research and Innovation (2007/2013)
  `GAL2014`::: Implementation and exploitation of European satellite navigation systems (EGNOS and Galileo) (2014/2020)
  `GRLD2020`::: EU cooperation with Greenland (2014/2020)
  `H2020`::: The framework programme for research and innovation (Horizon 2020) (2014/2020)
  `HEALTH`::: Union's action in the field of health (Health programme) (2014/2020)
  `HERC3`::: Programme to promote activities in the field of the protection of the European Union's financial interests (Hercule III) (2014/2020)
  `HFR_09_11`::: Supplementary High Flux Reactor (HFR) programmes (2009/2011)
  `HFR_16_19`::: Supplementary High Flux Reactor (HFR) programmes (2016/2019)
  `HFR_20_23`::: Supplementary High Flux Reactor (HFR) programmes (2020/2023)
  `HFR2015`::: Supplementary high flux reactor (HFR) programmes (2012/2015)
  `HORIZONEU`::: Horizon Europe – the Framework Programme for Research and Innovation (2021/2027)
  `HUMA_2021`::: Humanitarian Aid (HUMA) (2021/2027)
  `HUMA2020`::: Humanitarian aid (2014/2020)
  `ICFS`::: Enhancing consumers involvement in EU policy making in the field of financial services (2017/2020)
  `IES`::: Instrument for emergency support within the Union (2016/2020)
  `IF`::: Innovation Fund (IF) (2021/2027)
  `IFS2020`::: Instrument contributing to Stability and Peace (IcSP) (2014/2020)
  `INSC2020`::: Instrument for Nuclear Safety Cooperation (INSC) (2014/2020)
  `INVESTEU`::: InvestEU Programme (2021/2027)
  `IPA2`::: Instrument for Pre-accession Assistance (IPA II) (2014/2020)
  `IPAIII`::: Instrument for Pre-accession assistance (IPA III) (2021/2027)
  `ISA2015`::: Interoperability Solutions for European Public Administrations (ISA) (2010/2015)
  `ISA2020`::: Interoperability Solutions for European public administrations, businesses and citizens (ISA2) (2016/2020)
  `ISF`::: Internal Security Fund (ISF) (2014/2020)
  `ISF_2021`::: Internal Security Fund (ISF) (2021/2027)
  `ITER`::: International thermonuclear experimental reactor (ITER) (2014/2018)
  `ITER_19_20`::: International Thermonuclear Experimental Reactor (ITER) (2019/2020)
  `ITER_2021`::: International Thermonuclear Experimental Reactor (ITER) (2021/2027)
  `JTF`::: Just Transition Fund (2021/2027)
  `JUST`::: Justice programme (2014/2020)
  `JUSTICE`::: Justice Programme (2021/2027)
  `LIFE_2021`::: Programme for the Environment and Climate Action (LIFE) (2021/2027)
  `LIFE2020`::: Programme for the Environment and Climate Action (LIFE) (2014/2020)
  `LOAN2020`::: Guarantee Fund for external actions (2014/2020)
  `MFA`::: Macro financial assistance (MFA) (2014/2020)
  `MM_2021`::: Military mobility (2021/2027)
  `ND`::: Nuclear decommissioning assistance programmes in Bulgaria, Lithuania and Slovakia (2014/2020)
  `ND_LITH`::: Nuclear decommissioning assistance programmes (Lithuania) (2021/2027)
  `ND_OTHER`::: Nuclear Safety and decommissioning (incl. for Bulgaria and Slovakia) (2021/2027)
  `NDICI`::: Neighbourhood, Development and International Cooperation Instrument (NDICI) (2021/2027)
  `OCT`::: Overseas Countries and Territories (OCT) (including Greenland) (2021/2027)
  `OUTREG`::: Outermost and sparsely populated regions (2014/2020)
  `PERI2020`::: Exchange, assistance and training programme for the protection of the euro against counterfeiting (Pericles 2020) (2014/2020)
  `PERICLES`::: Protection of the euro against counterfeiting (the ‘Pericles IV programme’) (2021/2027)
  `PI`::: Partnership instrument for cooperation with third countries (PI) (2014/2020)
  `PSCI`::: European Union programme for employment and social innovation (EaSI) (2014/2020)
  `PSLF_JTM2021`::: Public sector loan facility under the Just Transition Mechanism (JTM) (2021/2027)
  `REGCONV`::: Regional convergence (less developed regions) (2014/2020)
  `RESCEU`::: Union Civil Protection Mechanism (rescEU) (2021/2027)
  `RFMOs`::: Compulsory contributions to regional fisheries management organisations (RFMOs) and to other international organisations (2014/2020)
  `RIGHTS_2021`::: Rights and Values Programme (2021/2027)
  `RRF`::: European Recovery and Resilience Facility (incl. Technical Support Instrument) (2021/2027)
  `SEAR_2021`::: Solidarity and Emergency Aid Reserve (SEAR) (2021/2027)
  `SFAs`::: Sustainable Fisheries Partnership Agreements (SFPAs) (2014/2020)
  `SINGLEMKT`::: Single Market Programme, including COSME, ISA2, ESP, consumer involvement in fin. Services, financial reporting, Health, Food and Feed, consumer programme (2021/2027)
  `SIS2020`::: Schengen Information System (SIS) (2014/2020)
  `SPACE`::: European Space Programme (2021/2027)
  `TA_IA`::: Technical assistance and innovative actions (2014/2020)
  `TCC`::: Instrument of financial support for encouraging the economic development of the Turkish Cypriot community (TCC) (2014/2020)
  `TCC_2021`::: Support to the Turkish Cypriot Community (2021/2027)
  `TERRCOOP`::: European territorial cooperation (2014/2020)
  `TRANSREG`::: Transition regions (2014/2020)
  `VIS2020`::: Visa Information System (VIS) (2014/2020)
  `YEI`::: Youth employment initiative (specific top-up allocation) (2014/2020)
