= `notice-subtype` codelist
:navtitle: Codelists

List of possible Notice Subtype codes for a Notice of type Business Registration Information Notice.
[horizontal]
Version:: 1.0
Tailored by:: xref:code-lists/brin-ecs.adoc[`brin-ecs`], xref:code-lists/brin-eeig.adoc[`brin-eeig`], xref:code-lists/can-desg.adoc[`can-desg`], xref:code-lists/can-modif.adoc[`can-modif`], xref:code-lists/can-social.adoc[`can-social`], xref:code-lists/can-standard.adoc[`can-standard`], xref:code-lists/can-tran.adoc[`can-tran`], xref:code-lists/cn-desg.adoc[`cn-desg`], xref:code-lists/cn-social.adoc[`cn-social`], xref:code-lists/cn-standard.adoc[`cn-standard`], xref:code-lists/compl.adoc[`compl`], xref:code-lists/pin-buyer.adoc[`pin-buyer`], xref:code-lists/pin-cfc-social.adoc[`pin-cfc-social`], xref:code-lists/pin-cfc-standard.adoc[`pin-cfc-standard`], xref:code-lists/pin-only.adoc[`pin-only`], xref:code-lists/pin-rtl.adoc[`pin-rtl`], xref:code-lists/pin-tran.adoc[`pin-tran`], xref:code-lists/pmc.adoc[`pmc`], xref:code-lists/qu-sy.adoc[`qu-sy`], xref:code-lists/subco.adoc[`subco`], xref:code-lists/veat.adoc[`veat`]
Structure:: flat
Used in:: xref:business-terms/OPP-070.adoc[`OPP-070`] Notice Subtype

== Codes
[horizontal]
  `1`::: 1
  `10`::: 10
  `11`::: 11
  `12`::: 12
  `13`::: 13
  `14`::: 14
  `15`::: 15
  `16`::: 16
  `17`::: 17
  `18`::: 18
  `19`::: 19
  `2`::: 2
  `20`::: 20
  `21`::: 21
  `22`::: 22
  `23`::: 23
  `24`::: 24
  `25`::: 25
  `26`::: 26
  `27`::: 27
  `28`::: 28
  `29`::: 29
  `3`::: 3
  `30`::: 30
  `31`::: 31
  `32`::: 32
  `33`::: 33
  `34`::: 34
  `35`::: 35
  `36`::: 36
  `37`::: 37
  `38`::: 38
  `39`::: 39
  `4`::: 4
  `40`::: 40
  `5`::: 5
  `6`::: 6
  `7`::: 7
  `8`::: 8
  `9`::: 9
  `CEI`::: CEI
  `E1`::: E1
  `E2`::: E2
  `E3`::: E3
  `E4`::: E4
  `E5`::: E5
  `E6`::: E6
  `T01`::: T01
  `T02`::: T02
  `X01`::: X01
  `X02`::: X02
