= `nuts-grc-lvl3` codelist
:navtitle: Codelists

List of level 3 NUTS codes for Greece
[horizontal]
Version:: 1.7.0
URI:: http://publications.europa.eu/resource/dataset/nuts
Subset of:: xref:code-lists/nuts.adoc[`nuts`]
Structure:: flat

== Codes
[horizontal]
  `EL301`::: Βόρειος Τομέας Αθηνών
  `EL302`::: Δυτικός Τομέας Αθηνών
  `EL303`::: Κεντρικός Τομέας Αθηνών
  `EL304`::: Νότιος Τομέας Αθηνών
  `EL305`::: Ανατολική Αττική
  `EL306`::: Δυτική Αττική
  `EL307`::: Πειραιάς, Νήσοι
  `EL411`::: Λέσβος, Λήμνος
  `EL412`::: Ικαρία, Σάμος
  `EL413`::: Χίος
  `EL421`::: Κάλυμνος, Κάρπαθος – Ηρωική Νήσος Κάσος, Κως, Ρόδος
  `EL422`::: Άνδρος, Θήρα, Κέα, Μήλος, Μύκονος, Νάξος, Πάρος, Σύρος, Τήνος
  `EL431`::: Ηράκλειο
  `EL432`::: Λασίθι
  `EL433`::: Ρέθυμνο
  `EL434`::: Χανιά
  `EL511`::: Έβρος
  `EL512`::: Ξάνθη
  `EL513`::: Ροδόπη
  `EL514`::: Δράμα
  `EL515`::: Θάσος, Καβάλα
  `EL521`::: Ημαθία
  `EL522`::: Θεσσαλονίκη
  `EL523`::: Κιλκίς
  `EL524`::: Πέλλα
  `EL525`::: Πιερία
  `EL526`::: Σέρρες
  `EL527`::: Χαλκιδική
  `EL531`::: Γρεβενά, Κοζάνη
  `EL532`::: Καστοριά
  `EL533`::: Φλώρινα
  `EL541`::: Άρτα, Πρέβεζα
  `EL542`::: Θεσπρωτία
  `EL543`::: Ιωάννινα
  `EL611`::: Καρδίτσα, Τρίκαλα
  `EL612`::: Λάρισα
  `EL613`::: Μαγνησία, Σποράδες
  `EL621`::: Ζάκυνθος
  `EL622`::: Κέρκυρα
  `EL623`::: Ιθάκη, Κεφαλληνία
  `EL624`::: Λευκάδα
  `EL631`::: Αιτωλοακαρνανία
  `EL632`::: Αχαΐα
  `EL633`::: Ηλεία
  `EL641`::: Βοιωτία
  `EL642`::: Εύβοια
  `EL643`::: Ευρυτανία
  `EL644`::: Φθιώτιδα
  `EL645`::: Φωκίδα
  `EL651`::: Αργολίδα, Αρκαδία
  `EL652`::: Κορινθία
  `EL653`::: Λακωνία, Μεσσηνία
  `ELZZZ`::: Extra-Regio NUTS 3
