= `nuts-ukr-lvl3` codelist
:navtitle: Codelists

List of level 3 NUTS codes for Ukraine
[horizontal]
Version:: 2024
URI:: http://publications.europa.eu/resource/dataset/nuts
Subset of:: xref:code-lists/nuts.adoc[`nuts`]
Structure:: flat

== Codes
[horizontal]
  `UA111`::: Кременчуцький Район
  `UA112`::: Лубенський Район
  `UA113`::: Миргородський Район
  `UA114`::: Полтавський Район
  `UA121`::: Конотопський Район
  `UA122`::: Охтирський Район
  `UA123`::: Роменський Район
  `UA124`::: Сумський Район
  `UA125`::: Шосткинський Район
  `UA131`::: Богодухівський Район
  `UA132`::: Ізюмський Район
  `UA133`::: Красноградський Район
  `UA134`::: Куп'Янський Район
  `UA135`::: Лозівський Район
  `UA136`::: Харківський Район
  `UA137`::: Чугуївський Район
  `UA141`::: Корюківський Район
  `UA142`::: Ніжинський Район
  `UA143`::: Новгород-Сіверський Район
  `UA144`::: Прилуцький Район
  `UA145`::: Чернігівський Район
  `UA211`::: Бахмутський Район
  `UA212`::: Волноваський Район
  `UA213`::: Горлівський Район
  `UA214`::: Донецький Район
  `UA215`::: Кальміуський Район
  `UA216`::: Краматорський Район
  `UA217`::: Маріупольський Район
  `UA218`::: Покровський Район
  `UA221`::: Алчевський Район
  `UA222`::: Довжанський Район
  `UA223`::: Луганський Район
  `UA224`::: Ровеньківський Район
  `UA225`::: Сватівський Район
  `UA226`::: Сєвєродонецький Район
  `UA227`::: Старобільський Район
  `UA228`::: Щастинський Район
  `UA311`::: Дніпровський Район
  `UA312`::: Кам'Янський Район
  `UA313`::: Криворізький Район
  `UA314`::: Нікопольський Район
  `UA315`::: Новомосковський Район
  `UA316`::: Павлоградський Район
  `UA317`::: Синельниківський Район
  `UA321`::: Бердянський Район
  `UA322`::: Василівський Район
  `UA323`::: Запорізький Район
  `UA324`::: Мелітопольський Район
  `UA325`::: Пологівський Район
  `UA331`::: Голованівський Район
  `UA332`::: Кропивницький Район
  `UA333`::: Новоукраїнський Район
  `UA334`::: Олександрійський Район
  `UA411`::: Баштанський Район
  `UA412`::: Вознесенський Район
  `UA413`::: Миколаївський Район
  `UA414`::: Первомайський Район
  `UA421`::: Березівський Район
  `UA422`::: Білгород-Дністровський Район
  `UA423`::: Болградський Район
  `UA424`::: Ізмаїльський Район
  `UA425`::: Одеський Район
  `UA426`::: Подільський Район
  `UA427`::: Роздільнянський Район
  `UA431`::: Бериславський Район
  `UA432`::: Генічеський Район
  `UA433`::: Каховський Район
  `UA434`::: Скадовський Район
  `UA435`::: Херсонський Район
  `UA441`::: Бахчисарайський Район
  `UA442`::: Білогірський Район
  `UA443`::: Джанкойський Район
  `UA444`::: Євпаторійський Район
  `UA445`::: Керченський Район
  `UA446`::: Курманський Район
  `UA447`::: Перекопський Район
  `UA448`::: Сімферопольський Район
  `UA449`::: Феодосійський Район
  `UA44A`::: Ялтинський Район
  `UA450`::: М. Севастополь
  `UA511`::: Вінницький Район
  `UA512`::: Гайсинський Район
  `UA513`::: Жмеринський Район
  `UA514`::: Могилів-Подільський Район
  `UA515`::: Тульчинський Район
  `UA516`::: Хмільницький Район
  `UA521`::: Кременецький Район
  `UA522`::: Тернопільський Район
  `UA523`::: Чортківський Район
  `UA531`::: Кам'Янець-Подільський Район
  `UA532`::: Хмельницький Район
  `UA533`::: Шепетівський Район
  `UA611`::: Білоцерківський Район
  `UA612`::: Бориспільський Район
  `UA613`::: Броварський Район
  `UA614`::: Бучанський Район
  `UA615`::: Вишгородський Район
  `UA616`::: Обухівський Район
  `UA617`::: Фастівський Район
  `UA621`::: Звенигородський Район
  `UA622`::: Золотоніський Район
  `UA623`::: Уманський Район
  `UA624`::: Черкаський Район
  `UA630`::: М. Київ
  `UA711`::: Берегівський Район
  `UA712`::: Мукачівський Район
  `UA713`::: Рахівський Район
  `UA714`::: Тячівський Район
  `UA715`::: Ужгородський Район
  `UA716`::: Хустський Район
  `UA721`::: Верховинський Район
  `UA722`::: Івано-Франківський Район
  `UA723`::: Калуський Район
  `UA724`::: Коломийський Район
  `UA725`::: Косівський Район
  `UA726`::: Надвірнянський Район
  `UA731`::: Дрогобицький Район
  `UA732`::: Золочівський Район
  `UA733`::: Львівський Район
  `UA734`::: Самбірський Район
  `UA735`::: Стрийський Район
  `UA736`::: Червоноградський Район
  `UA737`::: Яворівський Район
  `UA741`::: Вижницький Район
  `UA742`::: Дністровський Район
  `UA743`::: Чернівецький Район
  `UA811`::: Володимирський Район
  `UA812`::: Камінь-Каширський Район
  `UA813`::: Ковельський Район
  `UA814`::: Луцький Район
  `UA821`::: Бердичівський Район
  `UA822`::: Житомирський Район
  `UA823`::: Коростенський Район
  `UA824`::: Звягельський Район
  `UA831`::: Вараський Район
  `UA832`::: Дубенський Район
  `UA833`::: Рівненський Район
  `UA834`::: Сарненський Район
  `UAZZZ`::: Extra-Regio level 3
