= `nuts-lvl3` codelist
:navtitle: Codelists

List of all level 3 NUTS codes
[horizontal]
Version:: 1.13.0-SNAPSHOT
URI:: http://publications.europa.eu/resource/dataset/nuts
Subset of:: xref:code-lists/nuts.adoc[`nuts`]
Structure:: flat
Used in:: xref:business-terms/BT-507.adoc[`BT-507`] Organisation Country Subdivision, xref:business-terms/BT-5071.adoc[`BT-5071`] Place Performance Country Subdivision

== Codes
[horizontal]
  `AL011`::: Dibër
  `AL012`::: Durrës
  `AL013`::: Kukës
  `AL014`::: Lezhë
  `AL015`::: Shkodër
  `AL021`::: Elbasan
  `AL022`::: Tiranë
  `AL031`::: Berat
  `AL032`::: Fier
  `AL033`::: Gjirokastër
  `AL034`::: Korcë
  `AL035`::: Vlorë
  `ALZZZ`::: Extra-Regio NUTS 3
  `AT111`::: Mittelburgenland
  `AT112`::: Nordburgenland
  `AT113`::: Südburgenland
  `AT121`::: Mostviertel-Eisenwurzen
  `AT122`::: Niederösterreich-Süd
  `AT123`::: Sankt Pölten
  `AT124`::: Waldviertel
  `AT125`::: Weinviertel
  `AT126`::: Wiener Umland/Nordteil
  `AT127`::: Wiener Umland/Südteil
  `AT130`::: Wien
  `AT211`::: Klagenfurt-Villach
  `AT212`::: Oberkärnten
  `AT213`::: Unterkärnten
  `AT221`::: Graz
  `AT222`::: Liezen
  `AT223`::: Östliche Obersteiermark
  `AT224`::: Oststeiermark
  `AT225`::: West- und Südsteiermark
  `AT226`::: Westliche Obersteiermark
  `AT311`::: Innviertel
  `AT312`::: Linz-Wels
  `AT313`::: Mühlviertel
  `AT314`::: Steyr-Kirchdorf
  `AT315`::: Traunviertel
  `AT321`::: Lungau
  `AT322`::: Pinzgau-Pongau
  `AT323`::: Salzburg und Umgebung
  `AT331`::: Außerfern
  `AT332`::: Innsbruck
  `AT333`::: Osttirol
  `AT334`::: Tiroler Oberland
  `AT335`::: Tiroler Unterland
  `AT341`::: Bludenz-Bregenzer Wald
  `AT342`::: Rheintal-Bodenseegebiet
  `ATZZZ`::: Extra-Regio NUTS 3
  `BE100`::: Arr. de Bruxelles-Capitale/Arr. Brussel-Hoofdstad
  `BE211`::: Arr. Antwerpen
  `BE212`::: Arr. Mechelen
  `BE213`::: Arr. Turnhout
  `BE223`::: Arr. Tongeren
  `BE224`::: Arr. Hasselt
  `BE225`::: Arr. Maaseik
  `BE231`::: Arr. Aalst
  `BE232`::: Arr. Dendermonde
  `BE233`::: Arr. Eeklo
  `BE234`::: Arr. Gent
  `BE235`::: Arr. Oudenaarde
  `BE236`::: Arr. Sint-Niklaas
  `BE241`::: Arr. Halle-Vilvoorde
  `BE242`::: Arr. Leuven
  `BE251`::: Arr. Brugge
  `BE252`::: Arr. Diksmuide
  `BE253`::: Arr. Ieper
  `BE254`::: Arr. Kortrijk
  `BE255`::: Arr. Oostende
  `BE256`::: Arr. Roeselare
  `BE257`::: Arr. Tielt
  `BE258`::: Arr. Veurne
  `BE310`::: Arr. Nivelles
  `BE323`::: Arr. Mons
  `BE328`::: Arr. Tournai-Mouscron
  `BE329`::: Arr. La Louvière
  `BE32A`::: Arr. Ath
  `BE32B`::: Arr. Charleroi
  `BE32C`::: Arr. Soignies
  `BE32D`::: Arr. Thuin
  `BE331`::: Arr. Huy
  `BE332`::: Arr. Liège
  `BE334`::: Arr. Waremme
  `BE335`::: Arr. Verviers — communes francophones
  `BE336`::: Bezirk Verviers — Deutschsprachige Gemeinschaft
  `BE341`::: Arr. Arlon
  `BE342`::: Arr. Bastogne
  `BE343`::: Arr. Marche-en-Famenne
  `BE344`::: Arr. Neufchâteau
  `BE345`::: Arr. Virton
  `BE351`::: Arr. Dinant
  `BE352`::: Arr. Namur
  `BE353`::: Arr. Philippeville
  `BEZZZ`::: Extra-Regio NUTS 3
  `BG311`::: Видин
  `BG312`::: Монтана
  `BG313`::: Враца
  `BG314`::: Плевен
  `BG315`::: Ловеч
  `BG321`::: Велико Търново
  `BG322`::: Габрово
  `BG323`::: Русе
  `BG324`::: Разград
  `BG325`::: Силистра
  `BG331`::: Варна
  `BG332`::: Добрич
  `BG333`::: Шумен
  `BG334`::: Търговище
  `BG341`::: Бургас
  `BG342`::: Сливен
  `BG343`::: Ямбол
  `BG344`::: Стара Загора
  `BG411`::: София (столица)
  `BG412`::: София
  `BG413`::: Благоевград
  `BG414`::: Перник
  `BG415`::: Кюстендил
  `BG421`::: Пловдив
  `BG422`::: Хасково
  `BG423`::: Пазарджик
  `BG424`::: Смолян
  `BG425`::: Кърджали
  `BGZZZ`::: Extra-Regio NUTS 3
  `CH011`::: Vaud
  `CH012`::: Valais / Wallis
  `CH013`::: Genève
  `CH021`::: Bern / Berne
  `CH022`::: Fribourg / Freiburg
  `CH023`::: Solothurn
  `CH024`::: Neuchâtel
  `CH025`::: Jura
  `CH031`::: Basel-Stadt
  `CH032`::: Basel-Landschaft
  `CH033`::: Aargau
  `CH040`::: Zürich
  `CH051`::: Glarus
  `CH052`::: Schaffhausen
  `CH053`::: Appenzell Ausserrhoden
  `CH054`::: Appenzell Innerrhoden
  `CH055`::: St. Gallen
  `CH056`::: Graubünden / Grigioni / Grischun
  `CH057`::: Thurgau
  `CH061`::: Luzern
  `CH062`::: Uri
  `CH063`::: Schwyz
  `CH064`::: Obwalden
  `CH065`::: Nidwalden
  `CH066`::: Zug
  `CH070`::: Ticino
  `CHZZZ`::: Extra-Regio NUTS 3
  `CY000`::: Κύπρος
  `CYZZZ`::: Extra-Regio NUTS 3
  `CZ010`::: Hlavní město Praha
  `CZ020`::: Středočeský kraj
  `CZ031`::: Jihočeský kraj
  `CZ032`::: Plzeňský kraj
  `CZ041`::: Karlovarský kraj
  `CZ042`::: Ústecký kraj
  `CZ051`::: Liberecký kraj
  `CZ052`::: Královéhradecký kraj
  `CZ053`::: Pardubický kraj
  `CZ063`::: Kraj Vysočina
  `CZ064`::: Jihomoravský kraj
  `CZ071`::: Olomoucký kraj
  `CZ072`::: Zlínský kraj
  `CZ080`::: Moravskoslezský kraj
  `CZZZZ`::: Extra-Regio NUTS 3
  `DE111`::: Stuttgart, Stadtkreis
  `DE112`::: Böblingen
  `DE113`::: Esslingen
  `DE114`::: Göppingen
  `DE115`::: Ludwigsburg
  `DE116`::: Rems-Murr-Kreis
  `DE117`::: Heilbronn, Stadtkreis
  `DE118`::: Heilbronn, Landkreis
  `DE119`::: Hohenlohekreis
  `DE11A`::: Schwäbisch Hall
  `DE11B`::: Main-Tauber-Kreis
  `DE11C`::: Heidenheim
  `DE11D`::: Ostalbkreis
  `DE121`::: Baden-Baden, Stadtkreis
  `DE122`::: Karlsruhe, Stadtkreis
  `DE123`::: Karlsruhe, Landkreis
  `DE124`::: Rastatt
  `DE125`::: Heidelberg, Stadtkreis
  `DE126`::: Mannheim, Stadtkreis
  `DE127`::: Neckar-Odenwald-Kreis
  `DE128`::: Rhein-Neckar-Kreis
  `DE129`::: Pforzheim, Stadtkreis
  `DE12A`::: Calw
  `DE12B`::: Enzkreis
  `DE12C`::: Freudenstadt
  `DE131`::: Freiburg im Breisgau, Stadtkreis
  `DE132`::: Breisgau-Hochschwarzwald
  `DE133`::: Emmendingen
  `DE134`::: Ortenaukreis
  `DE135`::: Rottweil
  `DE136`::: Schwarzwald-Baar-Kreis
  `DE137`::: Tuttlingen
  `DE138`::: Konstanz
  `DE139`::: Lörrach
  `DE13A`::: Waldshut
  `DE141`::: Reutlingen
  `DE142`::: Tübingen, Landkreis
  `DE143`::: Zollernalbkreis
  `DE144`::: Ulm, Stadtkreis
  `DE145`::: Alb-Donau-Kreis
  `DE146`::: Biberach
  `DE147`::: Bodenseekreis
  `DE148`::: Ravensburg
  `DE149`::: Sigmaringen
  `DE211`::: Ingolstadt, Kreisfreie Stadt
  `DE212`::: München, Kreisfreie Stadt
  `DE213`::: Rosenheim, Kreisfreie Stadt
  `DE214`::: Altötting
  `DE215`::: Berchtesgadener Land
  `DE216`::: Bad Tölz-Wolfratshausen
  `DE217`::: Dachau
  `DE218`::: Ebersberg
  `DE219`::: Eichstätt
  `DE21A`::: Erding
  `DE21B`::: Freising
  `DE21C`::: Fürstenfeldbruck
  `DE21D`::: Garmisch-Partenkirchen
  `DE21E`::: Landsberg am Lech
  `DE21F`::: Miesbach
  `DE21G`::: Mühldorf a. Inn
  `DE21H`::: München, Landkreis
  `DE21I`::: Neuburg-Schrobenhausen
  `DE21J`::: Pfaffenhofen a. d. Ilm
  `DE21K`::: Rosenheim, Landkreis
  `DE21L`::: Starnberg
  `DE21M`::: Traunstein
  `DE21N`::: Weilheim-Schongau
  `DE221`::: Landshut, Kreisfreie Stadt
  `DE222`::: Passau, Kreisfreie Stadt
  `DE223`::: Straubing, Kreisfreie Stadt
  `DE224`::: Deggendorf
  `DE225`::: Freyung-Grafenau
  `DE226`::: Kelheim
  `DE227`::: Landshut, Landkreis
  `DE228`::: Passau, Landkreis
  `DE229`::: Regen
  `DE22A`::: Rottal-Inn
  `DE22B`::: Straubing-Bogen
  `DE22C`::: Dingolfing-Landau
  `DE231`::: Amberg, Kreisfreie Stadt
  `DE232`::: Regensburg, Kreisfreie Stadt
  `DE233`::: Weiden i. d. Opf, Kreisfreie Stadt
  `DE234`::: Amberg-Sulzbach
  `DE235`::: Cham
  `DE236`::: Neumarkt i. d. OPf.
  `DE237`::: Neustadt a. d. Waldnaab
  `DE238`::: Regensburg, Landkreis
  `DE239`::: Schwandorf
  `DE23A`::: Tirschenreuth
  `DE241`::: Bamberg, Kreisfreie Stadt
  `DE242`::: Bayreuth, Kreisfreie Stadt
  `DE243`::: Coburg, Kreisfreie Stadt
  `DE244`::: Hof, Kreisfreie Stadt
  `DE245`::: Bamberg, Landkreis
  `DE246`::: Bayreuth, Landkreis
  `DE247`::: Coburg, Landkreis
  `DE248`::: Forchheim
  `DE249`::: Hof, Landkreis
  `DE24A`::: Kronach
  `DE24B`::: Kulmbach
  `DE24C`::: Lichtenfels
  `DE24D`::: Wunsiedel i. Fichtelgebirge
  `DE251`::: Ansbach, Kreisfreie Stadt
  `DE252`::: Erlangen, Kreisfreie Stadt
  `DE253`::: Fürth, Kreisfreie Stadt
  `DE254`::: Nürnberg, Kreisfreie Stadt
  `DE255`::: Schwabach, Kreisfreie Stadt
  `DE256`::: Ansbach, Landkreis
  `DE257`::: Erlangen-Höchstadt
  `DE258`::: Fürth, Landkreis
  `DE259`::: Nürnberger Land
  `DE25A`::: Neustadt a. d. Aisch-Bad Windsheim
  `DE25B`::: Roth
  `DE25C`::: Weißenburg-Gunzenhausen
  `DE261`::: Aschaffenburg, Kreisfreie Stadt
  `DE262`::: Schweinfurt, Kreisfreie Stadt
  `DE263`::: Würzburg, Kreisfreie Stadt
  `DE264`::: Aschaffenburg, Landkreis
  `DE265`::: Bad Kissingen
  `DE266`::: Rhön-Grabfeld
  `DE267`::: Haßberge
  `DE268`::: Kitzingen
  `DE269`::: Miltenberg
  `DE26A`::: Main-Spessart
  `DE26B`::: Schweinfurt, Landkreis
  `DE26C`::: Würzburg, Landkreis
  `DE271`::: Augsburg, Kreisfreie Stadt
  `DE272`::: Kaufbeuren, Kreisfreie Stadt
  `DE273`::: Kempten (Allgäu), Kreisfreie Stadt
  `DE274`::: Memmingen, Kreisfreie Stadt
  `DE275`::: Aichach-Friedberg
  `DE276`::: Augsburg, Landkreis
  `DE277`::: Dillingen a.d. Donau
  `DE278`::: Günzburg
  `DE279`::: Neu-Ulm
  `DE27A`::: Lindau (Bodensee)
  `DE27B`::: Ostallgäu
  `DE27C`::: Unterallgäu
  `DE27D`::: Donau-Ries
  `DE27E`::: Oberallgäu
  `DE300`::: Berlin
  `DE401`::: Brandenburg an der Havel, Kreisfreie Stadt
  `DE402`::: Cottbus, Kreisfreie Stadt
  `DE403`::: Frankfurt (Oder), Kreisfreie Stadt
  `DE404`::: Potsdam, Kreisfreie Stadt
  `DE405`::: Barnim
  `DE406`::: Dahme-Spreewald
  `DE407`::: Elbe-Elster
  `DE408`::: Havelland
  `DE409`::: Märkisch-Oderland
  `DE40A`::: Oberhavel
  `DE40B`::: Oberspreewald-Lausitz
  `DE40C`::: Oder-Spree
  `DE40D`::: Ostprignitz-Ruppin
  `DE40E`::: Potsdam-Mittelmark
  `DE40F`::: Prignitz
  `DE40G`::: Spree-Neiße
  `DE40H`::: Teltow-Fläming
  `DE40I`::: Uckermark
  `DE501`::: Bremen, Kreisfreie Stadt
  `DE502`::: Bremerhaven, Kreisfreie Stadt
  `DE600`::: Hamburg
  `DE711`::: Darmstadt, Kreisfreie Stadt
  `DE712`::: Frankfurt am Main, Kreisfreie Stadt
  `DE713`::: Offenbach am Main, Kreisfreie Stadt
  `DE714`::: Wiesbaden, Kreisfreie Stadt
  `DE715`::: Bergstraße
  `DE716`::: Darmstadt-Dieburg
  `DE717`::: Groß-Gerau
  `DE718`::: Hochtaunuskreis
  `DE719`::: Main-Kinzig-Kreis
  `DE71A`::: Main-Taunus-Kreis
  `DE71B`::: Odenwaldkreis
  `DE71C`::: Offenbach, Landkreis
  `DE71D`::: Rheingau-Taunus-Kreis
  `DE71E`::: Wetteraukreis
  `DE721`::: Gießen, Landkreis
  `DE722`::: Lahn-Dill-Kreis
  `DE723`::: Limburg-Weilburg
  `DE724`::: Marburg-Biedenkopf
  `DE725`::: Vogelsbergkreis
  `DE731`::: Kassel, Kreisfreie Stadt
  `DE732`::: Fulda
  `DE733`::: Hersfeld-Rotenburg
  `DE734`::: Kassel, Landkreis
  `DE735`::: Schwalm-Eder-Kreis
  `DE736`::: Waldeck-Frankenberg
  `DE737`::: Werra-Meißner-Kreis
  `DE803`::: Rostock, Kreisfreie Stadt
  `DE804`::: Schwerin, Kreisfreie Stadt
  `DE80J`::: Mecklenburgische Seenplatte
  `DE80K`::: Landkreis Rostock
  `DE80L`::: Vorpommern-Rügen
  `DE80M`::: Nordwestmecklenburg
  `DE80N`::: Vorpommern-Greifswald
  `DE80O`::: Ludwigslust-Parchim
  `DE911`::: Braunschweig, Kreisfreie Stadt
  `DE912`::: Salzgitter, Kreisfreie Stadt
  `DE913`::: Wolfsburg, Kreisfreie Stadt
  `DE914`::: Gifhorn
  `DE916`::: Goslar
  `DE917`::: Helmstedt
  `DE918`::: Northeim
  `DE91A`::: Peine
  `DE91B`::: Wolfenbüttel
  `DE91C`::: Göttingen
  `DE922`::: Diepholz
  `DE923`::: Hameln-Pyrmont
  `DE925`::: Hildesheim
  `DE926`::: Holzminden
  `DE927`::: Nienburg (Weser)
  `DE928`::: Schaumburg
  `DE929`::: Region Hannover
  `DE931`::: Celle
  `DE932`::: Cuxhaven
  `DE933`::: Harburg
  `DE934`::: Lüchow-Dannenberg
  `DE935`::: Lüneburg, Landkreis
  `DE936`::: Osterholz
  `DE937`::: Rotenburg (Wümme)
  `DE938`::: Heidekreis
  `DE939`::: Stade
  `DE93A`::: Uelzen
  `DE93B`::: Verden
  `DE941`::: Delmenhorst, Kreisfreie Stadt
  `DE942`::: Emden, Kreisfreie Stadt
  `DE943`::: Oldenburg (Oldenburg), Kreisfreie Stadt
  `DE944`::: Osnabrück, Kreisfreie Stadt
  `DE945`::: Wilhelmshaven, Kreisfreie Stadt
  `DE946`::: Ammerland
  `DE947`::: Aurich
  `DE948`::: Cloppenburg
  `DE949`::: Emsland
  `DE94A`::: Friesland (DE)
  `DE94B`::: Grafschaft Bentheim
  `DE94C`::: Leer
  `DE94D`::: Oldenburg, Landkreis
  `DE94E`::: Osnabrück, Landkreis
  `DE94F`::: Vechta
  `DE94G`::: Wesermarsch
  `DE94H`::: Wittmund
  `DEA11`::: Düsseldorf, Kreisfreie Stadt
  `DEA12`::: Duisburg, Kreisfreie Stadt
  `DEA13`::: Essen, Kreisfreie Stadt
  `DEA14`::: Krefeld, Kreisfreie Stadt
  `DEA15`::: Mönchengladbach, Kreisfreie Stadt
  `DEA16`::: Mülheim an der Ruhr, Kreisfreie Stadt
  `DEA17`::: Oberhausen, Kreisfreie Stadt
  `DEA18`::: Remscheid, Kreisfreie Stadt
  `DEA19`::: Solingen, Kreisfreie Stadt
  `DEA1A`::: Wuppertal, Kreisfreie Stadt
  `DEA1B`::: Kleve
  `DEA1C`::: Mettmann
  `DEA1D`::: Rhein-Kreis Neuss
  `DEA1E`::: Viersen
  `DEA1F`::: Wesel
  `DEA22`::: Bonn, Kreisfreie Stadt
  `DEA23`::: Köln, Kreisfreie Stadt
  `DEA24`::: Leverkusen, Kreisfreie Stadt
  `DEA26`::: Düren
  `DEA27`::: Rhein-Erft-Kreis
  `DEA28`::: Euskirchen
  `DEA29`::: Heinsberg
  `DEA2A`::: Oberbergischer Kreis
  `DEA2B`::: Rheinisch-Bergischer Kreis
  `DEA2C`::: Rhein-Sieg-Kreis
  `DEA2D`::: Städteregion Aachen
  `DEA31`::: Bottrop, Kreisfreie Stadt
  `DEA32`::: Gelsenkirchen, Kreisfreie Stadt
  `DEA33`::: Münster, Kreisfreie Stadt
  `DEA34`::: Borken
  `DEA35`::: Coesfeld
  `DEA36`::: Recklinghausen
  `DEA37`::: Steinfurt
  `DEA38`::: Warendorf
  `DEA41`::: Bielefeld, Kreisfreie Stadt
  `DEA42`::: Gütersloh
  `DEA43`::: Herford
  `DEA44`::: Höxter
  `DEA45`::: Lippe
  `DEA46`::: Minden-Lübbecke
  `DEA47`::: Paderborn
  `DEA51`::: Bochum, Kreisfreie Stadt
  `DEA52`::: Dortmund, Kreisfreie Stadt
  `DEA53`::: Hagen, Kreisfreie Stadt
  `DEA54`::: Hamm, Kreisfreie Stadt
  `DEA55`::: Herne, Kreisfreie Stadt
  `DEA56`::: Ennepe-Ruhr-Kreis
  `DEA57`::: Hochsauerlandkreis
  `DEA58`::: Märkischer Kreis
  `DEA59`::: Olpe
  `DEA5A`::: Siegen-Wittgenstein
  `DEA5B`::: Soest
  `DEA5C`::: Unna
  `DEB11`::: Koblenz, Kreisfreie Stadt
  `DEB12`::: Ahrweiler
  `DEB13`::: Altenkirchen (Westerwald)
  `DEB14`::: Bad Kreuznach
  `DEB15`::: Birkenfeld
  `DEB17`::: Mayen-Koblenz
  `DEB18`::: Neuwied
  `DEB1A`::: Rhein-Lahn-Kreis
  `DEB1B`::: Westerwaldkreis
  `DEB1C`::: Cochem-Zell
  `DEB1D`::: Rhein-Hunsrück-Kreis
  `DEB21`::: Trier, Kreisfreie Stadt
  `DEB22`::: Bernkastel-Wittlich
  `DEB23`::: Eifelkreis Bitburg-Prüm
  `DEB24`::: Vulkaneifel
  `DEB25`::: Trier-Saarburg
  `DEB31`::: Frankenthal (Pfalz), Kreisfreie Stadt
  `DEB32`::: Kaiserslautern, Kreisfreie Stadt
  `DEB33`::: Landau in der Pfalz, Kreisfreie Stadt
  `DEB34`::: Ludwigshafen am Rhein, Kreisfreie Stadt
  `DEB35`::: Mainz, Kreisfreie Stadt
  `DEB36`::: Neustadt an der Weinstraße, Kreisfreie Stadt
  `DEB37`::: Pirmasens, Kreisfreie Stadt
  `DEB38`::: Speyer, Kreisfreie Stadt
  `DEB39`::: Worms, Kreisfreie Stadt
  `DEB3A`::: Zweibrücken, Kreisfreie Stadt
  `DEB3B`::: Alzey-Worms
  `DEB3C`::: Bad Dürkheim
  `DEB3D`::: Donnersbergkreis
  `DEB3E`::: Germersheim
  `DEB3F`::: Kaiserslautern, Landkreis
  `DEB3G`::: Kusel
  `DEB3H`::: Südliche Weinstraße
  `DEB3I`::: Rhein-Pfalz-Kreis
  `DEB3J`::: Mainz-Bingen
  `DEB3K`::: Südwestpfalz
  `DEC01`::: Regionalverband Saarbrücken
  `DEC02`::: Merzig-Wadern
  `DEC03`::: Neunkirchen
  `DEC04`::: Saarlouis
  `DEC05`::: Saarpfalz-Kreis
  `DEC06`::: St. Wendel
  `DED21`::: Dresden, Kreisfreie Stadt
  `DED2C`::: Bautzen
  `DED2D`::: Görlitz
  `DED2E`::: Meißen
  `DED2F`::: Sächsische Schweiz-Osterzgebirge
  `DED41`::: Chemnitz, Kreisfreie Stadt
  `DED42`::: Erzgebirgskreis
  `DED43`::: Mittelsachsen
  `DED44`::: Vogtlandkreis
  `DED45`::: Zwickau
  `DED51`::: Leipzig, Kreisfreie Stadt
  `DED52`::: Leipzig
  `DED53`::: Nordsachsen
  `DEE01`::: Dessau-Roßlau, Kreisfreie Stadt
  `DEE02`::: Halle (Saale), Kreisfreie Stadt
  `DEE03`::: Magdeburg, Kreisfreie Stadt
  `DEE04`::: Altmarkkreis Salzwedel
  `DEE05`::: Anhalt-Bitterfeld
  `DEE06`::: Jerichower Land
  `DEE07`::: Börde
  `DEE08`::: Burgenlandkreis
  `DEE09`::: Harz
  `DEE0A`::: Mansfeld-Südharz
  `DEE0B`::: Saalekreis
  `DEE0C`::: Salzlandkreis
  `DEE0D`::: Stendal
  `DEE0E`::: Wittenberg
  `DEF01`::: Flensburg, Kreisfreie Stadt
  `DEF02`::: Kiel, Kreisfreie Stadt
  `DEF03`::: Lübeck, Kreisfreie Stadt
  `DEF04`::: Neumünster, Kreisfreie Stadt
  `DEF05`::: Dithmarschen
  `DEF06`::: Herzogtum Lauenburg
  `DEF07`::: Nordfriesland
  `DEF08`::: Ostholstein
  `DEF09`::: Pinneberg
  `DEF0A`::: Plön
  `DEF0B`::: Rendsburg-Eckernförde
  `DEF0C`::: Schleswig-Flensburg
  `DEF0D`::: Segeberg
  `DEF0E`::: Steinburg
  `DEF0F`::: Stormarn
  `DEG01`::: Erfurt, Kreisfreie Stadt
  `DEG02`::: Gera, Kreisfreie Stadt
  `DEG03`::: Jena, Kreisfreie Stadt
  `DEG05`::: Weimar, Kreisfreie Stadt
  `DEG06`::: Eichsfeld
  `DEG07`::: Nordhausen
  `DEG09`::: Unstrut-Hainich-Kreis
  `DEG0A`::: Kyffhäuserkreis
  `DEG0C`::: Gotha
  `DEG0D`::: Sömmerda
  `DEG0E`::: Hildburghausen
  `DEG0G`::: Weimarer Land
  `DEG0J`::: Saale-Holzland-Kreis
  `DEG0K`::: Saale-Orla-Kreis
  `DEG0L`::: Greiz
  `DEG0M`::: Altenburger Land
  `DEG0Q`::: Schmalkalden-Meiningen
  `DEG0R`::: Wartburgkreis
  `DEG0S`::: Suhl, Kreisfreie Stadt
  `DEG0T`::: Ilm-Kreis
  `DEG0U`::: Saalfeld-Rudolstadt
  `DEG0V`::: Sonneberg
  `DEZZZ`::: Extra-Regio NUTS 3
  `DK011`::: Byen København
  `DK012`::: Københavns omegn
  `DK013`::: Nordsjælland
  `DK014`::: Bornholm
  `DK021`::: Østsjælland
  `DK022`::: Vest- og Sydsjælland
  `DK031`::: Fyn
  `DK032`::: Sydjylland
  `DK041`::: Vestjylland
  `DK042`::: Østjylland
  `DK050`::: Nordjylland
  `DKZZZ`::: Extra-Regio NUTS 3
  `EE001`::: Põhja-Eesti
  `EE004`::: Lääne-Eesti
  `EE008`::: Lõuna-Eesti
  `EE009`::: Kesk-Eesti
  `EE00A`::: Kirde-Eesti
  `EEZZZ`::: Extra-Regio NUTS 3
  `EL301`::: Βόρειος Τομέας Αθηνών
  `EL302`::: Δυτικός Τομέας Αθηνών
  `EL303`::: Κεντρικός Τομέας Αθηνών
  `EL304`::: Νότιος Τομέας Αθηνών
  `EL305`::: Ανατολική Αττική
  `EL306`::: Δυτική Αττική
  `EL307`::: Πειραιάς, Νήσοι
  `EL411`::: Λέσβος, Λήμνος
  `EL412`::: Ικαρία, Σάμος
  `EL413`::: Χίος
  `EL421`::: Κάλυμνος, Κάρπαθος – Ηρωική Νήσος Κάσος, Κως, Ρόδος
  `EL422`::: Άνδρος, Θήρα, Κέα, Μήλος, Μύκονος, Νάξος, Πάρος, Σύρος, Τήνος
  `EL431`::: Ηράκλειο
  `EL432`::: Λασίθι
  `EL433`::: Ρέθυμνο
  `EL434`::: Χανιά
  `EL511`::: Έβρος
  `EL512`::: Ξάνθη
  `EL513`::: Ροδόπη
  `EL514`::: Δράμα
  `EL515`::: Θάσος, Καβάλα
  `EL521`::: Ημαθία
  `EL522`::: Θεσσαλονίκη
  `EL523`::: Κιλκίς
  `EL524`::: Πέλλα
  `EL525`::: Πιερία
  `EL526`::: Σέρρες
  `EL527`::: Χαλκιδική
  `EL531`::: Γρεβενά, Κοζάνη
  `EL532`::: Καστοριά
  `EL533`::: Φλώρινα
  `EL541`::: Άρτα, Πρέβεζα
  `EL542`::: Θεσπρωτία
  `EL543`::: Ιωάννινα
  `EL611`::: Καρδίτσα, Τρίκαλα
  `EL612`::: Λάρισα
  `EL613`::: Μαγνησία, Σποράδες
  `EL621`::: Ζάκυνθος
  `EL622`::: Κέρκυρα
  `EL623`::: Ιθάκη, Κεφαλληνία
  `EL624`::: Λευκάδα
  `EL631`::: Αιτωλοακαρνανία
  `EL632`::: Αχαΐα
  `EL633`::: Ηλεία
  `EL641`::: Βοιωτία
  `EL642`::: Εύβοια
  `EL643`::: Ευρυτανία
  `EL644`::: Φθιώτιδα
  `EL645`::: Φωκίδα
  `EL651`::: Αργολίδα, Αρκαδία
  `EL652`::: Κορινθία
  `EL653`::: Λακωνία, Μεσσηνία
  `ELZZZ`::: Extra-Regio NUTS 3
  `ES111`::: A Coruña
  `ES112`::: Lugo
  `ES113`::: Ourense
  `ES114`::: Pontevedra
  `ES120`::: Asturias
  `ES130`::: Cantabria
  `ES211`::: Araba/Álava
  `ES212`::: Gipuzkoa
  `ES213`::: Bizkaia
  `ES220`::: Navarra
  `ES230`::: La Rioja
  `ES241`::: Huesca
  `ES242`::: Teruel
  `ES243`::: Zaragoza
  `ES300`::: Madrid
  `ES411`::: Ávila
  `ES412`::: Burgos
  `ES413`::: León
  `ES414`::: Palencia
  `ES415`::: Salamanca
  `ES416`::: Segovia
  `ES417`::: Soria
  `ES418`::: Valladolid
  `ES419`::: Zamora
  `ES421`::: Albacete
  `ES422`::: Ciudad Real
  `ES423`::: Cuenca
  `ES424`::: Guadalajara
  `ES425`::: Toledo
  `ES431`::: Badajoz
  `ES432`::: Cáceres
  `ES511`::: Barcelona
  `ES512`::: Girona
  `ES513`::: Lleida
  `ES514`::: Tarragona
  `ES521`::: Alicante / Alacant
  `ES522`::: Castellón / Castelló
  `ES523`::: Valencia / València
  `ES531`::: Eivissa y Formentera
  `ES532`::: Mallorca
  `ES533`::: Menorca
  `ES611`::: Almería
  `ES612`::: Cádiz
  `ES613`::: Córdoba
  `ES614`::: Granada
  `ES615`::: Huelva
  `ES616`::: Jaén
  `ES617`::: Málaga
  `ES618`::: Sevilla
  `ES620`::: Murcia
  `ES630`::: Ceuta
  `ES640`::: Melilla
  `ES703`::: El Hierro
  `ES704`::: Fuerteventura
  `ES705`::: Gran Canaria
  `ES706`::: La Gomera
  `ES707`::: La Palma
  `ES708`::: Lanzarote
  `ES709`::: Tenerife
  `ESZZZ`::: Extra-Regio NUTS 3
  `FI196`::: Satakunta
  `FI198`::: Keski-Suomi
  `FI199`::: Etelä-Pohjanmaa
  `FI19A`::: Pohjanmaa
  `FI19B`::: Pirkanmaa
  `FI1B1`::: Helsinki-Uusimaa
  `FI1C1`::: Varsinais-Suomi
  `FI1C2`::: Kanta-Häme
  `FI1C5`::: Etelä-Karjala
  `FI1C6`::: Päijät-Häme
  `FI1C7`::: Kymenlaakso
  `FI1D5`::: Keski-Pohjanmaa
  `FI1D7`::: Lappi
  `FI1D8`::: Kainuu
  `FI1D9`::: Pohjois-Pohjanmaa
  `FI1DA`::: Etelä-Savo
  `FI1DB`::: Pohjois-Savo
  `FI1DC`::: Pohjois-Karjala
  `FI200`::: Åland
  `FIZZZ`::: Extra-Regio NUTS 3
  `FR101`::: Paris
  `FR102`::: Seine-et-Marne
  `FR103`::: Yvelines
  `FR104`::: Essonne
  `FR105`::: Hauts-de-Seine
  `FR106`::: Seine-Saint-Denis
  `FR107`::: Val-de-Marne
  `FR108`::: Val-d’Oise
  `FRB01`::: Cher
  `FRB02`::: Eure-et-Loir
  `FRB03`::: Indre
  `FRB04`::: Indre-et-Loire
  `FRB05`::: Loir-et-Cher
  `FRB06`::: Loiret
  `FRC11`::: Côte-d’Or
  `FRC12`::: Nièvre
  `FRC13`::: Saône-et-Loire
  `FRC14`::: Yonne
  `FRC21`::: Doubs
  `FRC22`::: Jura
  `FRC23`::: Haute-Saône
  `FRC24`::: Territoire de Belfort
  `FRD11`::: Calvados
  `FRD12`::: Manche
  `FRD13`::: Orne
  `FRD21`::: Eure
  `FRD22`::: Seine-Maritime
  `FRE11`::: Nord
  `FRE12`::: Pas-de-Calais
  `FRE21`::: Aisne
  `FRE22`::: Oise
  `FRE23`::: Somme
  `FRF11`::: Bas-Rhin
  `FRF12`::: Haut-Rhin
  `FRF21`::: Ardennes
  `FRF22`::: Aube
  `FRF23`::: Marne
  `FRF24`::: Haute-Marne
  `FRF31`::: Meurthe-et-Moselle
  `FRF32`::: Meuse
  `FRF33`::: Moselle
  `FRF34`::: Vosges
  `FRG01`::: Loire-Atlantique
  `FRG02`::: Maine-et-Loire
  `FRG03`::: Mayenne
  `FRG04`::: Sarthe
  `FRG05`::: Vendée
  `FRH01`::: Côtes-d’Armor
  `FRH02`::: Finistère
  `FRH03`::: Ille-et-Vilaine
  `FRH04`::: Morbihan
  `FRI11`::: Dordogne
  `FRI12`::: Gironde
  `FRI13`::: Landes
  `FRI14`::: Lot-et-Garonne
  `FRI15`::: Pyrénées-Atlantiques
  `FRI21`::: Corrèze
  `FRI22`::: Creuse
  `FRI23`::: Haute-Vienne
  `FRI31`::: Charente
  `FRI32`::: Charente-Maritime
  `FRI33`::: Deux-Sèvres
  `FRI34`::: Vienne
  `FRJ11`::: Aude
  `FRJ12`::: Gard
  `FRJ13`::: Hérault
  `FRJ14`::: Lozère
  `FRJ15`::: Pyrénées-Orientales
  `FRJ21`::: Ariège
  `FRJ22`::: Aveyron
  `FRJ23`::: Haute-Garonne
  `FRJ24`::: Gers
  `FRJ25`::: Lot
  `FRJ26`::: Hautes-Pyrénées
  `FRJ27`::: Tarn
  `FRJ28`::: Tarn-et-Garonne
  `FRK11`::: Allier
  `FRK12`::: Cantal
  `FRK13`::: Haute-Loire
  `FRK14`::: Puy-de-Dôme
  `FRK21`::: Ain
  `FRK22`::: Ardèche
  `FRK23`::: Drôme
  `FRK24`::: Isère
  `FRK25`::: Loire
  `FRK26`::: Rhône
  `FRK27`::: Savoie
  `FRK28`::: Haute-Savoie
  `FRL01`::: Alpes-de-Haute-Provence
  `FRL02`::: Hautes-Alpes
  `FRL03`::: Alpes-Maritimes
  `FRL04`::: Bouches-du-Rhône
  `FRL05`::: Var
  `FRL06`::: Vaucluse
  `FRM01`::: Corse-du-Sud
  `FRM02`::: Haute-Corse
  `FRY10`::: Guadeloupe
  `FRY20`::: Martinique
  `FRY30`::: Guyane
  `FRY40`::: La Réunion
  `FRY50`::: Mayotte
  `FRZZZ`::: Extra-Regio NUTS 3
  `HR021`::: Bjelovarsko-bilogorska županija
  `HR022`::: Virovitičko-podravska županija
  `HR023`::: Požeško-slavonska županija
  `HR024`::: Brodsko-posavska županija
  `HR025`::: Osječko-baranjska županija
  `HR026`::: Vukovarsko-srijemska županija
  `HR027`::: Karlovačka županija
  `HR028`::: Sisačko-moslavačka županija
  `HR031`::: Primorsko-goranska županija
  `HR032`::: Ličko-senjska županija
  `HR033`::: Zadarska županija
  `HR034`::: Šibensko-kninska županija
  `HR035`::: Splitsko-dalmatinska županija
  `HR036`::: Istarska županija
  `HR037`::: Dubrovačko-neretvanska županija
  `HR050`::: Grad Zagreb
  `HR061`::: Međimurska županija
  `HR062`::: Varaždinska županija
  `HR063`::: Koprivničko-križevačka županija
  `HR064`::: Krapinsko-zagorska županija
  `HR065`::: Zagrebačka županija
  `HRZZZ`::: Extra-Regio NUTS 3
  `HU110`::: Budapest
  `HU120`::: Pest
  `HU211`::: Fejér
  `HU212`::: Komárom-Esztergom
  `HU213`::: Veszprém
  `HU221`::: Győr-Moson-Sopron
  `HU222`::: Vas
  `HU223`::: Zala
  `HU231`::: Baranya
  `HU232`::: Somogy
  `HU233`::: Tolna
  `HU311`::: Borsod-Abaúj-Zemplén
  `HU312`::: Heves
  `HU313`::: Nógrád
  `HU321`::: Hajdú-Bihar
  `HU322`::: Jász-Nagykun-Szolnok
  `HU323`::: Szabolcs-Szatmár-Bereg
  `HU331`::: Bács-Kiskun
  `HU332`::: Békés
  `HU333`::: Csongrád-Csanád
  `HUZZZ`::: Extra-Regio NUTS 3
  `IE041`::: Border
  `IE042`::: West
  `IE051`::: Mid-West
  `IE052`::: South-East
  `IE053`::: South-West
  `IE061`::: Dublin
  `IE062`::: Mid-East
  `IE063`::: Midland
  `IEZZZ`::: Extra-Regio NUTS 3
  `IS001`::: Höfuðborgarsvæði
  `IS002`::: Landsbyggð
  `ISZZZ`::: Extra-Regio NUTS 3
  `ITC11`::: Torino
  `ITC12`::: Vercelli
  `ITC13`::: Biella
  `ITC14`::: Verbano-Cusio-Ossola
  `ITC15`::: Novara
  `ITC16`::: Cuneo
  `ITC17`::: Asti
  `ITC18`::: Alessandria
  `ITC20`::: Valle d’Aosta/Vallée d’Aoste
  `ITC31`::: Imperia
  `ITC32`::: Savona
  `ITC33`::: Genova
  `ITC34`::: La Spezia
  `ITC41`::: Varese
  `ITC42`::: Como
  `ITC43`::: Lecco
  `ITC44`::: Sondrio
  `ITC46`::: Bergamo
  `ITC47`::: Brescia
  `ITC48`::: Pavia
  `ITC49`::: Lodi
  `ITC4A`::: Cremona
  `ITC4B`::: Mantova
  `ITC4C`::: Milano
  `ITC4D`::: Monza e della Brianza
  `ITF11`::: L’Aquila
  `ITF12`::: Teramo
  `ITF13`::: Pescara
  `ITF14`::: Chieti
  `ITF21`::: Isernia
  `ITF22`::: Campobasso
  `ITF31`::: Caserta
  `ITF32`::: Benevento
  `ITF33`::: Napoli
  `ITF34`::: Avellino
  `ITF35`::: Salerno
  `ITF43`::: Taranto
  `ITF44`::: Brindisi
  `ITF45`::: Lecce
  `ITF46`::: Foggia
  `ITF47`::: Bari
  `ITF48`::: Barletta-Andria-Trani
  `ITF51`::: Potenza
  `ITF52`::: Matera
  `ITF61`::: Cosenza
  `ITF62`::: Crotone
  `ITF63`::: Catanzaro
  `ITF64`::: Vibo Valentia
  `ITF65`::: Reggio Calabria
  `ITG11`::: Trapani
  `ITG12`::: Palermo
  `ITG13`::: Messina
  `ITG14`::: Agrigento
  `ITG15`::: Caltanissetta
  `ITG16`::: Enna
  `ITG17`::: Catania
  `ITG18`::: Ragusa
  `ITG19`::: Siracusa
  `ITG2D`::: Sassari
  `ITG2E`::: Nuoro
  `ITG2F`::: Cagliari
  `ITG2G`::: Oristano
  `ITG2H`::: Sud Sardegna
  `ITH10`::: Bolzano-Bozen
  `ITH20`::: Trento
  `ITH31`::: Verona
  `ITH32`::: Vicenza
  `ITH33`::: Belluno
  `ITH34`::: Treviso
  `ITH35`::: Venezia
  `ITH36`::: Padova
  `ITH37`::: Rovigo
  `ITH41`::: Pordenone
  `ITH42`::: Udine
  `ITH43`::: Gorizia
  `ITH44`::: Trieste
  `ITH51`::: Piacenza
  `ITH52`::: Parma
  `ITH53`::: Reggio nell’Emilia
  `ITH54`::: Modena
  `ITH55`::: Bologna
  `ITH56`::: Ferrara
  `ITH57`::: Ravenna
  `ITH58`::: Forlì-Cesena
  `ITH59`::: Rimini
  `ITI11`::: Massa-Carrara
  `ITI12`::: Lucca
  `ITI13`::: Pistoia
  `ITI14`::: Firenze
  `ITI15`::: Prato
  `ITI16`::: Livorno
  `ITI17`::: Pisa
  `ITI18`::: Arezzo
  `ITI19`::: Siena
  `ITI1A`::: Grosseto
  `ITI21`::: Perugia
  `ITI22`::: Terni
  `ITI31`::: Pesaro e Urbino
  `ITI32`::: Ancona
  `ITI33`::: Macerata
  `ITI34`::: Ascoli Piceno
  `ITI35`::: Fermo
  `ITI41`::: Viterbo
  `ITI42`::: Rieti
  `ITI43`::: Roma
  `ITI44`::: Latina
  `ITI45`::: Frosinone
  `ITZZZ`::: Extra-Regio NUTS 3
  `LI000`::: Liechtenstein
  `LIZZZ`::: Extra-Regio NUTS 3
  `LT011`::: Vilniaus apskritis
  `LT021`::: Alytaus apskritis
  `LT022`::: Kauno apskritis
  `LT023`::: Klaipėdos apskritis
  `LT024`::: Marijampolės apskritis
  `LT025`::: Panevėžio apskritis
  `LT026`::: Šiaulių apskritis
  `LT027`::: Tauragės apskritis
  `LT028`::: Telšių apskritis
  `LT029`::: Utenos apskritis
  `LTZZZ`::: Extra-Regio NUTS 3
  `LU000`::: Luxembourg
  `LUZZZ`::: Extra-Regio NUTS 3
  `LV005`::: Latgale
  `LV009`::: Zemgale
  `LV00A`::: Rīga
  `LV00B`::: Kurzeme
  `LV00C`::: Vidzeme
  `LVZZZ`::: Extra-Regio NUTS 3
  `ME000`::: Црна Гора
  `MEZZZ`::: Extra-Regio NUTS 3
  `MK001`::: Вардарски
  `MK002`::: Источен
  `MK003`::: Југозападен
  `MK004`::: Југоисточен
  `MK005`::: Пелагониски
  `MK006`::: Полошки
  `MK007`::: Североисточен
  `MK008`::: Скопски
  `MKZZZ`::: Extra-Regio NUTS 3
  `MT001`::: Malta
  `MT002`::: Gozo and Comino / Għawdex u Kemmuna
  `MTZZZ`::: Extra-Regio NUTS 3
  `NL112`::: Delfzijl en omgeving
  `NL114`::: Oost-Groningen
  `NL115`::: Overig Groningen
  `NL126`::: Zuidoost-Friesland
  `NL127`::: Noord-Friesland
  `NL128`::: Zuidwest-Friesland
  `NL131`::: Noord-Drenthe
  `NL132`::: Zuidoost-Drenthe
  `NL133`::: Zuidwest-Drenthe
  `NL211`::: Noord-Overijssel
  `NL212`::: Zuidwest-Overijssel
  `NL213`::: Twente
  `NL221`::: Veluwe
  `NL224`::: Zuidwest-Gelderland
  `NL225`::: Achterhoek
  `NL226`::: Arnhem/Nijmegen
  `NL230`::: Flevoland
  `NL321`::: Kop van Noord-Holland
  `NL323`::: IJmond
  `NL325`::: Zaanstreek
  `NL327`::: Het Gooi en Vechtstreek
  `NL328`::: Alkmaar en omgeving
  `NL32A`::: Agglomeratie Haarlem
  `NL32B`::: Groot-Amsterdam
  `NL341`::: Zeeuwsch-Vlaanderen
  `NL342`::: Overig Zeeland
  `NL350`::: Utrecht
  `NL361`::: Agglomeratie ’s-Gravenhage
  `NL362`::: Delft en Westland
  `NL363`::: Agglomeratie Leiden en Bollenstreek
  `NL364`::: Zuidoost-Zuid-Holland
  `NL365`::: Oost-Zuid-Holland
  `NL366`::: Groot-Rijnmond
  `NL411`::: West-Noord-Brabant
  `NL414`::: Zuidoost-Noord-Brabant
  `NL415`::: Midden-Noord-Brabant
  `NL416`::: Noordoost-Noord-Brabant
  `NL421`::: Noord-Limburg
  `NL422`::: Midden-Limburg
  `NL423`::: Zuid-Limburg
  `NLZZZ`::: Extra-Regio NUTS 3
  `NO020`::: Innlandet
  `NO060`::: Trøndelag/Trööndelage
  `NO071`::: Nordland/Nordlánnda
  `NO072`::: Troms/Romsa/Tromssa
  `NO073`::: Finnmark/Finnmárku/Finmarkku
  `NO081`::: Oslo
  `NO083`::: Østfold
  `NO084`::: Akershus
  `NO085`::: Buskerud
  `NO092`::: Agder
  `NO093`::: Vestfold
  `NO094`::: Telemark
  `NO0A1`::: Rogaland
  `NO0A2`::: Vestland
  `NO0A3`::: Møre og Romsdal
  `NO0B1`::: Jan Mayen
  `NO0B2`::: Svalbard
  `NOZZZ`::: Extra-Regio NUTS 3
  `PL213`::: Miasto Kraków
  `PL214`::: Krakowski
  `PL217`::: Tarnowski
  `PL218`::: Nowosądecki
  `PL219`::: Nowotarski
  `PL21A`::: Oświęcimski
  `PL224`::: Częstochowski
  `PL225`::: Bielski
  `PL227`::: Rybnicki
  `PL228`::: Bytomski
  `PL229`::: Gliwicki
  `PL22A`::: Katowicki
  `PL22B`::: Sosnowiecki
  `PL22C`::: Tyski
  `PL411`::: Pilski
  `PL414`::: Koniński
  `PL415`::: Miasto Poznań
  `PL416`::: Kaliski
  `PL417`::: Leszczyński
  `PL418`::: Poznański
  `PL424`::: Miasto Szczecin
  `PL426`::: Koszaliński
  `PL427`::: Szczecinecko-pyrzycki
  `PL428`::: Szczeciński
  `PL431`::: Gorzowski
  `PL432`::: Zielonogórski
  `PL514`::: Miasto Wrocław
  `PL515`::: Jeleniogórski
  `PL516`::: Legnicko-Głogowski
  `PL517`::: Wałbrzyski
  `PL518`::: Wrocławski
  `PL523`::: Nyski
  `PL524`::: Opolski
  `PL613`::: Bydgosko-Toruński
  `PL616`::: Grudziądzki
  `PL617`::: Inowrocławski
  `PL618`::: Świecki
  `PL619`::: Włocławski
  `PL621`::: Elbląski
  `PL622`::: Olsztyński
  `PL623`::: Ełcki
  `PL633`::: Trójmiejski
  `PL634`::: Gdański
  `PL636`::: Słupski
  `PL637`::: Chojnicki
  `PL638`::: Starogardzki
  `PL711`::: Miasto Łódź
  `PL712`::: Łódzki
  `PL713`::: Piotrkowski
  `PL714`::: Sieradzki
  `PL715`::: Skierniewicki
  `PL721`::: Kielecki
  `PL722`::: Sandomiersko-jędrzejowski
  `PL811`::: Bialski
  `PL812`::: Chełmsko-zamojski
  `PL814`::: Lubelski
  `PL815`::: Puławski
  `PL821`::: Krośnieński
  `PL822`::: Przemyski
  `PL823`::: Rzeszowski
  `PL824`::: Tarnobrzeski
  `PL841`::: Białostocki
  `PL842`::: Łomżyński
  `PL843`::: Suwalski
  `PL911`::: Miasto Warszawa
  `PL912`::: Warszawski wschodni
  `PL913`::: Warszawski zachodni
  `PL921`::: Radomski
  `PL922`::: Ciechanowski
  `PL923`::: Płocki
  `PL924`::: Ostrołęcki
  `PL925`::: Siedlecki
  `PL926`::: Żyrardowski
  `PLZZZ`::: Extra-Regio NUTS 3
  `PT111`::: Alto Minho
  `PT112`::: Cávado
  `PT119`::: Ave
  `PT11A`::: Área Metropolitana do Porto
  `PT11B`::: Alto Tâmega e Barroso
  `PT11C`::: Tâmega e Sousa
  `PT11D`::: Douro
  `PT11E`::: Terras de Trás-os-Montes
  `PT150`::: Algarve
  `PT191`::: Região de Aveiro
  `PT192`::: Região de Coimbra
  `PT193`::: Região de Leiria
  `PT194`::: Viseu Dão Lafões
  `PT195`::: Beira Baixa
  `PT196`::: Beiras e Serra da Estrela
  `PT1A0`::: Grande Lisboa
  `PT1B0`::: Península de Setúbal
  `PT1C1`::: Alentejo Litoral
  `PT1C2`::: Baixo Alentejo
  `PT1C3`::: Alto Alentejo
  `PT1C4`::: Alentejo Central
  `PT1D1`::: Oeste
  `PT1D2`::: Médio Tejo
  `PT1D3`::: Lezíria do Tejo
  `PT200`::: Região Autónoma dos Açores
  `PT300`::: Região Autónoma da Madeira
  `PTZZZ`::: Extra-Regio NUTS 3
  `RO111`::: Bihor
  `RO112`::: Bistriţa-Năsăud
  `RO113`::: Cluj
  `RO114`::: Maramureş
  `RO115`::: Satu Mare
  `RO116`::: Sălaj
  `RO121`::: Alba
  `RO122`::: Braşov
  `RO123`::: Covasna
  `RO124`::: Harghita
  `RO125`::: Mureş
  `RO126`::: Sibiu
  `RO211`::: Bacău
  `RO212`::: Botoşani
  `RO213`::: Iaşi
  `RO214`::: Neamţ
  `RO215`::: Suceava
  `RO216`::: Vaslui
  `RO221`::: Brăila
  `RO222`::: Buzău
  `RO223`::: Constanţa
  `RO224`::: Galaţi
  `RO225`::: Tulcea
  `RO226`::: Vrancea
  `RO311`::: Argeş
  `RO312`::: Călăraşi
  `RO313`::: Dâmboviţa
  `RO314`::: Giurgiu
  `RO315`::: Ialomiţa
  `RO316`::: Prahova
  `RO317`::: Teleorman
  `RO321`::: Bucureşti
  `RO322`::: Ilfov
  `RO411`::: Dolj
  `RO412`::: Gorj
  `RO413`::: Mehedinţi
  `RO414`::: Olt
  `RO415`::: Vâlcea
  `RO421`::: Arad
  `RO422`::: Caraş-Severin
  `RO423`::: Hunedoara
  `RO424`::: Timiş
  `ROZZZ`::: Extra-Regio NUTS 3
  `RS110`::: Београдска област
  `RS121`::: Западнобачка област
  `RS122`::: Јужнобанатска област
  `RS123`::: Јужнобачка област
  `RS124`::: Севернобанатска област
  `RS125`::: Севернобачка област
  `RS126`::: Средњобанатска област
  `RS127`::: Сремска област
  `RS211`::: Златиборска област
  `RS212`::: Колубарска област
  `RS213`::: Мачванска област
  `RS214`::: Моравичка област
  `RS215`::: Поморавска област
  `RS216`::: Расинска област
  `RS217`::: Рашка област
  `RS218`::: Шумадијска област
  `RS221`::: Борска област
  `RS222`::: Браничевска област
  `RS223`::: Зајечарска област
  `RS224`::: Јабланичка област
  `RS225`::: Нишавска област
  `RS226`::: Пиротска област
  `RS227`::: Подунавска област
  `RS228`::: Пчињска област
  `RS229`::: Топличка област
  `RSZZZ`::: Extra-Regio NUTS 3
  `SE110`::: Stockholms län
  `SE121`::: Uppsala län
  `SE122`::: Södermanlands län
  `SE123`::: Östergötlands län
  `SE124`::: Örebro län
  `SE125`::: Västmanlands län
  `SE211`::: Jönköpings län
  `SE212`::: Kronobergs län
  `SE213`::: Kalmar län
  `SE214`::: Gotlands län
  `SE221`::: Blekinge län
  `SE224`::: Skåne län
  `SE231`::: Hallands län
  `SE232`::: Västra Götalands län
  `SE311`::: Värmlands län
  `SE312`::: Dalarnas län
  `SE313`::: Gävleborgs län
  `SE321`::: Västernorrlands län
  `SE322`::: Jämtlands län
  `SE331`::: Västerbottens län
  `SE332`::: Norrbottens län
  `SEZZZ`::: Extra-Regio NUTS 3
  `SI031`::: Pomurska
  `SI032`::: Podravska
  `SI033`::: Koroška
  `SI034`::: Savinjska
  `SI035`::: Zasavska
  `SI036`::: Posavska
  `SI037`::: Jugovzhodna Slovenija
  `SI038`::: Primorsko-notranjska
  `SI041`::: Osrednjeslovenska
  `SI042`::: Gorenjska
  `SI043`::: Goriška
  `SI044`::: Obalno-kraška
  `SIZZZ`::: Extra-Regio NUTS 3
  `SK010`::: Bratislavský kraj
  `SK021`::: Trnavský kraj
  `SK022`::: Trenčiansky kraj
  `SK023`::: Nitriansky kraj
  `SK031`::: Žilinský kraj
  `SK032`::: Banskobystrický kraj
  `SK041`::: Prešovský kraj
  `SK042`::: Košický kraj
  `SKZZZ`::: Extra-Regio NUTS 3
  `TR100`::: İstanbul
  `TR211`::: Tekirdağ
  `TR212`::: Edirne
  `TR213`::: Kırklareli
  `TR221`::: Balıkesir
  `TR222`::: Çanakkale
  `TR310`::: İzmir
  `TR321`::: Aydın
  `TR322`::: Denizli
  `TR323`::: Muğla
  `TR331`::: Manisa
  `TR332`::: Afyonkarahisar
  `TR333`::: Kütahya
  `TR334`::: Uşak
  `TR411`::: Bursa
  `TR412`::: Eskişehir
  `TR413`::: Bilecik
  `TR421`::: Kocaeli
  `TR422`::: Sakarya
  `TR423`::: Düzce
  `TR424`::: Bolu
  `TR425`::: Yalova
  `TR510`::: Ankara
  `TR521`::: Konya
  `TR522`::: Karaman
  `TR611`::: Antalya
  `TR612`::: Isparta
  `TR613`::: Burdur
  `TR621`::: Adana
  `TR622`::: Mersin
  `TR631`::: Hatay
  `TR632`::: Kahramanmaraş
  `TR633`::: Osmaniye
  `TR711`::: Kırıkkale
  `TR712`::: Aksaray
  `TR713`::: Niğde
  `TR714`::: Nevşehir
  `TR715`::: Kırşehir
  `TR721`::: Kayseri
  `TR722`::: Sivas
  `TR723`::: Yozgat
  `TR811`::: Zonguldak
  `TR812`::: Karabük
  `TR813`::: Bartın
  `TR821`::: Kastamonu
  `TR822`::: Çankırı
  `TR823`::: Sinop
  `TR831`::: Samsun
  `TR832`::: Tokat
  `TR833`::: Çorum
  `TR834`::: Amasya
  `TR901`::: Trabzon
  `TR902`::: Ordu
  `TR903`::: Giresun
  `TR904`::: Rize
  `TR905`::: Artvin
  `TR906`::: Gümüşhane
  `TRA11`::: Erzurum
  `TRA12`::: Erzincan
  `TRA13`::: Bayburt
  `TRA21`::: Ağrı
  `TRA22`::: Kars
  `TRA23`::: Iğdır
  `TRA24`::: Ardahan
  `TRB11`::: Malatya
  `TRB12`::: Elazığ
  `TRB13`::: Bingöl
  `TRB14`::: Tunceli
  `TRB21`::: Van
  `TRB22`::: Muş
  `TRB23`::: Bitlis
  `TRB24`::: Hakkari
  `TRC11`::: Gaziantep
  `TRC12`::: Adıyaman
  `TRC13`::: Kilis
  `TRC21`::: Şanlıurfa
  `TRC22`::: Diyarbakır
  `TRC31`::: Mardin
  `TRC32`::: Batman
  `TRC33`::: Şırnak
  `TRC34`::: Siirt
  `TRZZZ`::: Extra-Regio NUTS 3
  `XK001`::: Prishtinë/Priština
  `XK002`::: Mitrovicë/Mitrovica
  `XK003`::: Pejë/Peć
  `XK004`::: Prizren/Prizren
  `XK005`::: Ferizaj/Uroševac
  `XK006`::: Gjilan/Gnjilane
  `XK007`::: Gjakovë/Đakovica
  `XKZZZ`::: Extra-Regio NUTS 3
