= `organisation-role` codelist
:navtitle: Codelists

This table provides the list of the different functions of the organisations in a procurement procedure.
[horizontal]
Version:: 20260318-0
URI:: http://publications.europa.eu/resource/dataset/organisation-role
Tailored by:: xref:code-lists/organisation-role-service.adoc[`organisation-role-service`], xref:code-lists/review-requester-type.adoc[`review-requester-type`]
Structure:: flat
EU Vocabularies:: https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/organisation-role[View on EU Vocabularies^]

== Codes
[horizontal]
  `ben-own`::: Beneficial owner
  `buyer`::: Buyer
  `cpb-acq`::: Central purchasing body acquiring supplies and/or services intended for other buyers
  `cpb-awa`::: Central purchasing body awarding public contracts or concluding framework agreements for works, supplies or services intended for other buyers
  `info-emp`::: Organisation providing information on employment legislation
  `info-envir`::: Organisation providing information on environmental legislation
  `info-tax`::: Organisation providing information on fiscal legislation
  `mediator`::: Mediation organisation
  `rev-req`::: Organisation (or person) requesting review that has or has had an interest in a contract and who has been or risks being harmed by an alleged infringement
  `reviewer`::: Review organisation
  `serv-prov`::: Procurement service provider
  `subcont`::: Subcontractor
  `ted-esen`::: TED eSender
  `tenderer`::: Tenderer
  `winner`::: Winner
