= `received-submission-type` codelist
:navtitle: Codelists

This table provides the list of relevant categories used to classify tenders or requests to participate received within the context of public procurement.
[horizontal]
Version:: 20260617-0
URI:: http://publications.europa.eu/resource/dataset/received-submission-type
Structure:: flat
EU Vocabularies:: https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/received-submission-type[View on EU Vocabularies^]
Used in:: xref:business-terms/BT-760.adoc[`BT-760`] Received Submissions Type

== Codes
[horizontal]
  `part-req`::: Requests to participate
  `t-esubm`::: Tenders submitted electronically
  `t-large`::: Tenders from large enterprises
  `t-med`::: Tenders from medium enterprises
  `t-micro`::: Tenders from micro enterprises
  `t-no-eea`::: Tenders from organisations from non-EEA countries
  `t-no-verif`::: Tenders for which it has not been verified if they are admissible or inadmissible
  `t-oth-eea`::: Tenders from organisations registered from an EEA country different from the country of the buyer
  `t-small`::: Tenders from small enterprises
  `t-sme`::: Tenders from SMEs
  `t-verif-inad`::: Tenders verified and inadmissible
  `t-verif-inad-low`::: Tenders verified and inadmissible because of an abnormally low price or cost
  `tenders`::: Tenders
