= `BT-195`: Unpublished Identifier
:navtitle: Business Terms

[horizontal]
Type:: IDENTIFIER

== Fields
[horizontal]
  `BT-195(BT-09)-Procedure`:: Unpublished Identifier
  `BT-195(BT-09)-Procedure-List`:: Unpublished Identifier Listname
  `BT-195(BT-105)-Procedure`:: Unpublished Identifier
  `BT-195(BT-105)-Procedure-List`:: Unpublished Identifier Listname
  `BT-195(BT-106)-Procedure`:: Unpublished Identifier
  `BT-195(BT-106)-Procedure-List`:: Unpublished Identifier Listname
  `BT-195(BT-1118)-NoticeResult`:: Unpublished Identifier
  `BT-195(BT-1118)-NoticeResult-List`:: Unpublished Identifier Listname
  `BT-195(BT-118)-NoticeResult`:: Unpublished Identifier
  `BT-195(BT-118)-NoticeResult-List`:: Unpublished Identifier Listname
  `BT-195(BT-1252)-Procedure`:: Unpublished Identifier
  `BT-195(BT-1252)-Procedure-List`:: Unpublished Identifier Listname
  `BT-195(BT-135)-Procedure`:: Unpublished Identifier
  `BT-195(BT-135)-Procedure-List`:: Unpublished Identifier Listname
  `BT-195(BT-1351)-Procedure`:: Unpublished Identifier
  `BT-195(BT-1351)-Procedure-List`:: Unpublished Identifier Listname
  `BT-195(BT-136)-Procedure`:: Unpublished Identifier
  `BT-195(BT-136)-Procedure-List`:: Unpublished Identifier Listname
  `BT-195(BT-142)-LotResult`:: Unpublished Identifier
  `BT-195(BT-142)-LotResult-List`:: Unpublished Identifier Listname
  `BT-195(BT-144)-LotResult`:: Unpublished Identifier
  `BT-195(BT-144)-LotResult-List`:: Unpublished Identifier Listname
  `BT-195(BT-156)-NoticeResult`:: Unpublished Identifier
  `BT-195(BT-156)-NoticeResult-List`:: Unpublished Identifier Listname
  `BT-195(BT-1561)-NoticeResult`:: Unpublished Identifier
  `BT-195(BT-1561)-NoticeResult-List`:: Unpublished Identifier Listname
  `BT-195(BT-160)-Tender`:: Unpublished Identifier
  `BT-195(BT-160)-Tender-List`:: Unpublished Identifier Listname
  `BT-195(BT-161)-NoticeResult`:: Unpublished Identifier
  `BT-195(BT-161)-NoticeResult-List`:: Unpublished Identifier Listname
  `BT-195(BT-162)-Tender`:: Unpublished Identifier
  `BT-195(BT-162)-Tender-List`:: Unpublished Identifier Listname
  `BT-195(BT-163)-Tender`:: Unpublished Identifier
  `BT-195(BT-163)-Tender-List`:: Unpublished Identifier Listname
  `BT-195(BT-171)-Tender`:: Unpublished Identifier
  `BT-195(BT-171)-Tender-List`:: Unpublished Identifier Listname
  `BT-195(BT-191)-Tender`:: Unpublished Identifier
  `BT-195(BT-191)-Tender-List`:: Unpublished Identifier Listname
  `BT-195(BT-193)-Tender`:: Unpublished Identifier
  `BT-195(BT-193)-Tender-List`:: Unpublished Identifier Listname
  `BT-195(BT-539)-Lot`:: Unpublished Identifier
  `BT-195(BT-539)-Lot-List`:: Unpublished Identifier Listname
  `BT-195(BT-539)-LotsGroup`:: Unpublished Identifier
  `BT-195(BT-539)-LotsGroup-List`:: Unpublished Identifier Listname
  `BT-195(BT-540)-Lot`:: Unpublished Identifier
  `BT-195(BT-540)-Lot-List`:: Unpublished Identifier Listname
  `BT-195(BT-540)-LotsGroup`:: Unpublished Identifier
  `BT-195(BT-540)-LotsGroup-List`:: Unpublished Identifier Listname
  `BT-195(BT-541)-Lot-Fixed`:: Unpublished Identifier
  `BT-195(BT-541)-Lot-Fixed-List`:: Unpublished Identifier Listname
  `BT-195(BT-541)-Lot-Threshold`:: Unpublished Identifier
  `BT-195(BT-541)-Lot-Threshold-List`:: Unpublished Identifier Listname
  `BT-195(BT-541)-Lot-Weight`:: Unpublished Identifier
  `BT-195(BT-541)-Lot-Weight-List`:: Unpublished Identifier Listname
  `BT-195(BT-541)-LotsGroup-Fixed`:: Unpublished Identifier
  `BT-195(BT-541)-LotsGroup-Fixed-List`:: Unpublished Identifier Listname
  `BT-195(BT-541)-LotsGroup-Threshold`:: Unpublished Identifier
  `BT-195(BT-541)-LotsGroup-Threshold-List`:: Unpublished Identifier Listname
  `BT-195(BT-541)-LotsGroup-Weight`:: Unpublished Identifier
  `BT-195(BT-541)-LotsGroup-Weight-List`:: Unpublished Identifier Listname
  `BT-195(BT-5421)-Lot`:: Unpublished Identifier
  `BT-195(BT-5421)-Lot-List`:: Unpublished Identifier Listname
  `BT-195(BT-5421)-LotsGroup`:: Unpublished Identifier
  `BT-195(BT-5421)-LotsGroup-List`:: Unpublished Identifier Listname
  `BT-195(BT-5422)-Lot`:: Unpublished Identifier
  `BT-195(BT-5422)-Lot-List`:: Unpublished Identifier Listname
  `BT-195(BT-5422)-LotsGroup`:: Unpublished Identifier
  `BT-195(BT-5422)-LotsGroup-List`:: Unpublished Identifier Listname
  `BT-195(BT-5423)-Lot`:: Unpublished Identifier
  `BT-195(BT-5423)-Lot-List`:: Unpublished Identifier Listname
  `BT-195(BT-5423)-LotsGroup`:: Unpublished Identifier
  `BT-195(BT-5423)-LotsGroup-List`:: Unpublished Identifier Listname
  `BT-195(BT-543)-Lot`:: Unpublished Identifier
  `BT-195(BT-543)-Lot-List`:: Unpublished Identifier Listname
  `BT-195(BT-543)-LotsGroup`:: Unpublished Identifier
  `BT-195(BT-543)-LotsGroup-List`:: Unpublished Identifier Listname
  `BT-195(BT-553)-Tender`:: Unpublished Identifier
  `BT-195(BT-553)-Tender-List`:: Unpublished Identifier Listname
  `BT-195(BT-554)-Tender`:: Unpublished Identifier
  `BT-195(BT-554)-Tender-List`:: Unpublished Identifier Listname
  `BT-195(BT-555)-Tender`:: Unpublished Identifier
  `BT-195(BT-555)-Tender-List`:: Unpublished Identifier Listname
  `BT-195(BT-556)-NoticeResult`:: Unpublished Identifier
  `BT-195(BT-556)-NoticeResult-List`:: Unpublished Identifier Listname
  `BT-195(BT-635)-LotResult`:: Unpublished Identifier
  `BT-195(BT-635)-LotResult-List`:: Unpublished Identifier Listname
  `BT-195(BT-636)-LotResult`:: Unpublished Identifier
  `BT-195(BT-636)-LotResult-List`:: Unpublished Identifier Listname
  `BT-195(BT-660)-LotResult`:: Unpublished Identifier
  `BT-195(BT-660)-LotResult-List`:: Unpublished Identifier Listname
  `BT-195(BT-709)-LotResult`:: Unpublished Identifier
  `BT-195(BT-709)-LotResult-List`:: Unpublished Identifier Listname
  `BT-195(BT-710)-LotResult`:: Unpublished Identifier
  `BT-195(BT-710)-LotResult-List`:: Unpublished Identifier Listname
  `BT-195(BT-711)-LotResult`:: Unpublished Identifier
  `BT-195(BT-711)-LotResult-List`:: Unpublished Identifier Listname
  `BT-195(BT-712)-LotResult`:: Unpublished Identifier
  `BT-195(BT-712)-LotResult-List`:: Unpublished Identifier Listname
  `BT-195(BT-720)-Tender`:: Unpublished Identifier
  `BT-195(BT-720)-Tender-List`:: Unpublished Identifier Listname
  `BT-195(BT-730)-Tender`:: Unpublished Identifier
  `BT-195(BT-730)-Tender-List`:: Unpublished Identifier Listname
  `BT-195(BT-731)-Tender`:: Unpublished Identifier
  `BT-195(BT-731)-Tender-List`:: Unpublished Identifier Listname
  `BT-195(BT-733)-Lot`:: Unpublished Identifier
  `BT-195(BT-733)-Lot-List`:: Unpublished Identifier Listname
  `BT-195(BT-733)-LotsGroup`:: Unpublished Identifier
  `BT-195(BT-733)-LotsGroup-List`:: Unpublished Identifier Listname
  `BT-195(BT-734)-Lot`:: Unpublished Identifier
  `BT-195(BT-734)-Lot-List`:: Unpublished Identifier Listname
  `BT-195(BT-734)-LotsGroup`:: Unpublished Identifier
  `BT-195(BT-734)-LotsGroup-List`:: Unpublished Identifier Listname
  `BT-195(BT-759)-LotResult`:: Unpublished Identifier
  `BT-195(BT-759)-LotResult-List`:: Unpublished Identifier Listname
  `BT-195(BT-760)-LotResult`:: Unpublished Identifier
  `BT-195(BT-760)-LotResult-List`:: Unpublished Identifier Listname
  `BT-195(BT-773)-Tender`:: Unpublished Identifier
  `BT-195(BT-773)-Tender-List`:: Unpublished Identifier Listname
  `BT-195(BT-88)-Procedure`:: Unpublished Identifier
  `BT-195(BT-88)-Procedure-List`:: Unpublished Identifier Listname
