= Notice View Templates
ifeval::[{eforms_latest_version} == {eforms_version}]
:page-aliases: latest@index.adoc
endif::[]

To standardise the way a notice can be visualised, independently of the media format used (PDF, HTML etc.), we have decided to create and share with our developer community a set of "view templates".

Every notice subtype can be associated with one or more different view templates. These templates are available in the `view-templates` folder in the eForms SDK. To create these template files, we use the EFX template language.

== How the files are organised
The view templates are available in the `view-template` folder of the SDK. Every template file is named using the notice subtype identifier and has the extension `.efx`.
For this version of the eForms SDK there is only one template available for every notice subtype. An additional template that can be used for any notice subtype is the `summary.efx` template, which as the name implies generates a summarised view of the notice.

== Template language syntax
As the `.efx` file extension implies, the language used to write the template is EFX. 

EFX, short for "eForms expression language", is a domain specific language that we have developed to allow us to easily and unambiguously express the eForms business rules, as well as to enable us to define these view templates. EFX templates provide the structural information necessary to visualise the notice. The template uses EFX expressions to convey content information.

For details on the EFX template language syntax xref:efx:template-syntax.adoc[follow this link].

== How to reuse the templates
If you could take advantage of these view templates to automatically visualise any notice, you would avoid having to recode your hardcoded visualisations every time a new version of eForms is released. Moreover, you could even aim at reusing the same template system for the visualisation of notices tailored for you Member State. So how can that be achieved?

The general idea is that you would need to automatically translate the eForms view templates to the templating system of your choice. Then use the automatically generated templates to visualise any notice.


For details on how to translate the provided EFX templates to the template language of your choice, see xref:efx:transpiling-efx.adoc[Transpiling EFX].


'''
*See also:*

* xref:efx-toolkit:index.adoc[EFX Toolkit for Java]
* xref:notice-viewer:index.adoc[Notice Viewer sample application]
