= Notice View Templates
ifeval::[{eforms_latest_version} == {eforms_version}]
:page-aliases: latest@index.adoc
endif::[]

To standardise the way a notice can be visualised, independently of the media format used (PDF, HTML etc.), we have decided to create and share with our developer community a set of "view templates".

Every notice subtype can be associated with one or more different view templates. These templates are available in the `view-templates` folder in the eForms SDK. To create these template files, we use the EFX template language.

== How the files are organised

The view templates are available in the `view-template` folder of the SDK. Every template file is named using the notice subtype identifier and has the extension `.efx`.
For this version of the eForms SDK there is only one template available for every notice subtype. An additional template that can be used for any notice subtype is the `summary.efx` template, which as the name implies generates a summarised view of the notice.

== Template language syntax

As the file extension implies, the language used inside the template is EFX. 

EFX, short for "eForms expression language", is a domain specific language that we have developed to allow us to easily and unambiguously express the eForms business rules, as well as to enable us to define these view templates. EFX templates provide the structural information necessary to visualise the notice and use EFX expressions to convey content information.

Every template file is organized in `template lines`. Every `template line`, contains two main pieces of information:

* the `context` of the line.
* the `content` that will be displayed in the output generated for the specific line.

Below is en excerpt from the EFX grammar that expresses this:

[source]
----
templateLine: (OutlineNumber | Tabs | Spaces | MixedIndent)? contextDeclarationBlock template CRLF;
----