:xrefstyle: short

[[codelistsAndFieldsSection]]
= Codelists and Fields

This section provides further details on some fields and codelists only. It is not foreseen to
be exhaustive and gives information necessary for clarification.

[[exclusionGroundsCodelistSection]]
== Exclusion grounds codelist

This codelist covers all possible codes for exclusion grounds, it is a tailored codelist built 
from the https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/criterion[criterion] 
codelist.

Some grounds are highly recommended; From the EU legislation perspective, these are mandatory, however derogations are 
possible (cf. <<codelists-and-fields-R1>> – art. 57). To identify precisely which value to use, 
the contracting authority shall also consider local legislation.

[bibliography]
== References

* [[[codelists-and-fields-R1, R1]]] **Directive 2014/24/EU of the European Parliament and of the
Council of 26 February 2014 on public procurement and repealing
Directive 2004/18/EC, Text with EEA relevance, **__Official Journal of
The European Union__, OJ L 94, 28.3.2014, pp. 65 - 242, Available at
http://data.europa.eu/eli/dir/2014/24/oj[http://data.europa.eu/eli/dir/2014/24/oj],
accessed February 11^th^, 2020.
