:xrefstyle: short

= Introduction

[[objectiveAndScopeSection]]
== Objective and scope

The objective of this document is to provide the person in charge of the
XML generation with the information necessary for integration of the
schemas.

There are three schemas foreseen to cover the 40 situations listed in
the eForms Regulation
(https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022R2303[Regulation (EU) 2022/2303]):

* Prior Information Notice (PIN),

* Contract Notice (CN), and

* Contract Award Notice (CAN).

The schemas are based on OASIS UBL v2.3 with some extensions for 
eForms-specific information.

Codelists, validation rules and technical integration are outside the
scope of the present document; although, if there are references to some
Business Rules or codelists in this document, these will not be
discussed in detail.

[[theRegulationSection]]
== The Regulation

A regulation on Public Procurement (eForms) has been drafted, proposed,
adopted, published in October 2019 <<introduction-R1>>, amended and the amended version published in November 2023 <<introduction-R4>>. It replaces the
Implementing Regulation from November 2015 <<introduction-R2>>.

eForms is part of the Single Market Strategy of the European Commission
<<introduction-R3>> and will help collect, manage and analyze procurement related data;
this will populate a meaningful source of information for Member States
to support their initiatives on _Public Procurement Governance_
improvement with amplified efficiency, transparency and integrity.

Some aspects that the regulation is intended to address, are:

* increased information accuracy;

* forms simplification;

* extended flexibility (e.g. ability to nationally: adapt labels
to regional preferences, enforce the use of some optional fields);

* closer consistency (amongst forms and with other documents
based on the same standards),

* intensified flexibility with specifications at Lots level;

* improved governance with identified sellers and buyers, as
well as a limited number of policy related information;

* balanced transparency-competition aspects with justified
private information;

* simplified process for Corrigenda publications;

* use of a procedure identifier for a better Business
Opportunities identification.

[[backgroundInformationSection]]
== Background information

In addition to the regulation, the following have been considered for
the schemas development:

* The published UBL 2.3 schemasfootnote:[Available at https://docs.oasis-open.org/ubl/cs01-UBL-2.3/UBL-2.3.html];

* The detailed spreadsheet corresponding to Annex II of the
eForms regulationfootnote:[Accessible from https://ec.europa.eu/docsroom/documents/52697/attachments/2/translations/en/renditions/native];

* The numerous discussions undertaken during the different
consultationsfootnote:[Accessible at https://github.com/eForms/eForms/issues] with the collected information regularly integrated by DG GROW in the
Annex II;

* The outcome of the eProcurement Ontology workgroup activityfootnote:[More information available at https://github.com/eprocurementontology/eprocurementontology];

* The approaches adopted for other UBL based data (ESPD,
eInvoicing ...).

[[aboutThisDocumentSection]]
== About this document

This document is divided in different sections:

* Sections 1 to 3 with introduction of general concepts, and

* Sections 4 to 7 more technical.

The choice has been made to be as concise as possible using tables and
cross references. Navigation between text and tables, or tables and
sections is possible with a _"Ctrl" + click_ and back navigation with
_"Alt" + "←"_.

Synthetic approach and readability concerns lead to the expression of
some elements usage in a table format. In these tables, the expressed
cardinality does not substitute the one of the Regulation, it is only a
mean to highlight the different occurrences that may be needed for some
elements at specific places for a given document type. As a kind of
synthesis of the requirements for all situations covered by a document
type (i.e. all columns of the Regulation annex that a given schema
intents to cover), the cardinality is more generic and may lack the
precision required by the Regulation and that the validation rules will
verify.

Codelists and validation rules are out of the scope of this document
even if they are referenced sometimes.

Some codelists justified by the technical design of the schemasfootnote:[Also referred to as "technical codelists".]
won't appear on EU Vocabularies, they will however be documented and
provided with the necessary artefacts required for data validation.

To clarify the usage of some elements, some validation rules had to be
stated; these do not however cover the whole set of validation rules
applicable which will be provided at a later stage.

Regarding illustration, samples have been provided using 2 linguistic
versions; this has been done for clarification purpose regarding
encoding of multilingual notices. There is no requirement to have
exactly two such linguistic versions.

[bibliography]
== References


* [[[introduction-R1, R1]]] **Commission Implementing Regulation (EU) 2019/1780 of 23
September 2019 establishing standard forms for the publication of
notices in the field of public procurement and repealing Implementing
Regulation (EU) 2015/1986 (eForms) (Text with EEA relevance)** ,
_Official Journal of The European Union_, OJ L 272, Oct. 25^th^, 2019,
pp. 7 - 73, available at
[.MsoHyperlink]##http://data.europa.eu/eli/reg_impl/2019/1780/oj##,
accessed January 27^th^, 2020.
* [[[introduction-R2, R2]]] **Commission Implementing Regulation (EU) 2015/1986 of 11
November 2015 establishing standard forms for the publication of notices
in the field of public procurement and repealing Implementing Regulation
(EU) No 842/2011**, _Official Journal of The European Union_, OJ L 296,
Nov. 12^th^, 2015, pp. 1 - 146, available at
http://data.europa.eu/eli/reg_impl/2015/1986/oj##,
accessed January 27^th^, 2020
* [[[introduction-R3, R3]]] **Communication From The Commission To The European Parliament,
The Council, The European Economic And Social Committee And The
Committee Of The Regions, Upgrading the Single Market: more
opportunities for people and business**, Oct. 28^th^, 2015, 23 p.,
available at
https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52015DC0550[https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52015DC0550],
accessed January 27^th^, 2020
* [[[introduction-R4, R4]]] **Commission Implementing Regulation 
(EU) 2022/2303 of 24 November 2022 amending Implementing Regulation 
(EU) 2019/1780 establishing standard forms for the publication of 
notices in the field of public procurement (Text with EEA relevance)** ,
_Official Journal of The European Union_, OJ L 305, Nov. 25^th^, 2022, pp. 12 – 50, available at
[.MsoHyperlink]##http://data.europa.eu/eli/reg_impl/2022/2303/oj##,
accessed January 24^th^, 2023.