= eForms Preview environment

== Scope and purpose

The Publications Office (OP) is developing a range of applications to manage the collection, validation, processing, visualisation and dissemination of eForms notices.

OP will progressively make available the relevant applications through a “Preview” environment that will help eSenders to develop and test their own applications.

The applications, URLs and user data are subject to unannounced changes until the applications go live in production in November 2022. 

For the applications with a web user interface (eNotices2 and TED API), users can sign in with an EU Login account from the acceptance environment at https://ecas.acceptance.ec.europa.eu/cas 

The OP applications are: 

* eNotices2 is the reception system for eForms. Notices can be submitted and managed through the web front-end or via API (by eSenders), replacing the current eNotices and eSentool applications. It uses CVS to validate notices before sending them to TED Monitor 2022 for publication.

* CVS is the Central Validation Service for eForms. This API runs all the technical and business validation rules to check that an eForms notice is valid. It is called by eNotices2 when a notice is submitted but it can also be called at any point in a notice’s lifecycle, e.g. by an eSender to check before submission.

* TED Viewer 2022 provides an API that returns an HTML or PDF rendition of an eForms XML notice at any stage of its lifecycle, e.g. before validation or after publication.

* TED API 2022 allows external parties to get a key to call OP APIs and it ensures the authentication of API calls by external parties.

* TED Monitor 2022 is the internal application used by OP to process and prepare the daily export of notices of the Supplement of the Official Journal (OJ S) that is published on TED. It also allows OP to check the lawfulness of certain notices and to mask unpublished fields. This application is not exposed in the Preview environment.

* TED is the public dissemination website for European procurement notices in the OJ S. It is being adapted to handle eForms notices and will be replaced by a new TED 2.0 website in spring 2023. There is no Preview environment for TED.



==  eNotices2

Website: https://enotices2.preview.ted.europa.eu

API endpoint: to come

API documentation: https://enotices2.preview.ted.europa.eu/esenders/swagger-ui/

=== Current status

Release: NRP-A2

SDK: 0.4.2 
 

Please be aware that the interface and the notices content are very much a work in progress in this release.  

At this point, the application is incomplete, many use cases are not implemented totally and others have dependencies in other applications which are only mocked-up. Similarly, the notices content is not complete as it is missing conditional rules, and significant tweaking or corrections of the sections is still to be expected. 

All the labels in the user interface (UI), notices and fields are subject to change – what you see are only placeholders and the UI is only fully available in English. The translated labels will not be available for several more months.  

The application is not integrated with any other TED applications, which means there are some limitations to what it can do. 

* Notices do not go through validation when they are submitted, therefore do not expect any other validation than the live validation rules that you will find within the form-filling tool. 
** Mandatory fields are shown by red asterisks. 
** Live validation fields will have a red highlight until the right pattern is entered.
** Some of the rules for mandatory fields and patterns aren’t fully correct in this version.
** Clicking on the validation button produces an error.

* Submitted notices aren’t published. They will have to go through another workflow in TED Monitor before they can be published, which takes place every working day around 15:00 CET, before you can create a Change notice or continue a procedure. 

* The notices can partially be previewed in either HTML or PDF.

In this version the application is expected to allow users to create the 40 eForms notice types plus the 5 other notice types which include the 2 transport regulation notices, the European economic interest grouping and European company/cooperative registration forms, and the call for expression of interest. The fields which are available, along with their behaviour, are consistent with SDK 0.4. In the codelist fields, prefilling of values is supported. 

The application also allows users to act upon notices and procedures, archiving, renaming and transferring them to other users or other procedures as well as import/ export notices in XML. There is also a search feature which allows users to sort through long lists of procedures. The main nature of the LOT can now be correctly defined.

Users can create workgroups between themselves and test the definitions of roles and permissions within these workgroups. They can also work and submit notices worked upon collectively.

Users can also define personalised settings for the legal basis and notice types that they want to use, as well as default languages in the notice, and tailoring of some fields is available (please note that adding a "default" currency will not allow you to create a Change notice):

* Optional fields can be set to mandatory or hidden.
* Confidential fields can be set to be always confidential or non-confidential. 

The first iteration of the address book has been implemented, which allows users to create a database of addresses of known organisations which regularly take part in the procurement process and import them in their notices. 

eNotices2 uses the codelists from the SDK, which have not been tailored. This means that certain codelists have too many entries, such as countries or languages that no longer exist. 

The eNotices2 API for this release is not yet available for external access. The Swagger UI provides basic documentation of the four functions. The URLs and parameters of the API are likely to change in future releases.

=== Planned 

Release: NRP+1

Indicative planning: August 2022

SDK: 0.6.2

This version of the application is focused on improvements to the UI experience and the correction of bugs.

There are many improvements in the form filling tool including the possibility to filter optional fields and a notable improvement to the usability of CPV and NUTS codelists.

The address book usage has been improved and the notion of main buyer allows users to set up their own “contracting body” to be always present, except within the workgroups.

Users can see an improved mock-up of the CVS.

In the notice sections a search feature has been added and pagination for up to 2000 lots is supported.



== CVS 

API endpoint: https://cvs.preview.ted.europa.eu/v1/notices/validation

API documentation: https://cvs.preview.ted.europa.eu/swagger-ui/

=== Current status 

Release: 1.1.0 (Phase 3)

SDK: 0.4.2 and 0.6.2

Complete implementation, including the execution of the validation rules (Schematron).

We are working on resolving the following limitations and known issues:

* As indicated above, notices can currently only be validated with the rules from SDK 0.4 and 0.6.
* Large notices (750 KB or above) cannot be sent, due to a technical restriction.


== TED Viewer 2022 

API endpoint: to come 

API documentation: Swagger UI to come 

=== Current status 

Release: Phase 2 

SDK: 0.4.1 and 0.5.0 

Partial rendering of HTML and PDF. 

=== Planned 

Release: Phase 3 

Indicative planning: August 2022 

SDK: 0.4.1, 0.5.0 and 0.6.0 

Final version of the applications with full rendering of HTML and PDF and using the view-templates defined in the SDK.



== TED API (Developer Portal)

Website: https://developer.preview.ted.europa.eu/home 

Documentation: a dedicated section of docs.ted.europa.eu will document all APIs. 

=== Current status 

Final release. Users can generate and revoke an API key. Used by the other systems in Preview environment to authenticate API calls. 



== TED Monitor 2022 

This application is not public but this information provides some background about progress and how the applications are integrated. 

=== Current status 

Release: Phase 2 

SDK: 0.4.1 

This release implements the core functions for checking notices that require lawfulness authorisation, masking unpublished fields and generating the daily export files for TED. The checks on lawfulness validation are not yet fully implemented. They will be finalised with Phase 4.

=== Planned 

Release: Phase 3 

SDK: 0.4.1 and 0.5.0 

Indicative planning: July 2022 

The release will include display results page, homepage overview (Follow-up notices), advanced search, notice information. 



== TED website 

The test environment of the TED application is not public but this information can provide some background about progress and how the applications are integrated. 

=== Current status 

Release: Phase 2 

Store and index eForms notices. 

=== Planned 

Release: Phase 3 

Indicative planning: August 2022 

Final release.

