=== `buyer-categories`
List of codes used to characterize the buyers for the subsequent contracts of a given Framework Agreement. 
[horizontal]
Version:: 1.0

See xref:code-lists/buyer-categories.adoc[details & codes]

'''

=== `buyer-contracting-type`
List of codes to specify whether a Buyer is a Contracting Entity or not.
[horizontal]
Version:: 1.0

See xref:code-lists/buyer-contracting-type.adoc[details & codes]

'''

=== `classification-type`
List of commodity classifications
[horizontal]
Version:: 1.0

See xref:code-lists/classification-type.adoc[details & codes]

'''

=== `conditions`
Codes for conditions
[horizontal]
Version:: 1.0

See xref:code-lists/conditions.adoc[details & codes]

'''

=== `contract-detail`
This table provides a framework to represent data relating to procurement.
[horizontal]
Version:: 1.0

See xref:code-lists/contract-detail.adoc[details & codes]

'''

=== `customer-service`
This table provides a list of customer services.
[horizontal]
Version:: 1.0

See xref:code-lists/customer-service.adoc[details & codes]

'''

=== `document-distribution`
List of codes to specify whether the document distribution is restricted or not.
[horizontal]
Version:: 1.0

See xref:code-lists/document-distribution.adoc[details & codes]

'''

=== `document-status`
List of codes to specify whether a document has or not a legal status.
[horizontal]
Tailored by:: <<_linguistic_status,`linguistic-status`>>
Version:: 1.0

See xref:code-lists/document-status.adoc[details & codes]

'''

=== `eforms-currency`
List of currency codes allowed in eforms
[horizontal]
Subset of:: <<_currency,`currency`>>
Version:: 20230315-0

See xref:code-lists/eforms-currency.adoc[details & codes]

'''

=== `eu-funded`
List of codes to specify whether a procurement would be financed using EU funds.
[horizontal]
Version:: 1.0

See xref:code-lists/eu-funded.adoc[details & codes]

'''

=== `exclusion-ground`
List of codes for Exclusion Ground identification
[horizontal]
Subset of:: <<_criterion,`criterion`>>
Version:: 20230315-0

See xref:code-lists/exclusion-ground.adoc[details & codes]

'''

=== `gpp-criteria`
Green Public Procurement Criteria
[horizontal]
Version:: 1.0

See xref:code-lists/gpp-criteria.adoc[details & codes]

'''

=== `indicator`
List of eforms allowed indicator values
[horizontal]
Tailored by:: <<_accelerated_procedure,`accelerated-procedure`>>, <<_cvd_scope,`cvd-scope`>>, <<_esignature_submission,`esignature-submission`>>, <<_nda,`nda`>>, <<_required,`required`>>, <<_subcontracting_allowed,`subcontracting-allowed`>>, <<_tender_guarantee_required,`tender-guarantee-required`>>
Version:: 1.0

See xref:code-lists/indicator.adoc[details & codes]

'''

=== `lawful-country`
List of countries for which there is a legal basis for publication in the Supplement to the Official Journal of the European Union
[horizontal]
Subset of:: <<_country,`country`>>

See xref:code-lists/lawful-country.adoc[details & codes]

'''

=== `non-publication-identifier`
List of codes for the identification of the information whose publication shall be delayed.
[horizontal]
Version:: 1.0

See xref:code-lists/non-publication-identifier.adoc[details & codes]

'''

=== `notice-purpose`
List of codes to specify the purpose of the Business Register Information Notice
[horizontal]
Version:: 1.0

See xref:code-lists/notice-purpose.adoc[details & codes]

'''

=== `notice-subtype`
List of possible Notice Subtype codes for a Notice of type Business Registration Information Notice.
[horizontal]
Tailored by:: <<_brin_ecs,`brin-ecs`>>, <<_brin_eeig,`brin-eeig`>>, <<_can_desg,`can-desg`>>, <<_can_modif,`can-modif`>>, <<_can_social,`can-social`>>, <<_can_standard,`can-standard`>>, <<_can_tran,`can-tran`>>, <<_cn_desg,`cn-desg`>>, <<_cn_social,`cn-social`>>, <<_cn_standard,`cn-standard`>>, <<_corr,`corr`>>, <<_pin_buyer,`pin-buyer`>>, <<_pin_cfc_social,`pin-cfc-social`>>, <<_pin_cfc_standard,`pin-cfc-standard`>>, <<_pin_only,`pin-only`>>, <<_pin_rtl,`pin-rtl`>>, <<_pin_tran,`pin-tran`>>, <<_qu_sy,`qu-sy`>>, <<_subco,`subco`>>, <<_veat,`veat`>>
Version:: 1.0

See xref:code-lists/notice-subtype.adoc[details & codes]

'''

=== `nuts-alb-lvl3`
List of level 3 NUTS codes for Albania
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-alb-lvl3.adoc[details & codes]

'''

=== `nuts-aut-lvl3`
List of level 3 NUTS codes for Austria
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-aut-lvl3.adoc[details & codes]

'''

=== `nuts-bel-lvl3`
List of level 3 NUTS codes for Belgium
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-bel-lvl3.adoc[details & codes]

'''

=== `nuts-bgr-lvl3`
List of level 3 NUTS codes for Bulgaria
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-bgr-lvl3.adoc[details & codes]

'''

=== `nuts-che-lvl3`
List of level 3 NUTS codes for Switzerland
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-che-lvl3.adoc[details & codes]

'''

=== `nuts-cyp-lvl3`
List of level 3 NUTS codes for Cyprus
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-cyp-lvl3.adoc[details & codes]

'''

=== `nuts-cze-lvl3`
List of level 3 NUTS codes for Czech Republic
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-cze-lvl3.adoc[details & codes]

'''

=== `nuts-deu-lvl3`
List of level 3 NUTS codes for Germany
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-deu-lvl3.adoc[details & codes]

'''

=== `nuts-dnk-lvl3`
List of level 3 NUTS codes for Denmark
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-dnk-lvl3.adoc[details & codes]

'''

=== `nuts-esp-lvl3`
List of level 3 NUTS codes for Spain
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-esp-lvl3.adoc[details & codes]

'''

=== `nuts-est-lvl3`
List of level 3 NUTS codes for Estonia
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-est-lvl3.adoc[details & codes]

'''

=== `nuts-fin-lvl3`
List of level 3 NUTS codes for Finland
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-fin-lvl3.adoc[details & codes]

'''

=== `nuts-fra-lvl3`
List of level 3 NUTS codes for France
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-fra-lvl3.adoc[details & codes]

'''

=== `nuts-gbr-lvl3`
List of level 3 NUTS codes for United Kingdom
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-gbr-lvl3.adoc[details & codes]

'''

=== `nuts-grc-lvl3`
List of level 3 NUTS codes for Greece
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-grc-lvl3.adoc[details & codes]

'''

=== `nuts-hrv-lvl3`
List of level 3 NUTS codes for Croatia
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-hrv-lvl3.adoc[details & codes]

'''

=== `nuts-hun-lvl3`
List of level 3 NUTS codes for Hungary
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-hun-lvl3.adoc[details & codes]

'''

=== `nuts-irl-lvl3`
List of level 3 NUTS codes for Ireland
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-irl-lvl3.adoc[details & codes]

'''

=== `nuts-isl-lvl3`
List of level 3 NUTS codes for Iceland
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-isl-lvl3.adoc[details & codes]

'''

=== `nuts-ita-lvl3`
List of level 3 NUTS codes for Italy
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-ita-lvl3.adoc[details & codes]

'''

=== `nuts-lie-lvl3`
List of level 3 NUTS codes for Lichtenstein
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-lie-lvl3.adoc[details & codes]

'''

=== `nuts-ltu-lvl3`
List of level 3 NUTS codes for Lithuania
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-ltu-lvl3.adoc[details & codes]

'''

=== `nuts-lux-lvl3`
List of level 3 NUTS codes for Luxembourg
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-lux-lvl3.adoc[details & codes]

'''

=== `nuts-lva-lvl3`
List of level 3 NUTS codes for Latvia
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-lva-lvl3.adoc[details & codes]

'''

=== `nuts-lvl3`
List of all level 3 NUTS codes
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-lvl3.adoc[details & codes]

'''

=== `nuts-mkd-lvl3`
List of level 3 NUTS codes for Former Yugoslav Republic of Macedonia
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-mkd-lvl3.adoc[details & codes]

'''

=== `nuts-mlt-lvl3`
List of level 3 NUTS codes for Malta
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-mlt-lvl3.adoc[details & codes]

'''

=== `nuts-mne-lvl3`
List of level 3 NUTS codes for Montenegro
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-mne-lvl3.adoc[details & codes]

'''

=== `nuts-nld-lvl3`
List of level 3 NUTS codes for Netherlands
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-nld-lvl3.adoc[details & codes]

'''

=== `nuts-nor-lvl3`
List of level 3 NUTS codes for Norway
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-nor-lvl3.adoc[details & codes]

'''

=== `nuts-pol-lvl3`
List of level 3 NUTS codes for Poland
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-pol-lvl3.adoc[details & codes]

'''

=== `nuts-prt-lvl3`
List of level 3 NUTS codes for Portugal
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-prt-lvl3.adoc[details & codes]

'''

=== `nuts-rou-lvl3`
List of level 3 NUTS codes for Romania
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-rou-lvl3.adoc[details & codes]

'''

=== `nuts-srb-lvl3`
List of level 3 NUTS codes for Serbia
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-srb-lvl3.adoc[details & codes]

'''

=== `nuts-svk-lvl3`
List of level 3 NUTS codes for Slovakia
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-svk-lvl3.adoc[details & codes]

'''

=== `nuts-svn-lvl3`
List of level 3 NUTS codes for Slovenia
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-svn-lvl3.adoc[details & codes]

'''

=== `nuts-swe-lvl3`
List of level 3 NUTS codes for Sweden
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-swe-lvl3.adoc[details & codes]

'''

=== `nuts-tur-lvl3`
List of level 3 NUTS codes for Turkey
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-tur-lvl3.adoc[details & codes]

'''

=== `period-listname`
-/-
[horizontal]
Version:: 1.0

See xref:code-lists/period-listname.adoc[details & codes]

'''

=== `review-status`
List of codes for the status of a given review request.
[horizontal]
Version:: 1.0

See xref:code-lists/review-status.adoc[details & codes]

'''

=== `review-type`
List of codes for the identification of the type of review requester
[horizontal]
Version:: 1.0

See xref:code-lists/review-type.adoc[details & codes]

'''

=== `rewards-penalties`
List of codes for rewards and penalties associated to a Public Transportation Service.
[horizontal]
Version:: 1.0

See xref:code-lists/rewards-penalties.adoc[details & codes]

'''

=== `tenderlot-presentation`
List of codes to specify whether the submission should deal with all the defined lots.
[horizontal]
Version:: 1.0

See xref:code-lists/tenderlot-presentation.adoc[details & codes]

'''

=== `transport-service`
This table provides a list of transport services.
[horizontal]
Version:: 1.0

See xref:code-lists/transport-service.adoc[details & codes]

'''

=== `vehicles`
List of codes for vehicle categories.
[horizontal]
Version:: 1.0

See xref:code-lists/vehicles.adoc[details & codes]

'''

