=== `accelerated-procedure`
List of codes to specify whether a procedure is accelerated or not.
[horizontal]
Subset of:: <<_indicator,`indicator`>>
Version:: 1.0

See xref:code-lists/accelerated-procedure.adoc[details & codes]

'''

=== `authority-activity`
List of Main Activity codes allowed for a Contracting Authority
[horizontal]
Subset of:: <<_main_activity,`main-activity`>>
Version:: 20220316-0

See xref:code-lists/authority-activity.adoc[details & codes]

'''

=== `bri`
List of allowed Notice Type codes for a Business Register Information document
[horizontal]
Subset of:: <<_notice_type,`notice-type`>>
Version:: 20210929-0

See xref:code-lists/bri.adoc[details & codes]

'''

=== `brin-ecs`
List of allowed Notice Subtype codes for a notice concerning a European Company or a European Cooperative Society registration processing.
[horizontal]
Subset of:: <<_notice_subtype,`notice-subtype`>>
Version:: 1.0

See xref:code-lists/brin-ecs.adoc[details & codes]

'''

=== `brin-eeig`
List of allowed Notice Subtype codes for a notice concerning a European Economic Interest Grouping registration processing.
[horizontal]
Subset of:: <<_notice_subtype,`notice-subtype`>>
Version:: 1.0

See xref:code-lists/brin-eeig.adoc[details & codes]

'''

=== `buyer-categories`
List of codes used to characterize the buyers for the subsequent contracts of a given Framework Agreement. 
[horizontal]
Version:: 1.0

See xref:code-lists/buyer-categories.adoc[details & codes]

'''

=== `buyer-contracting-type`
List of codes to specify whether a Buyer is a Contracting Entity or not.
[horizontal]
Version:: 1.0

See xref:code-lists/buyer-contracting-type.adoc[details & codes]

'''

=== `can-desg`
List of allowed Notice Subtype codes for a notice of CAN Design Notice Type.
[horizontal]
Subset of:: <<_notice_subtype,`notice-subtype`>>
Version:: 1.0

See xref:code-lists/can-desg.adoc[details & codes]

'''

=== `can-modif`
List of allowed Notice Subtype codes for a notice of Contract Modification Notice Type .
[horizontal]
Subset of:: <<_notice_subtype,`notice-subtype`>>
Version:: 1.0

See xref:code-lists/can-modif.adoc[details & codes]

'''

=== `can-social`
List of allowed Notice Subtype codes for a notice of CAN Social Notice Type .
[horizontal]
Subset of:: <<_notice_subtype,`notice-subtype`>>
Version:: 1.0

See xref:code-lists/can-social.adoc[details & codes]

'''

=== `can-standard`
List of allowed Notice Subtype codes for a notice of CAN Standard Notice Type .
[horizontal]
Subset of:: <<_notice_subtype,`notice-subtype`>>
Version:: 1.0

See xref:code-lists/can-standard.adoc[details & codes]

'''

=== `can-tran`
List of allowed Notice Subtype codes for a notice of CAN Public Transport Service Notice Type .
[horizontal]
Subset of:: <<_notice_subtype,`notice-subtype`>>
Version:: 1.0

See xref:code-lists/can-tran.adoc[details & codes]

'''

=== `classification-type`
List of commodity classifications
[horizontal]
Version:: 1.0

See xref:code-lists/classification-type.adoc[details & codes]

'''

=== `cn-desg`
List of allowed Notice Subtype codes for a notice of CN Design Notice Type.
[horizontal]
Subset of:: <<_notice_subtype,`notice-subtype`>>
Version:: 1.0

See xref:code-lists/cn-desg.adoc[details & codes]

'''

=== `cn-social`
List of allowed Notice Subtype codes for a notice of CN Social Notice Type.
[horizontal]
Subset of:: <<_notice_subtype,`notice-subtype`>>
Version:: 1.0

See xref:code-lists/cn-social.adoc[details & codes]

'''

=== `cn-standard`
List of allowed Notice Subtype codes for a notice of CN Standard Design Notice Type.
[horizontal]
Subset of:: <<_notice_subtype,`notice-subtype`>>
Version:: 1.0

See xref:code-lists/cn-standard.adoc[details & codes]

'''

=== `competition`
List of allowed Notice Type codes for a notice of Competition Form Type
[horizontal]
Subset of:: <<_notice_type,`notice-type`>>
Version:: 20210929-0

See xref:code-lists/competition.adoc[details & codes]

'''

=== `conditions`
Codes for conditions
[horizontal]
Version:: 1.0

See xref:code-lists/conditions.adoc[details & codes]

'''

=== `cont-modif`
List of allowed Notice Type codes for a notice of Contract Modification Form Type
[horizontal]
Subset of:: <<_notice_type,`notice-type`>>
Version:: 20210929-0

See xref:code-lists/cont-modif.adoc[details & codes]

'''

=== `contract-term`
TODO
[horizontal]
Subset of:: <<_contract_detail,`contract-detail`>>
Version:: 20220316-0

See xref:code-lists/contract-term.adoc[details & codes]

'''

=== `customer-service`
This table provides a list of customer services.
[horizontal]
Version:: 1.0

See xref:code-lists/customer-service.adoc[details & codes]

'''

=== `cvd-scope`
List of codes to specify whether the procurement falls within the scope of the European Parliament and Council 2009/33/EC (Clean Vehicles Directive – CVD).
[horizontal]
Subset of:: <<_indicator,`indicator`>>
Version:: 1.0

See xref:code-lists/cvd-scope.adoc[details & codes]

'''

=== `dir-awa-pre`
List of allowed Notice Type codes for a Direct Award Preannouncement Form Type
[horizontal]
Subset of:: <<_notice_type,`notice-type`>>
Version:: 20210929-0

See xref:code-lists/dir-awa-pre.adoc[details & codes]

'''

=== `document-distribution`
List of codes to specify whether the document distribution is restricted or not.
[horizontal]
Version:: 1.0

See xref:code-lists/document-distribution.adoc[details & codes]

'''

=== `document-status`
List of codes to specify whether a document has or not a legal status.
[horizontal]
Tailored by:: <<_linguistic_status,`linguistic-status`>>
Version:: 1.0

See xref:code-lists/document-status.adoc[details & codes]

'''

=== `duration`
List of codes for undefined duration
[horizontal]
Subset of:: <<_timeperiod,`timeperiod`>>
Version:: 20190918-0

See xref:code-lists/duration.adoc[details & codes]

'''

=== `duration-unit`
List of codes for eforms allowed duration unit of measure
[horizontal]
Subset of:: <<_timeperiod,`timeperiod`>>
Version:: 20190918-0

See xref:code-lists/duration-unit.adoc[details & codes]

'''

=== `ecatalog-submission`
List of codes to specify whether the submission of electronic catalogues is allowed or not.
[horizontal]
Subset of:: <<_permission,`permission`>>
Version:: 20220316-0

See xref:code-lists/ecatalog-submission.adoc[details & codes]

'''

=== `eea-country`
List of codes of the European Economic Area countries
[horizontal]
Subset of:: <<_country,`country`>>
Version:: 20230915-0

See xref:code-lists/eea-country.adoc[details & codes]

'''

=== `eforms-buyer-legal-type`
List of buyer-legal-type codes allowed in eforms
[horizontal]
Subset of:: <<_buyer_legal_type,`buyer-legal-type`>>
Version:: 20220615-0

See xref:code-lists/eforms-buyer-legal-type.adoc[details & codes]

'''

=== `eforms-contract-nature`
List of eforms allowed codes to specify the main and additional natures of a purchase
[horizontal]
Subset of:: <<_contract_nature,`contract-nature`>>
Version:: 20210317-0

See xref:code-lists/eforms-contract-nature.adoc[details & codes]

'''

=== `eforms-country`
List of country codes allowed in eforms
[horizontal]
Subset of:: <<_country,`country`>>
Version:: 20230915-0

See xref:code-lists/eforms-country.adoc[details & codes]

'''

=== `eforms-currency`
List of currency codes allowed in eforms
[horizontal]
Subset of:: <<_currency,`currency`>>
Version:: 20230315-0

See xref:code-lists/eforms-currency.adoc[details & codes]

'''

=== `eforms-language`
List of language codes allowed in eforms
[horizontal]
Subset of:: <<_language,`language`>>
Version:: 20220928-0

See xref:code-lists/eforms-language.adoc[details & codes]

'''

=== `eu-country`
List of codes of the EU countries
[horizontal]
Subset of:: <<_country,`country`>>
Version:: 20230915-0

See xref:code-lists/eu-country.adoc[details & codes]

'''

=== `eu-funded`
List of codes to specify whether a procurement would be financed using EU funds.
[horizontal]
Version:: 1.0

See xref:code-lists/eu-funded.adoc[details & codes]

'''

=== `eu-official-language`
List of codes of the EU official languages
[horizontal]
Subset of:: <<_language,`language`>>
Version:: 20220928-0

See xref:code-lists/eu-official-language.adoc[details & codes]

'''

=== `exclusion-ground`
List of codes for Exclusion Ground identification
[horizontal]
Subset of:: <<_criterion,`criterion`>>
Version:: 20230315-0

See xref:code-lists/exclusion-ground.adoc[details & codes]

'''

=== `gpp-criteria`
Green Public Procurement Criteria
[horizontal]
Version:: 1.0

See xref:code-lists/gpp-criteria.adoc[details & codes]

'''

=== `indicator`
List of eforms allowed indicator values
[horizontal]
Tailored by:: <<_accelerated_procedure,`accelerated-procedure`>>, <<_cvd_scope,`cvd-scope`>>, <<_esignature_submission,`esignature-submission`>>, <<_nda,`nda`>>, <<_required,`required`>>, <<_subcontracting_allowed,`subcontracting-allowed`>>, <<_tender_guarantee_required,`tender-guarantee-required`>>
Version:: 1.0

See xref:code-lists/indicator.adoc[details & codes]

'''

=== `lawful-country`
List of countries for which there is a legal basis for publication in the Supplement to the Official Journal of the European Union
[horizontal]
Subset of:: <<_country,`country`>>
Version:: 20230915-0

See xref:code-lists/lawful-country.adoc[details & codes]

'''

=== `non-publication-identifier`
List of codes for the identification of the information whose publication shall be delayed.
[horizontal]
Version:: 1.0

See xref:code-lists/non-publication-identifier.adoc[details & codes]

'''

=== `notice-purpose`
List of codes to specify the purpose of the Business Register Information Notice
[horizontal]
Version:: 1.0

See xref:code-lists/notice-purpose.adoc[details & codes]

'''

=== `notice-reference`
Notice reference type
[horizontal]
Version:: 1.0

See xref:code-lists/notice-reference.adoc[details & codes]

'''

=== `notice-subtype`
List of possible Notice Subtype codes for a Notice of type Business Registration Information Notice.
[horizontal]
Tailored by:: <<_brin_ecs,`brin-ecs`>>, <<_brin_eeig,`brin-eeig`>>, <<_can_desg,`can-desg`>>, <<_can_modif,`can-modif`>>, <<_can_social,`can-social`>>, <<_can_standard,`can-standard`>>, <<_can_tran,`can-tran`>>, <<_cn_desg,`cn-desg`>>, <<_cn_social,`cn-social`>>, <<_cn_standard,`cn-standard`>>, <<_pin_buyer,`pin-buyer`>>, <<_pin_cfc_social,`pin-cfc-social`>>, <<_pin_cfc_standard,`pin-cfc-standard`>>, <<_pin_only,`pin-only`>>, <<_pin_rtl,`pin-rtl`>>, <<_pin_tran,`pin-tran`>>, <<_qu_sy,`qu-sy`>>, <<_subco,`subco`>>, <<_veat,`veat`>>
Version:: 1.0

See xref:code-lists/notice-subtype.adoc[details & codes]

'''

=== `nuts-alb-lvl3`
List of level 3 NUTS codes for Albania
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-alb-lvl3.adoc[details & codes]

'''

=== `nuts-aut-lvl3`
List of level 3 NUTS codes for Austria
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-aut-lvl3.adoc[details & codes]

'''

=== `nuts-bel-lvl3`
List of level 3 NUTS codes for Belgium
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-bel-lvl3.adoc[details & codes]

'''

=== `nuts-bgr-lvl3`
List of level 3 NUTS codes for Bulgaria
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-bgr-lvl3.adoc[details & codes]

'''

=== `nuts-che-lvl3`
List of level 3 NUTS codes for Switzerland
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-che-lvl3.adoc[details & codes]

'''

=== `nuts-country`
List of codes for Countries having NUTS codes
[horizontal]
Subset of:: <<_country,`country`>>
Version:: 20230915-0

See xref:code-lists/nuts-country.adoc[details & codes]

'''

=== `nuts-cyp-lvl3`
List of level 3 NUTS codes for Cyprus
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-cyp-lvl3.adoc[details & codes]

'''

=== `nuts-cze-lvl3`
List of level 3 NUTS codes for Czech Republic
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-cze-lvl3.adoc[details & codes]

'''

=== `nuts-deu-lvl3`
List of level 3 NUTS codes for Germany
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-deu-lvl3.adoc[details & codes]

'''

=== `nuts-dnk-lvl3`
List of level 3 NUTS codes for Denmark
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-dnk-lvl3.adoc[details & codes]

'''

=== `nuts-esp-lvl3`
List of level 3 NUTS codes for Spain
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-esp-lvl3.adoc[details & codes]

'''

=== `nuts-est-lvl3`
List of level 3 NUTS codes for Estonia
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-est-lvl3.adoc[details & codes]

'''

=== `nuts-fin-lvl3`
List of level 3 NUTS codes for Finland
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-fin-lvl3.adoc[details & codes]

'''

=== `nuts-fra-lvl3`
List of level 3 NUTS codes for France
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-fra-lvl3.adoc[details & codes]

'''

=== `nuts-gbr-lvl3`
List of level 3 NUTS codes for United Kingdom
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-gbr-lvl3.adoc[details & codes]

'''

=== `nuts-grc-lvl3`
List of level 3 NUTS codes for Greece
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-grc-lvl3.adoc[details & codes]

'''

=== `nuts-hrv-lvl3`
List of level 3 NUTS codes for Croatia
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-hrv-lvl3.adoc[details & codes]

'''

=== `nuts-hun-lvl3`
List of level 3 NUTS codes for Hungary
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-hun-lvl3.adoc[details & codes]

'''

=== `nuts-irl-lvl3`
List of level 3 NUTS codes for Ireland
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-irl-lvl3.adoc[details & codes]

'''

=== `nuts-isl-lvl3`
List of level 3 NUTS codes for Iceland
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-isl-lvl3.adoc[details & codes]

'''

=== `nuts-ita-lvl3`
List of level 3 NUTS codes for Italy
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-ita-lvl3.adoc[details & codes]

'''

=== `nuts-lie-lvl3`
List of level 3 NUTS codes for Lichtenstein
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-lie-lvl3.adoc[details & codes]

'''

=== `nuts-ltu-lvl3`
List of level 3 NUTS codes for Lithuania
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-ltu-lvl3.adoc[details & codes]

'''

=== `nuts-lux-lvl3`
List of level 3 NUTS codes for Luxembourg
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-lux-lvl3.adoc[details & codes]

'''

=== `nuts-lva-lvl3`
List of level 3 NUTS codes for Latvia
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-lva-lvl3.adoc[details & codes]

'''

=== `nuts-lvl3`
List of all level 3 NUTS codes
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-lvl3.adoc[details & codes]

'''

=== `nuts-mkd-lvl3`
List of level 3 NUTS codes for Former Yugoslav Republic of Macedonia
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-mkd-lvl3.adoc[details & codes]

'''

=== `nuts-mlt-lvl3`
List of level 3 NUTS codes for Malta
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-mlt-lvl3.adoc[details & codes]

'''

=== `nuts-mne-lvl3`
List of level 3 NUTS codes for Montenegro
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-mne-lvl3.adoc[details & codes]

'''

=== `nuts-nld-lvl3`
List of level 3 NUTS codes for Netherlands
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-nld-lvl3.adoc[details & codes]

'''

=== `nuts-nor-lvl3`
List of level 3 NUTS codes for Norway
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-nor-lvl3.adoc[details & codes]

'''

=== `nuts-pol-lvl3`
List of level 3 NUTS codes for Poland
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-pol-lvl3.adoc[details & codes]

'''

=== `nuts-prt-lvl3`
List of level 3 NUTS codes for Portugal
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-prt-lvl3.adoc[details & codes]

'''

=== `nuts-rou-lvl3`
List of level 3 NUTS codes for Romania
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-rou-lvl3.adoc[details & codes]

'''

=== `nuts-srb-lvl3`
List of level 3 NUTS codes for Serbia
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-srb-lvl3.adoc[details & codes]

'''

=== `nuts-svk-lvl3`
List of level 3 NUTS codes for Slovakia
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-svk-lvl3.adoc[details & codes]

'''

=== `nuts-svn-lvl3`
List of level 3 NUTS codes for Slovenia
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-svn-lvl3.adoc[details & codes]

'''

=== `nuts-swe-lvl3`
List of level 3 NUTS codes for Sweden
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-swe-lvl3.adoc[details & codes]

'''

=== `nuts-tur-lvl3`
List of level 3 NUTS codes for Turkey
[horizontal]
Subset of:: <<_nuts,`nuts`>>
Version:: 1.7.0

See xref:code-lists/nuts-tur-lvl3.adoc[details & codes]

'''

=== `period-listname`
-/-
[horizontal]
Version:: 1.0

See xref:code-lists/period-listname.adoc[details & codes]

'''

=== `player-type`
Type of role/subrole player
[horizontal]
Version:: 1.0

See xref:code-lists/player-type.adoc[details & codes]

'''

=== `postcode-country`
List of country codes for countries having postcodes and requiring their use
[horizontal]
Subset of:: <<_country,`country`>>
Version:: 20230915-0

See xref:code-lists/postcode-country.adoc[details & codes]

'''

=== `procedure-type-10`
Allowed procedure type for notice subtype 10
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-10.adoc[details & codes]

'''

=== `procedure-type-11`
Allowed procedure type for notice subtype 11
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-11.adoc[details & codes]

'''

=== `procedure-type-12`
Allowed procedure type for notice subtype 12
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-12.adoc[details & codes]

'''

=== `procedure-type-13`
Allowed procedure type for notice subtype 13
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-13.adoc[details & codes]

'''

=== `procedure-type-16`
Allowed procedure type for notice subtype 16
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-16.adoc[details & codes]

'''

=== `procedure-type-17`
Allowed procedure type for notice subtype 17
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-17.adoc[details & codes]

'''

=== `procedure-type-18`
Allowed procedure type for notice subtype 18
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-18.adoc[details & codes]

'''

=== `procedure-type-20`
Allowed procedure type for notice subtype 20
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-20.adoc[details & codes]

'''

=== `procedure-type-21`
Allowed procedure type for notice subtype 21
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-21.adoc[details & codes]

'''

=== `procedure-type-23`
Allowed procedure type for notice subtype 23
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-23.adoc[details & codes]

'''

=== `procedure-type-24`
Allowed procedure type for notice subtype 24
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-24.adoc[details & codes]

'''

=== `procedure-type-25`
Allowed procedure type for notice subtype 25
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-25.adoc[details & codes]

'''

=== `procedure-type-26`
Allowed procedure type for notice subtype 26
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-26.adoc[details & codes]

'''

=== `procedure-type-27`
Allowed procedure type for notice subtype 27
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-27.adoc[details & codes]

'''

=== `procedure-type-28`
Allowed procedure type for notice subtype 28
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-28.adoc[details & codes]

'''

=== `procedure-type-29`
Allowed procedure type for notice subtype 29
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-29.adoc[details & codes]

'''

=== `procedure-type-30`
Allowed procedure type for notice subtype 30
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-30.adoc[details & codes]

'''

=== `procedure-type-31`
Allowed procedure type for notice subtype 31
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-31.adoc[details & codes]

'''

=== `procedure-type-33`
Allowed procedure type for notice subtype 33
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-33.adoc[details & codes]

'''

=== `procedure-type-34`
Allowed procedure type for notice subtype 34
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-34.adoc[details & codes]

'''

=== `procedure-type-36`
Allowed procedure type for notice subtype 36
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-36.adoc[details & codes]

'''

=== `procedure-type-37`
Allowed procedure type for notice subtype 37
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-37.adoc[details & codes]

'''

=== `procedure-type-7`
Allowed procedure type for notice subtype 7
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-7.adoc[details & codes]

'''

=== `procedure-type-8`
Allowed procedure type for notice subtype 8
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-8.adoc[details & codes]

'''

=== `procedure-type-9`
Allowed procedure type for notice subtype 9
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-9.adoc[details & codes]

'''

=== `procedure-type-e1`
Allowed procedure type for notice subtype E1
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-e1.adoc[details & codes]

'''

=== `procedure-type-e2`
Allowed procedure type for notice subtype E2
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-e2.adoc[details & codes]

'''

=== `procedure-type-e3`
Allowed procedure type for notice subtype E3
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-e3.adoc[details & codes]

'''

=== `procedure-type-e4`
Allowed procedure type for notice subtype E4
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-e4.adoc[details & codes]

'''

=== `procedure-type-e5`
Allowed procedure type for notice subtype E5
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-e5.adoc[details & codes]

'''

=== `procedure-type-t01`
Allowed procedure type for notice subtype T01
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-t01.adoc[details & codes]

'''

=== `procedure-type-t02`
Allowed procedure type for notice subtype T02
[horizontal]
Subset of:: <<_procurement_procedure_type,`procurement-procedure-type`>>
Version:: 20220928-0

See xref:code-lists/procedure-type-t02.adoc[details & codes]

'''

=== `revenue-allocation`
Revenue allocation
[horizontal]
Subset of:: <<_contract_detail,`contract-detail`>>
Version:: 20230927-0

See xref:code-lists/revenue-allocation.adoc[details & codes]

'''

=== `review-status`
List of codes for the status of a given review request.
[horizontal]
Version:: 1.0

See xref:code-lists/review-status.adoc[details & codes]

'''

=== `review-type`
List of codes for the identification of the type of review requester
[horizontal]
Version:: 1.0

See xref:code-lists/review-type.adoc[details & codes]

'''

=== `rewards-penalties`
List of codes for rewards and penalties associated to a Public Transportation Service.
[horizontal]
Version:: 1.0

See xref:code-lists/rewards-penalties.adoc[details & codes]

'''

=== `tendered-object`
Object type covered by the tender (lot, group of lots)
[horizontal]
Version:: 1.0

See xref:code-lists/tendered-object.adoc[details & codes]

'''

=== `tenderlot-presentation`
List of codes to specify whether the submission should deal with all the defined lots.
[horizontal]
Version:: 1.0

See xref:code-lists/tenderlot-presentation.adoc[details & codes]

'''

=== `transport-service`
This table provides a list of transport services.
[horizontal]
Version:: 1.0

See xref:code-lists/transport-service.adoc[details & codes]

'''

=== `vehicles`
List of codes for vehicle categories.
[horizontal]
Version:: 1.0

See xref:code-lists/vehicles.adoc[details & codes]

'''

