= eForms FAQ
:page-aliases: home:FAQ:eforms.adoc

== General overview of eForms 
[qanda]
 

Is there a general presentation of eForms available?:: 

The policy background of eForms is available on the link:https://ec.europa.eu/growth/single-market/public-procurement/digital/eforms_en[DG GROW website].
+
The link:https://op.europa.eu/en/web/ted-esenders-webinar-2021[2021 eSenders seminar] provided an updated overview of eForms implementation.
+ 
The link:https://op.europa.eu/en/web/ted-esenders-workshop-2022/[May 2022 eForms Technical Workshop] focused on eForms technical implementation for developers 
and on building metadata-driven applications.
+
A follow-up eForms Technical Workshop is scheduled to take place online on 29 & 30 September 2022.




What is the planned transition for eForms implementation on the TED portal?:: 

Starting on 14 November 2022, usage of eForms by Contracting Authorities
and Contracting Entities is optional and the Publications Office (OP) will
accept both the current TED schema notices and new eForms notices. The
TED portal will show both the current TED schema and eForms notices. 
+
From 25 October 2023 onwards, the usage of eForms is mandatory and the
Publications Office will no longer accept the current TED schema notices
but only eForms notices. The TED portal will continue to show the TED
schema notices that will have been received until 24 October 2023. 
+
The last day when OP will accept notices in the current TED schema format 
will be 24 October 2023, in line with the repeal of Implementing Regulation (EU) 2015/1986.
 

Which systems will be available for eSenders during the transition period?:: 

OP is developing a range of applications to manage the collection, validation, processing, visualisation and dissemination of eForms notices. 
OP will progressively make available the relevant applications through a link:https://docs.ted.europa.eu/home/eforms/preview/[“Preview”] environment 
that will help eSenders to develop and test their own applications. 
+
Notices sent to the current eSentool will continue to be accepted until
24 October 2023 and published on TED. As of 14 November 2022, eSenders
will have the possibility to send notices in the new format; however,
this will not become mandatory before 25 October 2023. 
+
On 14 November 2022, TED will display the new eForms while it will continue showing all notices 
submitted for the past 10 years even after 2024. 
From 14 November 2022 until 24 October 2023, the Publications Office
will run two systems in parallel, but it is up to the eSenders to
implement changes on their systems as and when best suits them during
this time. The current reception (eSentool and current eNotices) and production systems will be discontinued at the end of 2023.

 

Until when will the current eNotices application be available?:: 

Implementing Regulation (EU) 2015/1986 will be repealed on 25 October 2023. 
The current eNotices application will be available to submit notices until 24 October 2023. 
+
The new eNotices2 application will be available as of 14 November 2022
and run in parallel with the current eNotices application during the
transition period. 
+
eNotices2 is an application that performs both functions carried out 
by the current eNotices and eSentool applications. Authorised applications 
will be able to send complete notices to the API data interface of eNotices2, 
and if they are valid, they will be published in the Supplement to the Official Journal 
of the European Union (OJ S). Individuals with an eNotices2 account will be able to 
create notices within eNotices2 using its interactive web forms. 
+
eNotices2 will not take into account the different tailoring policies of Member States. 
As long as a submitted notice is valid against the eForms schema and the validation 
rules which implement the EU procurement regulations, it can be published in the OJ S. 
It will be up to the notice authors to apply any additional tailoring required 
by an individual Member State. 
 

With eForms, will there be a fixed publication schedule as there is today?::

The release calendar on TED includes the dates on which there will be an issue of the OJ S. 
The OJ S will continue to be published from Monday to Friday apart from certain national holidays. 
+
When submitting a notice, users can select a preferred publication date, or can choose publication “as soon as possible”. 
During the initial stages, OP will probably aim at publishing within five days, 
but it may be technically possible in the future to publish sooner 
provided the notice has passed automatic validation and the manual checks for lawfulness.   


What is the earliest possible time by when eForms could be introduced on a national level?:: 

The application of the eForms regulation in national legislation is
not under the control of OP or the European
Commission. We assume that in any case the earliest possible time by
when eForms could be introduced at a national level would be the same as
for the EU level, namely 14 November 2022. 
+
See also the section on link:https://ec.europa.eu/growth/single-market/public-procurement/digital/eforms_en[implementation in EU countries].


 
What sources of information are available for eForms?:: 

The following websites cover the various aspects of eForms: 
+
--
* Legal basis: Commission Implementing Regulation establishing standard
forms for the publication of notices in the field of public procurement (eForms) +
link:https://eur-lex.europa.eu/eli/reg_impl/2019/1780/oj[]
+
* Policy background from the European Commission (DG GROW: Directorate
General for Internal Market, Industry, Entrepreneurship, and SME) +
https://ec.europa.eu/growth/single-market/public-procurement/digital/eforms_en
+
* SIMAP: information about European public procurement +
https://simap.ted.europa.eu/web/simap/eforms
+
* eForms presentations from the TED eSenders webinar in November 2021 +
https://op.europa.eu/en/web/ted-esenders-webinar-2021/agenda
+
* eForms presentations from the eForms Technical Workshop in May 2022 +
https://op.europa.eu/en/web/ted-esenders-workshop-2022/agenda
+
* TED developer documentation portal +
https://docs.ted.europa.eu/
+
* eForms Software Development Kit on GitHub +
https://github.com/OP-TED/eForms-SDK
--
+
For any questions or issues, please contact the TED helpdesk at: ted@publications.europa  
+

Please note that the document "XPATHs provisional release v. 1.0.docx" is outdated 
and will no longer be updated. The equivalent information, and much more, is now available in the 
eForms SDK, which also takes into account the fact that some Business Terms occur 
in different contexts, and that the rules may differ between these contexts. 
 

== Forms and procedures 
[qanda]

 
Will eSenders have to send eForms for procedures that were started with the current standard forms? If so, how will the previous publication field be filled in, given that the Procedure Identifier is not used in the current forms?:: 

Once the use of eForms becomes mandatory, eSenders will be required to
send eForms notices for any procedures that were started with the
current standard forms. As there is no Procedure Identifier in the
current forms, in these cases the notice number of the previous TED XML
notice (as published in the OJ S) must be entered in the previous
publication field in the eForms notice. OP is reviewing how the eForms 
schema links to previous notices and will harmonise them to use 
/*/cacTenderingProcess/cac:NoticeDocumentReference/cbc:ID as a consistent 
element in the different contexts (root, lot, contract).

 
 
In the documentation we can read that we must use a UUID version 4 for the Procedure Identifier. Are there any limitations? Can we use every possible identifier and is it possible that two or more eSenders use the same number identifier in this case?::

The Procedure UUID is not linked to the eSender but to the procedure. Same Procedure UUID documents will be linked together in the same family of documents; 
this is the case - for instance -  for a continued procedure. In practice, it would be possible to send same family documents 
(linked together through the same Procedure ID) through different eSenders/ platforms. 
+
There are no limitations at this stage and version 4 UUID was chosen as the chances that the same UUID will be generated is close enough to zero to be negligible. 



How can a Contract Notice (current schema) be linked to a Contract Award Notice (eForms)?::

eForms include some BTs with the identifier of the previous notice, regardless of 
whether the notice uses the current TED schema or is an eForms notice. 
If the previous notice does not use eForms, the identifier will be the OJ S Notice ID (XXXXXXX-YYYY). 
For eForms, the previous notice identifier can be the Notice ID (UUID-vv).



How do we make a correction (F14) to a notice published in current schema, after transitioning to eForms?::

In the same way that it will be possible to link current form notices to eForms 
for procedures that started with the current form TED schema and ended with eForms. 
+
The notice in eForms format will link to the preceding TED format notice 
by referencing its OJ S number. However, a TED format notice cannot follow a notice 
in eForms format. 
+
OP is currently creating a converter, so a published notice 
in TED format can be converted to a partial eForms notice; "partial", because eForms notices 
contain much more information than TED notices. However, the "partial" eForms notice 
will have to be completed and checked in the eSenders’ systems. 
+
Regarding the F14, there is no longer a specific form for corrections such as the current F14. 
The Change notice Business Group will instead work as a separate section that will be 
attached to any notice, to indicate that this notice corrects, changes, or otherwise modifies 
a "parent" notice with the use of BG-9 and in particular BT-140 Change Reason Code. 



Currently an F14 may not be submitted until its previous notice is published. Will there be a change with eForms?:: 

With eForms, there will be a Change notice, which is a reproduction of its parent notice with an extra section 
to advertise changes to the procurement and procurement documents and for correction of clerical errors. 
+
A Change form will only be possible for notices whose parent notice has been published to avoid the possibility that different users 
may act on the same notice at the same time. If the parent notice has not yet been published, users can stop publication and resubmit. 
+
In case of many clerical errors, it will be possible to cancel a notice, which will cancel the notice itself and make it null and void, 
but this will not cancel the procedure. The user can - in this case - republish the same notice. 
To cancel the procedure, we would expect a Contract Award Notice with no winner. 



When creating a Change notice, should we send a new notice version with all changes included AND the section with the information of what has been changed or should we only send the Change notice separately?::

The Change notice Business Group works as a separate section that will be attached to any notice to indicate that this notice corrects, 
changes, or otherwise modifies a "parent" notice (identified by NoticeID and VersionID) with the use of BG-9 and in particular BT-140 Change Reason Code. 
+
A Change notice must contain all the information reported in the initial notice, with changes applied, as well as a section 
describing the latest changes (to the immediately preceding Notice): 
+
Changes may apply to notices of any form type. A Change notice may only concern a single notice and contains all the information from 
that initial notice with applied changes in addition to the information on those changes. 
+
When a change is applied to a previous Change notice, the consolidated text must integrate all changes from previous versions, 
and only the latest changes are described in the changes section. 
+
A Change notice may report that the procurement documents referenced by the initial notice have changed, and the date of that change, 
using BT-718 Procurement Documents Change Indicator and BT-719 Procurement Documents Change Date. 
A description of the changes to the procurement documents may be included in BT-141 Change Description. 
+
The Notice VersionID is described in the link:https://docs.ted.europa.eu/eforms/1.0.0/schema/elements.html#noticeIDSection[Notice & Version Identifiers] 
section: "Versions of a notice are purely editorial and for a given Notice ID, a single version may be published." 
+ 
The Notice VersionID can relate only to the editorial versions of the same notice (with the same Notice Identifier), 
managed by the generating application (e.g. eNotices2 or an eSender’s system), before publication of the notice. 
Only one of these versions will get published. 
+ 
The version ID values of different notices do not relate to each other. So, the VersionID of a Change notice 
is not related to the VersionID of the preceding notice. 
+ 
In the link:https://docs.ted.europa.eu/eforms/1.0.0/schema/change-notice.html[Change Notice] section, the word "version" is used 
to describe a notice or any of the related Change notices. 



We understand that the Change notice shall have its own identifier and version that differs from the one of the notice that has been changed. Does that mean that the initial notice always keeps the same version number?::

Yes. Multiple version IDs are for pre-publication, when eSenders might have multiple versions of the same notice on their systems 
and submit some of them. Each time a notice with the same notice identifier is submitted and accepted by the destination application 
(and publication is not stopped by the user), it must have a different version ID (starting at "01" and incrementing).
+
The first time the notice is accepted and published, the version ID of the notice they submitted is then final, 
and no other notices with the same notice identifier will be accepted. The version ID should increase if the notice is stopped 
and resubmitted or in case of error. 



Can you please clarify the meaning of each choice in the codelist Change corrig justification and when to use them?::

The below Change-corrig-justification codelist improvements will be made available at a later stage on EU Vocabularies. 
+
*link:https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/change-corrig-justification[Change-corrig-justification] codelist improvements*
+
This codelist is required for BT-140 Change Reason Code when using a Change notice.  
+
This proposal clarifies each code by adding a description and by changing two labels:  
+
- from "Cancellation" to "Cancel this notice" to make it clear that it only cancels the notice, not the procedure or the lot, 
which must be cancelled via a result notice with no winner.  
- from "Availability information" to "Information now available" to distinguish it more clearly from "Information updated". 
+
[cols="1,2,4", options="header"]
.change-corrig-justification codelist 
|===
| Code | Label | Definition

| cancel
| #Cancel this notice#
| The buyer has cancelled the current notice by making it null and void. It does not cancel the procedure or the lot.

| cancel-intent
| Cancellation intention
| The buyer intends to cancel the original notice. This enables the implementation of European Court of Justice case C-81/98 points 37-42.

| cor-buy
| Buyer correction
| Correction of one or more mistakes originally made by the buyer.

| cor-esen
| eSender correction
| Correction of one or more mistakes originally made by the eSender.

| cor-pub
| Publisher correction
| Correction of one or more mistakes originally made by the Publications Office of the EU.

| info-release
| #Information now available#
| Publication of information that was originally postponed for reasons of law enforcement, commercial interests of an economic operator, fair competition or other public interest

| update-add
| Information updated
| The buyer has updated or added information
|===



What will be the notice status of an eForms notice through its lifecycle?::

A user working on the user interface of eNotices2 will be able to see the following notice status: 
- Draft: The notice is being drafted. 
- Locked: The notice is being edited. 
- Validated: The notice is validated and ready for submission. 
- Submitted: The notice is successfully received, validated and sent to OP (received by TED-Monitor-2022). 
- Published: The notice is published online on TED. 
- Stopped: Publication of the notice was stopped by the buyer/ eSender before publication and the request was accepted. 
- Not published: The notice was received but not published on TED 



What is the meaning of the status “Not published”? Will there be reason codes for “Not Published” notices?::

If a notice is rejected due to manual lawfulness checks, it will obtain the status “Not published”. 
From an API point of view, a notice that fails the CVS check will not even reach status “submitted”. 
The CVS will give a validation report, which will detail all the reasons why a notice did not get through and the status “Not published” 
can be queried through the API. Rejection due to lawfulness manual check will be communicated via email to the contracting authority only.



What is meant by E1, E2, E3, E4 and E5 in the Excel document annexed to the eForms regulation?:: 

E1, E2, E3, E4 and E5 refer to forms that are not part of
the eForms regulation, but they were included in the “Extended Annex” to
regulation 2019/1780 available at: https://ec.europa.eu/docsroom/documents/43488
+
These forms will be implemented after eForms are mandatory in October
2023 and their use, which currently has no EU legal basis, will be optional. 
+
They would extend (E) the set of the other forms and correspond to the
following notices:  
+
- Preliminary Market Consultation (E1) 
- PIN below threshold (E2) 
- CN below threshold (E3) 
- CAN below threshold (E4) 
- Contract Completion (E5) 



What is the legal value of the five other non-eForm forms?::

The Implementing Regulation has 40 eForms. The 5 other forms are not eForms and implement other EU regulations but they are included in the same systems at OP:
- T01, T02: regulation 1370/2007 (public passenger transport by rail and by road) 
- X01, X02: business registration (European economic interest grouping and European company/cooperative society) 
- CEI: call for expression of interest (by EU institutions) 



What is the notice variant Business Registration Information used for?:: 

The “Business Registration Information Notice” scheme refers to European
Company and European Economic Interest Grouping notices, currently
available as interactive PDFs only. 
+
They are not part of the eForms Implementing Regulation but they are implemented in the same systems at the Publications Office 
so they appear in the eForms schema and rules as forms X01 and X02.

 

What is foreseen in eForms for countries that have no NUTS code?::

The eForms Regulation Annex 2 states that for both BT-507 Organisation Country Subdivision, and BT-5071 Place Performance Country Subdivision, 
"The NUTS3 classification code must be used." BT-507 and BT-5071 are intended to be used only when the NUTS3 level is known.
If a country does not have NUTS3 code, then it is not required. SDK 0.5.0 and future versions have reduced the NUTS codelist to only level 3 NUTS codes. 
+
BT-507 is only mandatory if one or more of BT-513 Organisation City, BT-512 Organisation Post Code, or BT-510 Organisation Street is present. 
And BT-5071 is only mandatory if one or more of BT-5131 Place Performance City, BT-5121 Place Performance Post Code, or BT-5101 Place Performance Street 
is present. 
+
BT-514 Organisation Country Code, and BT-514 Place Performance Country Code, are used to specify a country. If the country is used as a geographical 
region, neither BT-507 nor BT-5071 is required. 
+
When Place Performance Services Other (BT-727) has the value "anyw-cou" (Anywhere in the given country), the Place Performance Country Code (BT-5141) is mandatory. 



How will tailoring by Member States be handled by TED and the Publications Office?:: 

National specificities and their implementation at national, regional
and local level are outside OP's remit. 
+
In the eNotices2 form-filling tool user interface, users will be able to fill in and
send notices based on the eForms regulation. eNotices2 is not aware of
and does not apply any compliance with Member State tailoring; for
example, it will not check if an optional field (according to the EU
regulation) is mandatory at national level.  
+
The same applies to notices sent by eSenders via the eNotices API
(the successor of eSentool). All notices go through the same checks of
the Central Validation Service, not applying any Member State
tailoring. It is up to each user (or eSender) to ensure that their
notices comply with the national implementation of eForms.  +
 

== Planning and development 
[qanda]
 

What are the update cycles and how is change management (minor/major releases etc.) carried out for eForms?:: 

The technical standards will be based on the eForms SDK, which is versioned clearly, in particular to distinguish any breaking changes.  
+
See also the developer documentation about SDK versioning at: 
https://docs.ted.europa.eu/eforms/latest/versioning.html 
+
The formal change management governance is currently being set up and a change management board is envisaged. 

 

Has development of eNotices2 started?:: 

The development of eNotices2 started in 2020 and the application is
foreseen to be in production for November 2022. 
+
The scope of the application is to implement the eForms requirements in
a product that will allow at least the same functionalities that are
available in the current eNotices and the main functionalities that
are currently available in eSentool.  
+
The application also has a number of new features that will make
it easier and more streamlined for contracting parties to publish
notices, while mitigating the inherent complexity of the eForms
regulation as much as possible.
+
Presentations are available at the link:https://op.europa.eu/en/web/ted-esenders-webinar-2021[2021 eSenders seminar]. An updated demo 
of eNotices2 front-end application was presented during the 
link:https://op.europa.eu/en/web/ted-esenders-workshop-2022/agenda[eForms Technical Workshop of May 2022]. 


 
From 14 November 2022, will EU public buyers be able to create their eForms in eNotices2? Will it propose all the fields (mandatory and optional)?::

This is the point of eNotices2: it will provide all mandatory and optional fields 
and it will have rules to determine which fields are mandatory under certain conditions. 
There will also be a feature for users to make some of the optional fields mandatory. In the same way, 
it is also foreseen that if an optional field is not relevant for some users, the administrator of 
the organisation can “hide” these optional fields from view should they wish so.



Will there be a test system where users can test their eForms applications/ development?::

An instance of the OP applications is currently being deployed as a link:https://docs.ted.europa.eu/home/eforms/preview/[“Preview”] environment. 
The applications started to be made progressively available during Q2 2022.



Will you continue to send email notifications, e.g. to the Contracting Authorities, to remind them to publish a contract award notice?::

We have foreseen quite an extensive notification system, which will contain several methods for communication with eNotices2 users, 
including email communications. We should also provide the means to retrieve the information about the contracting authority 
sending notice through an eSender via the Notice Author concept, when it is needed. We have not yet decided if the reminder 
to publish a Contract Award Notice will be sent through an email notification, though it will likely be the case at some point.



Will eNotices2 send email notification for notices submitted by Web Services about publications or non-publication?::

This is currently under discussion. There is going to be an extensive notification 
system within eNotices2 and once this is in place, we may consider continuing with email notifications. 
For notices sent through Web Services and which have failed validation, an email notification will be sent 
to the Notice Author detailing all the rules that failed. 



== Visualisation and display of eForms notices 
[qanda]
 

Will a standard visual display be applied for eForms? Is it possible for the Publications Office to share (PDF) templates of eForms?:: 

The eForms will be displayed as standard forms, both within the
application that will be used to create and submit them (eNotices2) and
for their display on the TED website. The visual display will focus on
user-friendliness. As part of the ongoing development of eForms, the provisional samples of the 40 mandatory notices in PDF format 
was published in July 2021 at: https://simap.ted.europa.eu/documents/10184/320101/eForms+notice+PDF+samples+2021-07-22/c6785da3-8907-4071-9980-bb670b8ae9b8
+
An updated link:https://simap.ted.europa.eu/documents/10184/320101/eforms_2022-05-10-html/6be809e4-ac8a-4bc1-96d9-11b5fc366e6a[HTML file] was published 
in May 2022. It provides sample data to make it easier to see the TED Viewer structure, understand how the elements fit together 
and allows to switch between different notice types. The biggest structural change compared to samples from July 2021 
is the decision to group almost all the organisation information in one section. The current version is not yet final 
but it is quite close to what the eForms TED Viewer will produce. 
+
The link:https://github.com/OP-TED/eForms-SDK/tree/develop/view-templates[view-templates] available in the SDK 
contain the technical definition of how an HTML/ PDF will be generated by TED Viewer 2022. 
 
 

How will eForms notices be published and displayed on the TED website?:: 

For information about the future changes planned for the TED website, please refer to the relevant presentation in the 2021 eSenders Seminar: 
https://op.europa.eu/documents/8651547/0/eForms-in-TED-and-the-future-TED-2-0-2021-eSenders-seminar.pptx/317c4f15-9a18-58c3-a38e-be283206b977?t=1636106124942.



What preview solution do you provide with eForms TED API?::

TED Viewer 2022 is going to be available through an API in order to visualise the notice in HTML and PDF. 
It will be possible to preview a notice before sending it for publication.



What will be the retention period for the display of the eForms notices published on TED?:: 

The retention period for displaying all notices (including eForms
notices) on the TED website is 10 years (data available as of
1/1/2014). 



Will the Publications Office be providing eForms-rendering stylesheets?::

OP does not intend to provide XSL stylesheets. The view-templates in the SDK define how eForms will be displayed by TED Viewer 2022, 
using the eForms expression language (EFX). 
+
Users will also be able to render eForms notices in HTML or PDF using the service provided by TED Viewer 2022, which is going to be available through an API.



Will the Publications Office be providing XML notice samples for every PDF notice sample?::

The PDFs are only examples of how notices could be displayed. There are also examples of XML notices in the SDK 
at https://github.com/OP-TED/eForms-SDK/tree/main/examples/notices.
+
They are not the same notices as the ones used in the PDF views but they are aligned with the other SDK elements (like the schemas and rules).
 
 
 
What is the meaning of section 9.CHANGE in eForms 40 - Contract Modification Notice?::

eForm 40 is the equivalent of current form 20; it is used to publicise changes in ongoing contracts. 
As with all other forms, it may be corrected, in which case, a form 40 will contain section 9 (change) and 
will be published as a Change notice for a Contract Modification Notice.





== Technical documentation and Software Development Kit 
[qanda]
 

Where can I find the latest technical documentation published on eForms (schemas, business or validation rules and other relevant information)?:: 

Technical information on eForms, relevant to developers and experts, can
be found in the eForms Software Development Kit (SDK) on GitHub at https://github.com/OP-TED/eForms-SDK 

 

What is the purpose and governance of the SDK?:: 

Provisional releases of the eForms Schema and eForms Documentation were
provided in 2019 and 2020 through separate announcements on SIMAP. In
order to assist eSenders and eForms developers, new releases of the
eForms artefacts are now bundled together in the form of a Software
Development Kit (SDK). This includes the eForms schema, Schematron
validation rules, eForms documentation, sample XML documents and other elements. All
artefacts are versioned together with the version number of the eForms
SDK. 
+
The eForms documentation will indicate the version of the eForms SDK
that modified it. Likewise, the sample XML files will indicate the
version of the eForms SDK used when they were created or last modified. 
+
For more information on SDK versioning: https://docs.ted.europa.eu/eforms/latest/versioning
+
The purpose of the SDK is to assist eForms developers in creating applications that generate eForms notices in order to send them to eNotices2.
+
The components of the SDK are intended to be directly consumed by these applications. Multiple versions of the SDK will be maintained and remain 
available as long as they are supported by the legislation or business rules, allowing for more flexibility on the timing of upgrades 
on the eSenders’ applications. Updating applications to use new versions of the SDK should require minimal effort if the applications 
are built to integrate the SDK components.
+
More information about the SDK was presented at the link:https://op.europa.eu/en/web/ted-esenders-webinar-2021[2021 eSenders seminar].
+
The link:https://op.europa.eu/en/web/ted-esenders-workshop-2022/agenda[May 2022 eForms Technical Workshop] focused on building metadata-driven 
applications using the SDK.
+
For more information and examples of metadata driven applications: https://docs.ted.europa.eu/eforms/latest/metadata-driven-applications.html



Is there a roadmap (release plan) for future eForms SDK releases or a set release date for version 1.0.0 of the SDK?::

The eForms SDK is a complicated development and information is made available as fast as possible. 
An initial version of the SDK roadmap is available at link:https://docs.ted.europa.eu/home/eforms/roadmap/index.html[eForms SDK roadmap] 
and will be updated progressively. The page was created with a view to outlining the changes and additions to the eForms SDK 
planned in the upcoming releases.
+
The idea of the SDK is not to be bound by specific release dates. The target release date for version 1.0.0 of the SDK is August 2022. 
For this, all components of the SDK would need to be in place and complete, along with stable file formats. Version 1.0.0 of the SDK 
is OP’s top priority, but having all features in place is not foreseen before August of 2022.
+
However, please note that version 1.0.0 refers to the technical compatibility of the SDK 
as described in link:https://docs.ted.europa.eu/eforms/latest/versioning.html[eForms SDK Versioning].
+
The metadata of the SDK, in particular the schema and the rules, will still change after version 1.0.0 and until shortly before November 2022. 
+
The European Commission is planning to publish an amendment to the 2019 eForms implementing regulations. This amendment will change 
and add several business terms. 



Since the codelists are bound to SDK version, is there a risk that an SDK version/ lifetime can be short-lived?::

Versions of the SDK might be short-lived due to various reasons; however, multiple versions of the SDK can be used at the same time 
provided they are still acceptable. OP will aim to avoid breaking changes but stopping support for an SDK 
will often come for legal reasons and will be given enough transition time. 
+
Having a metadata-driven approach to this should enable users to make the technical transition with little to no effort. 
In theory, a metadata-driven approach could render any changes directly consumable by an application without human intervention
and the goal of the SDK is to minimise the effort. 
For more information on SDK versioning and backwards compatibility: 
https://docs.ted.europa.eu/eforms/latest/versioning



Other standardisation efforts provide information on how the business terms are mapped to the syntax. Currently OP provides a fields.json which is a highly       specialised tool used by OP. The fields.json contain max length constraints on fields, albeit no such limitation is found in the documentation.::

Fields.json does not attempt to follow or set a standard. It is a custom representation of field metadata 
that was chosen as the most suitable way for eForms systems to consume the information. 
OP is using it for its own applications (like eNotices2), and we aim to have a stable structure 
that can also be useful to external parties. The eForms implementing regulation does not define any maximum length constraints 
but we consider they are needed and have encoded them for each relevant field. Procurement notices are not intended 
to replace all the documents of a procurement procedure so there should be no need to publish very long texts. 


The XML schemas, its documentation and especially the mapping from business terms to fields in the schemas is essential to implementers in regard to technical and legal correctness. This includes the mapping of business terms to the XML schemas (XPATHs).::

The XML schemas and all relevant documentation are available on the eForms SDK; the IDs for Fields are always based on the "parent" BT. 
We have a specific definition for link:https://docs.ted.europa.eu/eforms/1.0.0/fields/index.html#_what_is_a_field[Fields].
They most often map to single XML elements, but not always. The mapping of Fields to XML elements is contained in the fields.json file.



If we were to use the SDK, would there be the need to customise for the national adoptions?::

Yes, customisations and tailoring would need to be applied locally, on the user’s application.



Will OP be providing a mapping of current TED XML schema to eForms?::

To support the transition between the two data formats, OP is mapping the fields of the current TED XML schema to the eForms schema. 
+
This link:https://simap.ted.europa.eu/documents/10184/320101/TED-XML-to-eForms-mapping-OP-public-20220404/a0fed751-76cb-491b-957d-96985fdc82a4[mapping in Excel]
builds on the 2021 mapping of business terms by the European Commission and completes it with the technical mapping of TED XML 
to the fields of the eForms schema at XPath level. 
+
Not all standard forms (SF) are included, and there is not an exact business correspondence between each SF and each eForm notice. 
+
This Excel file is provided "as is" and may serve as a guide. It will not be further updated but any feedback is welcome via ted@publications.europa.eu 
+
OP is sharing the XSLT files with the actual implementation of these mappings, which will be progressively enriched: 
https://github.com/OP-TED/ted-xml-data-converter. 
+
OP is also intending to develop an application to convert from TED XML to eForms XML using these XSLT files and which will be provided as a public API service. 
+
The conversion of TED XML will always result in an invalid eForms XML because, for example, not all fields exist, or text fields 
cannot be turned into codelist values. But it should allow users and systems to carry over as much as possible of existing notices into the new format, 
for example, when continuing a procedure that overlaps the switch between the two schemas. 



[NOTE]
====
Please note that the eForms SDK is updated regularly. 
Updates are announced on link:https://simap.ted.europa.eu/web/simap/eforms[SIMAP]  
and on the link:https://webgate.ec.europa.eu/fpfis/wikis/pages/viewpage.action?spaceKey=TEDeSender&title=TED+eSenders[TED eSenders Workspace].

You can also use the "watch" repository feature of Github to receive notifications for new releases.
====



== APIs and Web Services 
[qanda]
 

Will there be a TED qualification environment available for eForms? When will there be a way to test the submission of eForms notices?:: 

Unlike the current standard forms in eSentool, there will be no
qualification procedure for eForms and any user with an API key and an eNotices2 account 
will be able to submit notices via the API. Similarly, Qualification and Simulation endpoints will cease to exist. 
The environments available will be instead Production and Preview.  
+
The Preview environment that we are currently setting up will be available indefinitely 
so that users can test validation of notices against new versions of the SDK. The latter will first be implemented 
in Preview environment during a pre-announced transition period before going into Production. 
An SDK Management Service will be accessible as an API so that users can check all active versions of the SDK at any given time. 
+
A Central Validation Service (CVS) will be remotely available so that you can check the validity of eForms
notices. As our developments have no awareness of national tailoring, the application of the eForms regulation in national legislation 
will not be taken into account for the CVS.     
+
The CVS is not expected to be made available before mid-2022. 
+
Any announcements will be made via SIMAP at +
https://simap.ted.europa.eu/web/simap/eforms



Will a Sandbox be provided for testing the Web Services?::

A link:https://docs.ted.europa.eu/home/eforms/preview/[“Preview”] environment is gradually being made available. 
We plan to offer the possibility for users to go through all the steps from submission to publication, 
but this is done incrementally, gradually adding steps to the environment. 



Will there be any limitations for using TED API Validation Service?::

The Central Validation Service (CVS) will be available to users the same way as for eNotices2. 
There should be no limitations in using the CVS through the TED API. However, there will be some throttling 
to prevent that possible abuse of the system would degrade the experience for users. Therefore, there will be some limits 
to make sure the system works well for everyone, but the exact limitations will be communicated at a later stage. 



Will there be change in authentication method for the new eForms and if so, what authentication method will be used for the API?::

For the new systems, we will be using API Keys, which is - as a mechanism - very close to what we have in eSentool. 
Instead, however, of basic authentication with a username and password, an API key will be sent to the user 
in another HTTP Header; this API key will verify the user’s identity and through it, the user will be able to connect to various services, 
i.e. submitting/ validating/ visualising notices. Any user can be a Web Services user as long as they have an API key. 



Will the URL to which we send the messages remain the same?::  

The URL used for eForms notices will be different to the one used for
the current notices in eSentool.  
+
The new URL will be communicated when it becomes available. 



Will there be some API available, which users can use to transform/ convert TED XML to eForms?::

A converter is being developed, which will take a TED XML and convert it to a partial eForms XML. “Partial” because eForms notices 
contain more information than current TED notices. We will expose the converter to users through an API as a call service;
however, a full conversion will not be possible. For notice types that the converter does not cover, 
the information from the previous TED schema form will need to be entered again in the eForm for procedures that span the transition period.
If a field in a TED XML notice doesn’t exist in eForms, it’s only possible to use the free text of Additional Information field (BT-300).
+
A new release of the TED XML to eForms Converter (TEDXDC) has been published on link:https://github.com/OP-TED/ted-xml-data-converter[GitHub]. 
This release of the tool can convert Contract Award Notices using TED XML form F03, as well as all TED XML Contract Notice forms. 



Can I send an incomplete notice via Web Service-API and continue via eNotices2 UI?::

No, the notices must be complete before they are submitted via API.
 
 
 

== Schema and field definitions 
[qanda]
 

What is the release date for the eForms schema version that will be used for production in the future?:: 

The latest version of the schema is close to the version that will be
used for production.  The remaining unstated requirements
are being identified. 
+
Please consult the link:https://github.com/OP-TED/eForms-SDK[eForms Software Development Kit (SDK)] for more
details on the latest version of the schema and other technical components.

 

What is a Group of Lots and is it optional?::

Grouping of Lots is optional and simply a question of ease of use, as some buyers might find it easier to group lots together for a particular reason. 
+
At the level of Competition, you may have some lots that you feel can be grouped together under a specific set of tendering terms 
and allow companies to submit their offers for the group. This is also related to the maximum awarded lots and 
the quantity of lots the buyer wishes to award to the same company. At the level of the Result, the Group of Lots is just a concept,
meaning that the award should only be per lot, even if the lots form part of a group of lots. eForms regulation states that each lot 
has its own result; for each lot there will be one contract signed and one winner among the tenderers and all the non-winning tenders 
should also be mentioned. It is still going to be possible to award all the lots in the same notice, but only one by one. 



Should a single lot in a notice have the ID LOT-0000 or LOT-0001? What makes a lot "technical"?::

In eForms, at least one Lot is mandatory. A single Lot is a "technical" lot with LOT-0000 as the only accepted identifier. 
This means that a LOT-0001 would only exist if there were also a LOT-0002. If the notice contains multiple lots, 
it is not allowed to have a technical lot. 
+
Similarly, a Prior Information Notice or Periodic Indicative Notice used only for information without multiple parts 
should have a “technical” part with ID "PAR-0000". 



We find a lot of fields with OPT and OPP. However, there are no field definitions for these kind of terms. Will there be a new section in the documentation regarding OPTs and OPPs? Will there be a mapping between OPT/OPP and BT/BG, respectively do we need to map these?::

Basing the development of the eForms schema on the UBL schema, as well as conferring many advantages, has also imposed some constraints. 
These constraints have required the creation of a number of fields which were not anticipated in the eForms regulations; 
they do not have a true Business justification. They have been assigned different abbreviations to distinguish them 
from the BT terms defined in the eForms regulations, and to avoid potential conflicts if new Business Terms were created by DG GROW in the future.
+
Two abbreviations for these fields have been introduced: "OPP" and "OPT". "OP" is the abbreviation for "l'Office des publications". 
"P" stands for Production; these fields are required for the production processes, particularly for the non-standard forms
(not defined in the eForms regulations) that also use the eForms schema. "T" stands for Technical, these are required by our use of UBL 
as the base schema for eForms.
+
Some of the OPT and OPP fields are defined in the fields.json. More of these will be added in a future release of the SDK. 
Descriptions and usage information for all of the introduced OPT and OPP fields will be added to the documentation, 
each in the relevant section. Where they are intended to be used instead of other Business Terms, this will be stated. 
They may be listed in a table in a new section. A mapping between OPT/OPP and BT/BG is not currently foreseen. 



What does ORG-XXXX or TPO-XXXX mean? How is this value defined? What does the value for field "OPT 300" mean and how do we find these values?::

Each organisation used in a Notice is defined in an <efac:Organization> element, 
see https://docs.ted.europa.eu/eforms/1.0.0/schema/parties.html#organizationSection. It has a single identifier, 
which must follow the pattern "ORG-XXXX", where "XXXX" is four digits. The first organisation would have identifier "ORG-0001", 
the second one "ORG-0002", etc, but numerical sequence in numbering does not have to be observed and there can be gaps in the numbering.
+
An organisation might have several contact details, each for one or more different functions. Each contact is defined in a TouchPoint, 
which has an identifier following the pattern "TPO-XXXX". An example XML for a Buyer is shown in: 
https://docs.ted.europa.eu/eforms/1.0.0/schema/parties.html#buyerSection. 
+
Within the rest of the notice, any function performed by an organisation can then link to that organisation, or to one of its touchpoints, 
by using the relevant identifier as a reference. Examples of this can be found in: 
https://docs.ted.europa.eu/eforms/1.0.0/schema/parties.html#_legislation_information_provider 
and the following section: https://docs.ted.europa.eu/eforms/1.0.0/schema/parties.html#_other_rolessubroles  
+
These references use fields OPT-300 and OPT-301. These and other similar references are listed in: 
https://docs.ted.europa.eu/eforms/1.0.0/schema/identifiers.html 



What are the Roles/ Subroles with which a TouchPoint can be associated?:: 

Roles/subroles it may be associated with are in table 2 in the Documentation section
link:https://docs.ted.europa.eu/eforms/1.0.0/schema/identifiers.html#_referring_to_objects[IDs & References].
+
A Touchpoint could be referred to for the following roles/subroles: 
+
[cols="1,6", options="header"]
|===
| Business Term | Name of the Business Term
| OPT-301
| Additional Info Provider Technical Identifier Reference

| OPT-301
| Document Provider Technical Identifier Reference

| OPT-301
| Employment Legislation Organization Technical Identifier Reference

| OPT-301
| Environmental Legislation Organization Technical Identifier Reference

| OPT-301
| Tax Legislation Information Provider Technical Identifier Reference

| OPT-301
| Mediator Technical Identifier Reference

| OPT-301
| Review Information Providing Organization Technical Identifier Reference

| OPT-301
| Review Organization Technical Identifier Reference

| OPT-301
| Tender Evaluator Technical Identifier Reference

| OPT-301
| Tender Recipient Technical Identifier Reference
|===



How should we fill in BT-3201 Tender Identifier?::

For TenderID, as for most identifiers, a dedicated scheme similar to that defined for other identifiers, has been specified. 
Information is available in the documentation in the link:https://github.com/OP-TED/eForms-SDK[eForms SDK].

 
What happens when CA_ACTIVITY_OTHER is given in current F02?:: 

The current TED XML element CA_ACTIVITY_OTHER allows free-text content. This often leads to inconsistencies in reporting the main activity of
the contracting authority.  
+
In eForms, this possibility has been removed and only one value from the list of values in the "main-activity" code list is allowed. 


How can I deal with multiple NUTS codes in OBJECT_DESCR?:: 

In the current TED XML, the location(s) of each Lot is indicated with only one MAIN_SITE element, but multiple NUTS elements. 
+
In eForms, there is the possibility to have more information about each location: a full address, a description and a NUTS code. These are held
in the cac:RealizedLocation element. This element is repeatable within each Lot. 



How is joint procurement handled in eForms?::

Joint procurement / consortia are handled by use of the Tendering Party 
(https://docs.ted.europa.eu/eforms/1.0.0/schema/competition-results.html#tenderingPartySection). A Tendering Party may contain one or more tenderers.



In the .xsd files elements "cbc:ActivityTypeCode" and "cbc:ActivityType" are found for BT-10 and BT-610, but in samples it's used rather as only a value from the codelist. Is ActivityType ever implemented or is this element redundant and all activities are covered by the codelist?::

The element cbc:ActivityType is not implemented for eForms. The requirements for BT-10 and BT-610 are only for code values, 
hence only the element cbc:ActivityTypeCode is used. The element cbc:ActivityType is redundant, and all activities are covered by the codelist.


What is the meaning of “multilingual text” in BT-500?::

"Multilingual Text" means that the text may be language-specific and repeated. In some cases, such as textual descriptions, 
this means that the text may be repeated, once for each official language used in the notice. In other cases, 
as with some uses of BT-500, the text may be the name of an entity that may exist in multiple languages. 
+
BT-500 (Organisation Name) is used in four contexts: 
+
- BT-500-Organisation-Company - A company may have different names in different languages.
- BT-500-Organisation-TouchPoint - A contact unit within a company may have different names in different languages. 
- BT-500-UBO - This is the personal Name of the Ultimate Business Owner, and so cannot be expressed in multiple languages.
- BT-500-Business - Only allowed for X01 and X02 notice type forms. As these are Business Registration Information Notice forms, only one Business Name is allowed. 



Is BT-78 (Security Clearance Deadline) intended for submitting some documents after the tender deadline? Validation of this BT against other deadlines is not described in the documentation.::

For BT-78, the description field BT-732 can be used to define how the Security Clearance Deadline related to other dates in the procedure. 
As the fields are optional, there are no plans to have any business rules for them and can be used as needed.



Is BT-195 really an identifier?::

BT-195 is named as "Unpublished Identifier" in the Annex spreadsheet. It is an identifier in a general sense, 
in that it is intended to identify the BT that is "unpublished". But in the UBL schema, the XML elements for the BTs 
that need to be unpublished do not have identifier elements associated with them. Instead, we have created a codelist 
which maps codes to the associated BTs. This codelist is included in the SDK identified by the listName attribute 
"non-publication-identifier", filename non-publication-identifier.gc.



How does BG-8 Not Immediately Published work in practice?::

The unpublished fields are the eForms equivalent to the confidential fields of today. There are several fields involved, 
which can be "unpublished", some related to all Directives and others only for Directive 25. 
The fields themselves are handled by the use of a codelist and for each of them the fields of BG-8 are requested in the XML. 
+
For example, BT-118 Notice Framework Value, can be unpublished. If that is the case, the user will be able to identify it as such 
and then will have to insert BT-197 (why it is unpublished), and BT-198 (when this field will be made public). 
A user may also want to add BT-196 (an optional description). 
+
On TED, the unpublished fields will still be present, but their content will be replaced with masking values, 
e.g. text fields will contain "unpublished" and numbers will be set to -1. 



With BT-198 (Unpublished Accessibility Date) it is possible to give the exact date on which the information will be made available. How will this actually work and how will the publication work in practice when the deadline has passed?::

You should include the information not meant for immediate publication in the form. As each expiry date is reached, 
OP will re-publish the form with the relevant information included. Not Immediately Published Data is masked in notices 
before the Unpublished Accessibility Date (BT-198), and then the notice is published. 
+
Whenever an Unpublished Accessibility Date (BT-198) is reached, the notice is republished with the relevant Not Immediately Published Data included. 
The notice has the same Notice ID, but a new Publication ID. 
+
The BT-198 should be within the next 10 years. If the date is not filled, the unpublished fields will never be published 
(and the notice is therefore only published once). 



How will BT-702 Notice Official Language work in practice?::

Any Contracting Authority may publish an eForms Notice in one or more of the EU Official languages. 
The chosen languages are considered of equal status. EU Institutions publishing eForms Notices are obliged to publish them in all 24 EU Official languages. 
+
If more than one language is chosen, all text content of the Notice is capable of being expressed in different languages 
must be expressed in all chosen languages. Due to the technical requirements of UBL, only one language may be specified 
using the element <cbc:NoticeLanguageCode>; the others must use the element <cbc:ID> within the element <cac:AdditionalNoticeLanguage>. 
There is no implication or meaning to the choice of which language is specified using <cbc:NoticeLanguageCode>. 


BT-125 and more specifically BT-1251 refer to the Previous Planning Part Identifier. What is a “part” of a notice. How can one define a “part” without using lots?::

The "Previous Planning" refers to Notices of type "Planning". The "Part Identifier" refers to a Part that is included in such Planning Notices. 
The Part may later become a Lot or a self-standing procedure. Field BT-125 Previous Planning Identifier is only to be used 
to identify previous planning notices. Within a framework agreement, the field BT-1252 "Direct Award Justification Previous Procedure Identifier" 
should contain the identifier of the procedure under which the framework agreement was concluded (BT-04). 



Why is BT-1371 Previous Planning Lot Identifier not documented?::

Most of the elements “XYZ Lot Identifier” Business Terms that exist in the extended annex  spreadsheet do not appear in this annex 
as they are just a way to link a BG to a Lot/Part. When looking at the regulation extended annex (file “CELEX_32019R1780_EN_ANNEX_TABLE2”) 
you will observe for multiple Business Groups the presence of elements of the kind “XYZ Lot Identifier” just after the row for the Business Group; 
in most cases this is a way to associate a Business Group (and its content) to one or more specific lots. 
In the XML, this information is pointless by design as the information of the Business Group may be found inside the element representing the lot.
+
Some of the BTs for identifiers are not needed due to the way that the schema has been developed. There is a list of these in the documentation, 
under the section https://docs.ted.europa.eu/eforms/1.0.0/schema/identifiers.html#pointlessDueToDesignSection["Pointless due to design"].



BT-738 allows to choose a preferred notice publication date. How will this work exactly?::

The BT-738 Notice Publication Date Preferred is available to help the buyer to coordinate publication dates at national and European levels. 
The submitted notice will be stored in the OP internal system (TED Monitor 2022). When the preferred publication date is reached, 
the notice will be published on TED. The preferred publication date can be set for up to 3 months into the future. 



== Business and validation rules 
[qanda]
 
What are referred to as business rules in the context of eForms?::

Business Rules are business-driven rules used to ensure a certain
quality of the reported information. They define or constrain the
existence of business information in a procurement notice (e.g. whether
some information is mandatory, the possible values of a field, etc.).
They have their origin in the Directives and the eForms Regulation or
are based on common sense (e.g. an end date is later than a start date)
as well as on the legal bases, the public procurement Directives and the
eForms Regulation: 
+
* https://ec.europa.eu/growth/single-market/public-procurement/rules-implementation_en 
* https://ec.europa.eu/growth/single-market/public-procurement/digital/eforms_en 

 
When will the business rules and field validation rules be made available?::

The current Schematron validation rules together with some examples of
valid and invalid XML files are published on GitHub as part of the link:https://github.com/OP-TED/eForms-SDK[eForms SDK]. 
+
We will keep updating these artefacts regularly as they evolve. 



What is the role and status of the Extended Annex Excel, and differences with the Implementing Regulation?::

The Extended Annex to the Regulation was made available (https://ec.europa.eu/docsroom/documents/43488) to provide additional information and clarifications. 
+
As stated in the Legend tab of the Excel sheet, the Extended Annex spreadsheet is identical to Table 2 of Annex of the "Implementing Regulation 
establishing standard forms for the publication of notices in the field of public procurement", except for three differences: 
+
- The spreadsheet differentiates "M", "CM" and "EM" fields (see below). The Annex of the Implementing Regulation does not - it denotes all as "M".
+
- The spreadsheet explicitly lists lot identifiers (e.g. Purpose Lot Identifier BT-137), while the Annex of the Implementing Regulation does not.
+
In both cases, these additional details are useful to know for technical implementation, but are an excessive technical detail to be included in the act itself.   +
- The extended Annex includes additional notices that will be made available to national authorities for voluntary use after October 2023. 
These are marked as "E1" - "E5" in the notice number field and their use is explained in chapter 3 of the eForms Policy Implementation Handbook. 
Extended notices E1 and E5 contain fields not used in other notices. These cases are marked in column AZ of the ‘Annex’ sheet.    



What are CM and EM fields?::  

EM is mandatory if the related information exists, i.e. if the Contracting Authority has the information, they should fill it in.
CM is Conditional Mandatory, i.e. mandatory if certain conditions are met.  
+
References to CM and EM are not part of the annex to the Regulation; they are included in the so called “Extended Annex” Excel sheet 
that was provided for information and clarification purposes. 


Are the rules for CM documented in detail? If so, where can one read about these conditions?:: 

The conditions are visible in the Schematron rules as well as in the eForms expression language, efx-grammar. 



Why do the validation rules differ in some cases between the Extended Annex to the Regulation and fields.json? For example, CELEX states that BT-52 (Successive Reduction) for eForm 16 is mandatory, but fields.json has no mandatory rule for this field.::

The validation rules in the fields.json differ from those in the CELEX table because the business logic 
requires the aggregation of multiple conditions, and sometimes the introduction of interdependencies, 
not all of which are directly shown/visible in the Regulation Annex. Not all of the required business rules 
have been implemented in the SDK, and so the fields.json is not yet complete. 
+
BT-52 belongs to a Business Group (BG-709 Second Stage) which is CM (Conditionally Mandatory) and may not always exist; 
in fact, BG-709 may only exist when the procedure is a "competitive dialogue", "innovation partnership" or "negotiation with a prior CFC". 



BT-541 is not marked as mandatory in CELEX and fields.json, but it is mandatory according to schema. Which one should be considered correct?:: 

BT-541 is held in the element efbc:ParameterNumeric which is mandatory within its parent element efac:AwardCriterionParameter. 
But the parent element efac:AwardCriterionParameter is optional, and so in the context of a LOT, BT-541 is optional. 
The element efac:AwardCriterionParameter is designed to hold a single criterion, with a number value (BT-541) and a dimension (BT-5421, BT-5422 or BT-5423). 


What are Schematron files for eForms? Can you provide samples of them?::

The eForms schema applies basic structural rules to the XML notices. Schematron files are used to apply 
further validation rules to the XML notices, ensuring that for each notice type, mandatory fields are present 
and correct field values are used. Schematron files are available as part of the eForms SDK in the GitHub repository. 
+
As the creation of Schematron files is a work in progress and they will not be ready for official publication for some time, 
the versions in the SDK only contain a preview. They are provided as-is, without any commitments from the Publications Office 
for their completeness or stability and without any documentation or support at this stage. The SDK in the repository will be updated periodically. 



Will OP be providing an Excel sheet with the validation rules of individual fields for eForms?::

OP does not intend to use an Excel spreadsheet to document the validation rules for fields within eForms. 
Due to the increased number of fields in eForms compared to the existing TED XML, there will be a very large number of validation rules, 
and an Excel spreadsheet listing the validation rules would be difficult to maintain and use. 
Instead, we are providing the validation rules as a set of Schematron files, included in the eForms SDK. 
These rules are still being developed, and more rules will be added in future releases of the SDK. 



Are the Schematron validation rules documented in a more” human readable” form? Can you provide a data model for eForms domain - something like an "entity -relationship diagram"?::

Some of these rules are in the documentation, e.g. which field must use which codelist. We currently do not have an exhaustive 
human-readable documentation or an entity-relationship diagram, but OP is working on human-readable versions of the business rules 
that can be linked to the technical validation rules. For the time being, all information is communicated through the SDK, 
but ideas for documenting rules are welcome. 



Will we receive translations for the error messages that are foreseen in the Schematron validation files?::

We are currently working on creating translations for the error messages in the Schematron validation files. 
These will be included in a future release of the eForms SDK. 
+
In the future, users will be able to decide in which of the 24 languages they would like to receive the returned validation report 
in Schematron Validation Report Language (SVRL). 



If a field is mandatory but left empty or if a code choice is mandatory but not chosen, will the notice be rejected and not published? Are there no "content" checks beyond that, for example if a monetary value doesn't make sense?::  

If mandatory fields are not filled in, it will not be possible to submit the corresponding notice and the notice will, therefore, be rejected.
There will be several additional business rules that will check the validity of the content of different fields, i.e., combinations of
fields, in a way equivalent to what is done today with the existing forms.  
+
As with the current TED notices, there will be rules that will block (reject) the submission of eForms notices, particularly in cases that
violate or contradict the Procurement Directives. All these rules are currently under construction and implemented using Schematron. Only
after 14 November 2022, when eForms are introduced, will the Publications Office inform users in advance of any new rules to come. 
+
Notice validation will be automated through the Central Validation System. Human validation will only be done for notices that have a “lawfulness” warning. 
This means that the notice contains information that suggests it should not be published in the Supplement to the Official Journals of the EU. For example, 
notices from countries outside the EEA or that do not have an agreement with the EU. The notices will be subject to a manual check at OP 
to decide if they should be published or rejected. 
 


From a technical point of view, would an eForms notice be rejected if the names of some business terms and descriptions are changed at the national level?:: 

The eForms notices submitted for publication on TED should conform to
the eForms schema, XPaths and field IDs, which are the same for all
Member States. This means that any notice submitted that doesn't conform
to this schema will be rejected by definition. 
+
On the other hand, what is done and published at national level is under
the responsibility and control of the National Authorities, which means
that a notice published at national level may not look exactly the
same on the national site (which follows the national
terminology) as on TED (which follows the EU terminology). 



What are the technical restrictions in eForms?::

There will be some throttling to prevent possible abuse of the system. The new eNotices2 application currently being developed 
will have a limit of 2000 Lots for the user interface, however, OP may decide to impose lower limits in the future. 
+ 
The technical limit for the number of LOTs is 9999. This is because the technical identifier of a LOT is 
"LOT-" followed by four digits. The identifier value "LOT-0000" is reserved as a "technical" lot for Procedures without LOTs. 
+ 
There are other technical identifiers which impose the same limit of 9999 on numbers of: Parts (PAR-XXXX), 
Groups of Lots (GLO-XXXX), Organisations (ORG-XXXX), TouchPoints (TPO-XXXX), Contracts (CON-XXXX), Tenders (TEN-XXXX), 
Tendering Parties (TPA-XXXX), Ultimate Beneficial Owners (UBO-XXXX). 
+ 
These limits, and other restrictions, can be found in the fields.json file in the SDK. They are defined as 
regular expression patterns associated with the relevant fields, within "pattern" keys. 



Are there any official regular expression patterns that will be used to validate received notices regarding e.g. email addresses, phone numbers, URLs, postal codes etc.?::

The regular expression patterns we currently have (used in the Schematron files) are used to validate certain fields. 
Many of these validate the format of identifiers: Procedure and Notice Identifiers, and the internal identifiers 
for parts of a notice such as Lots, Tenders, Organisations, etc. There is a pattern for email addresses, 
and one for telephone and fax numbers. We don't have one for URLs at present. 
As the format of postal codes varies by country, and new formats can be created at any time, we have currently 
no plans to validate these using regular expressions. 
+
We have not published a list of these regular expressions, but they can be found in the fields metadata JSON file by the key "regex".



== Codelists 
[qanda] 


Are all eForms codelists published on the EU Vocabularies site? Where do we find the most recent and correct version of the codelists, on GitHub or the EU Vocabularies Authority tables and taxonomies?::

There are codelists that have no relevance or use outside the context of eForms; these are not published on the EU Vocabularies website
but are published as part of the eForms SDK. 
+
The codelists in the "codelists" folder of the SDK in GitHub should be used for developing eForms applications. This is because:
+ 
- Some codelists are "tailored" codelists, using a subset of values from their "parent" codelists. These will not be published 
on the EU Vocabularies Authority tables page.
+
- Some codelists are "technical" codelists that are required only because of the use of UBL to implement eForms. The "conditions" 
codelist for BT-70 is an example. These will not be published on the EU Vocabularies Authority tables page.
+
- Some codelists are made available first in the SDK on GitHub, because the process for publishing them on the EU Vocabularies 
Authority tables page takes longer due a quarterly publishing schedule.
+
For more information, see https://docs.ted.europa.eu/eforms/1.0.0/codelists/index.html[Tailored Codelists] 
in the documentation.



Are the filenames and format of the codelists as intended? We are wondering about the suffix ‘.gc’ and whether them containing all languages renders the translations unnecessary.::

The codelist files use the OASIS standard Code List Representation (genericode) format 
(see https://docs.oasis-open.org/codelist/genericode/v1.0/genericode-v1.0.html) which typically uses the "gc" suffix for filenames. 
They contain translations in the 24 official languages of the EU. The translations files contain translations for all business terms, 
fields and decorations used in eForms. For convenience to developers, the codelist translations are also included in the translations files. 
+
The values of the @listName attributes correspond to the identifiers of the codelists. The filenames of the codelists 
match the codelists identifiers for entire (published on EU Vocabularies) or technical codelists. But tailored codelists contain subsets of entire codelists, 
and their filenames are derived from both the tailored codelist identifier and the parent entire codelist identifier. 
+
For more information, see https://docs.ted.europa.eu/eforms/1.0.0/codelists/index.html[Tailored Codelists] 
in the documentation.



Will eForms use Supplementary CPV codes?::

As supplementary CPV codes are not mentioned in the regulation, they will not be implemented in eForms. 
Current use of supplementary CPV codes is very low and there no plans to use them in eForms.  
+
However, the eForms schema will allow the addition of other classifications if needed in the future.



BT-755-Lot, BT-772-Lot and BT-777-Lot all reference codelists in the“xpathAbsolute”/”xpathRelative” field, have a “type”-attribute called “text-multilingual” and a “legal-type”-attribute called “TEXT” and therefore a codelist is not attached to these fields. All those codelists are at least referenced in the “xpathAbsolute” field. How are these fields validated against the codelists?::

These Business Fields contain multilingual text, so their validation is limited to checking the declared language codes; 
they are not validated against codelists. However, codelists are referenced in their "xpathAbsolute" field, in an ancestor or sibling node 
of the Business Field. Validation of the codelist values of these nodes is included in the Schematron validation files in the SDK. 
+
For example, Business Field BT-755-Lot has field "xpathAbsolute" with a value of: 
"/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cac:ProcurementAdditionalType[cbc:ProcurementTypeCode/@listName='accessibility']/cbc
:ProcurementType". 
+
The leaf element cbc:ProcurementType is validated for compliance with language rules. The sibling element cbc:ProcurementTypeCode has a 
@listName attribute set to "accessibility". The Schematron includes a rule which restricts the content of this sibling element to the values 
in the "accessibility" codelist. 



Why is the codelist for BT-774 (green-procurement) not present either on the EU vocabularies Authority tables page or in the "Codelist" folder on GitHub?:: 

BT-774 uses the environmental-impact codelist, which is available in the SDK on GitHub. The version of this codelist in the SDK will be updated 
with the June 2022 version published on EU Vocabularies at:
https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/environmental-impact  



Why are you adding codes to eForms Business Terms and how often this will be done?::

Some BTs represent fields whose values come from predefined lists. These
values are represented by codes.  Such code lists are not specific to
eForms and they can be used in other domains. Code lists are dynamic and
can be updated. Standard releases and release dates can be found at +
https://op.europa.eu/en/web/eu-vocabularies/releases
+
The concepts in the EU Vocabularies authority tables and taxonomies that
are used in eForms are indicated in the XML and SKOS formats by the
”EFORMS” use context. These formats are available for each vocabulary
under the “Downloads” tab.  
+
For example, in the case of contract-nature available at + 
https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/contract-nature.
+
The XML file does not indicate the “EFORMS” context for the "combined"
concept, therefore combined is not used in eForms:  
+
[source, xml]
----
<start.use>2021-03-17</start.use>  
<use.context>TED</use.context>  
----
+
whereas the XML file indicates the use eForms context for the "services"
concept, therefore "services" can be used in eForms: 
+
[source, xml]
----
<start.use>2019-09-18</start.use>  
<use.context>CODIF_DATA</use.context>  
<use.context>EFORMS</use.context>  
<use.context>TED</use.context> 
----
     
     
== ESPD 

[qanda]
Could you provide a clarification about the integration of ESPD into eForms (BG-701 and BG-702)?:: 

The possibility of some level of integration of ESPD requests into
eForms notices (avoiding multiple encoding of the same information
by reusing it) has been considered and the feasibility of this is still
being evaluated. However, it will not be a complete substitution, and
ESPD requests will remain necessary. 
+
For more information, please see section 4.1.2.1 
of the link:https://op.europa.eu/en/publication-detail/-/publication/73a78487-cc8b-11ea-adf7-01aa75ed71a1[eForms Policy Implementation Handbook].
 
 
 
