= Business Entities

== Introduction

In some fields there are patterns like:

[source,json]
----
  "pattern" : {
    "value" : "^(RESULT|((CON|RES|TEN|TPA|TPO|ORG)-\\d{4}))$",
    "severity" : "ERROR"
  },
----

Or this pattern:

[source,json]
----
  "pattern" : {
    "value" : "^(PROCEDURE|BUYER|RESULT|((PAR|LOT|GLO|RES|ORG)-\\d{4}))$",
    "severity" : "ERROR"
  }
----

Values like `LOT` are described in various places outside of the pattern.
But some values like `PROCEDURE` only existed in the SDK.
This gave us a hint that machine readable information was missing somewhere in the SDK.
The information about identifiers was spread across the fields, nodes and patterns.

To solve this we decided to add what we call "business entities" to the SDK.
We also decided that each field should belong to one and only one business entity.
The business entities are independent from the XML structure (nodes) even if there are common points.
Thus in `fields.json` the fields have a `businessEntityId` and we decided that nodes of the `xmlStructure` nodes would only have a business entity if repeatable.

The business entities describe what we call the logical structure.

== Business entities in the SDK

Business entities are provided as a JSON array called `businessEntities` in the `fields.json`

[horizontal]
`id`:: Identifier of the business entity.
`parentId`:: Identifier of the direct parent business entity (if applicable).
`name`:: A short name which can be used for display (instead of the id).
`description`:: A descriptive text, it is longer than the `name`.
`repeatable`:: Indicates if the business entity can be repeated inside its parent.
`repeatsWithNodeId`:: Indicates the node the business entity repeats with, present if it repeats.
`identifierFieldId`:: Indicates which field id identifies this business entity instance (if applicable).
`captionFieldId`:: Indicates which field id can be used to display this business entity instance to a user (if applicable).
`instanceIdentifier`:: An object to document the instance identifier (if applicable).
`formatName`:: Found in `instanceIdentifier`, the format name, for now we have two, the "prefixedNumber" or "fixedText".
`text`:: Found in `instanceIdentifier`, the identifier prefix or the fixed text.
`schemeName`:: Indicates the schemeName (if applicable).

== Legacy data

The business entities could make some of the `fields.json` data obsolete.
We will keep this data for backward compatibility reasons, but it could be removed in a future SDK.

For example:

[source,json]
----
    "businessEntityId" : "groupOfLots",
    "idScheme" : "GLO",
    ...
      "schemeName" : "LotsGroup",
----

The field `schemeName` is coming from the business entity, it should ideally be retrieved via the business entity of the field.
We will keep the `schemeName` in the `fields.json` for backward compatibility.
The same is true for the `idScheme`, `identifierFieldId` and `captionFieldId`.

== Usage

=== User interfaces

This can be used in a UI to group or filter fields by their business entity.
It can be more natural to group them by business entity than to group them by XML structure node.
In that case the fields can be first sorted by business entity and second by alphabetical order.

=== Hardcoded identifiers

Some identifiers like for example `PROCEDURE` were not present in the SDK except in the `pattern` of some fields.
These identifiers are made of fixed text, in the business entities they have `"formatName"` with value `"fixedText"`.
The identifier value is given by the `"text"`, for example `"text" : "PROCEDURE"`.

=== Detecting changes

The process of detecting changes could be automated inside of applications.
In order to populate the data of the field `BT-13716-notice` the following logic can be used: 

* If the data of a field was changed
* Read the `businessEntityId` of the field via `fields.json`
* Get the business entity by business entity id via `fields.json`

After this there are two cases fixed and prefixed identifiers.

==== Fixed identifiers

The simplest case is if the business entity has the fixed identifier format `fixedText`.
In that case the `text` gives the identifier that changed.

==== Prefixed identifiers

A more complex case is when the identifier has the prefixed number format `prefixedNumber`.
In that case the `instanceIdentifier` field can be found via the business entity.
The field business entity id of a field always points to the most precise business entity.
But if the field is repeatable the application must pick the correct instance, the one to which the changed field belongs.

=== XML generation and schemeName attribute

In simple cases fields of type `id-ref` can only reference one type of identifier, in that case the scheme name is given.
But in some cases for fields of type `id-ref` the user can select between multiple identifier types.
For example `ORG` or `TPO`, this means the user will decide the `schemeName`, it cannot be determined in advance.

Assuming the user selected `Touch point one (TPO-0001)`:

* The application puts the correct id `TPO-0001` into the field
* From the value `TPO-0001` the application can extract the `TPO` prefix 
* In `fields.json` the application can find the business entity that has the prefix `TPO`
* From the business entity the application can infer the `schemeName` which is `touchpoint`

The `schemeName` is an XML attribute which must be set on some XML elements and the value must be `touchpoint` in this example.
It is possible to achieve this without the business entities but the business entities make the link more obvious.
