= Field metadata

== What is a field

The https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32019R1780[eForms
Regulation] defines, in table 2 of its annex, a set of business terms (BT) for
the various pieces of information that are in a notice.

But the level of granularity of those BTs is not sufficient to accurately
reflect the structure of the information in the XML notices.

For example, there is a single business term, BT-27, for the estimated value of
the procurement procedure or lot. But the estimated value of a lot is in a
different location in the XML, and will be subject to different rules, than the
estimated value of the whole procedure.

The notion of fields was added to resolve those ambiguities. Each field is
related to one single business term, and corresponds to a more precise
definition of the information it contains. The identifier of a field always
starts with the identifier of the corresponding business term.

For the example above, the fields defined for BT-27 are:

* BT-27-Procedure : estimated value of the procedure
* BT-27-Lot : estimated value of a lot
* BT-27-Part : estimated value of a part
* BT-27-LotsGroup : estimated value of a group of lots 

[#field-repository]
== The field repository

[WARNING]
====
The structure and content of the field repository described below are driven by
the specific needs of our various applications.

As we think it could be useful for others, we are sharing it publicly, and you are
free to make use of it. However we currently do not guarantee the stability
of the structure or content described here.
====

The field repository is a JSON file that contains all relevant information for
each field we have defined, in a structured and reusable form.

We are using this file to provide the definition of all fields to our
form-filling application (eNotices2). Each form is then made of a specific
subset of those fields.

The field repository is an array of fields, preceded by some version information:

[source,json]
----
{
  "ublVersion": "2.3", // <1>
  "sdkVersion" : "eforms-sdk-0.5.0", // <2>
  "metadataDatabase": { // <3>
    "version": "0.2.53",
    "createdOn": "2021-11-20T16:46:39"
  },
  "fields": [ // <4>
    { ... },
	...
  ]
}
----
<1> version of the UBL standard used
<2> version of the eForms SDK the file belongs to
<3> version number and date of the data used to create this file
<4> list of fields

== Field properties

For each field, various of its characteristics are indicated as properties of the JSON object that represents it.

[source,json]
----
{
  {
    "id" : "BT-01-notice", // <1>
    "parentNodeId" : "ND-0", // <2>
    "name" : "Procedure Legal Basis", // <3>
    "btId" : "BT-01", // <4>
    "xpathAbsolute" : "/*/cbc:RegulatoryDomain", // <5>
    "xpathRelative" : "cbc:RegulatoryDomain", // <6>
    "type" : "internal-code", // <7>
    "legalType" : "CODE", // <8>
    "repeatable" : { // <9>
      "value" : false
    },
    "codeList" : { // <10>
      "value" : {
        "id" : "legal-basis",
        "type" : "flat"
      }
    }
  },
...
}
----
<1> Identifier of the field.
<2> Identifier of the node (XML element) that contains the field.
<3> Short name of the field.
<4> Identifier of the business term to which the field corresponds.
<5> Location of the field in an XML notice, as an absolute xPath.
<6> Location of the field in an XML notice, relative to its parent node.
<7> Technical data type of the field.
<8> Data type of the business term, as indicated in the eForms Regulation.
<9> Indicates if the field can appear more than once inside its container
<10> Identifier of the code list from which the field value must belong.
Applicable only for fields of type "code" or "internal-code"


=== Property Values

Some properties are assigned with a static value; a value that does not depend on any conditions and does not change. For example the "btId" property (indicating the business term associated with the field) is assigned a static value because it is always the same. 

The properties that are assigned with static values are listed below:

* `id`
* `parentNodeId`
* `name`
* `btId`
* `xpathAbsolute`
* `xpathRelative`
* `type`
* `legalType`

Static properties are always assigned with a scalar value (a string, a boolean, a number, etc.).

Every other property, apart from the ones listed above, is assigned a dynamic value. This is because the value of the property may depend on different factors, for example the notice type it is used in, or the values of other fields in the same notice.

Dynamic values are represented with a JSON object. The object always contains a `value` property which indicates the default value for the  dynamic property and, when necessary, a `constraints` list that indicates the conditions under which the dynamic property may take different values.


.Dynamic property value example
[example]
====

In the following snippet, a dynamic value is assigned to the `forbidden` dynamic property:

[source,json]
----
"forbidden" : {
  "value" : false, // <1>
  "constraints" : [ { // <2>
    "noticeTypes" : [ "22", "38", "39", "40", "X01", "X02" ], // <3>
    "value" : true, // <4>
    "severity" : "ERROR"
  }, {
    "noticeTypes" : [ "2", "5", "8", "11", "14", "15", "17", "19", "24", "30", "32", "35", "37" ], 
    "condition" : "!(field('BT-740-Procedure-Buyer')=='not-cont-ent')", // <5>
    "value" : true, // <4>
    "severity" : "ERROR"
  } ]
},
----
<1> The default value of the property will be false in this example
<2> List of constraints for this property.
<3> The first constraint in this example specifies a different value than the default one in case the field is used in one of the notice types indicated.
<4> The value of this dynamic field in case the constraint is applicable is indicated here.
<5> The second constraint in this example, does not only require specific notice types but also indicates specific condition that need to be true for the constraint to be applicable.
====

All dynamic values are always represented in the same was as in the example above. The structure of this object is illustrated in the abstract snippet below:

[source,json]
----
"propertyName" : {
  "value" : "scalar1", // <1>
  "severity" : "ERROR", // <6>
  "constraints" : [ // <2>
    {
      "noticeTypes" : [ "noticeType1", "noticeType2" ], // <3>
      "condition": "Boolean expression in SpEL", // <4>
      "value" : "scalar2", // <5>
      "severity" : "ERROR" // <6>
    },
    ... // <7>
  ]
}
----
<1> Use this default value for the property if none of the provided constraints applies. This value is always provided.
<2> A list of constraints will be provided if needed. If not, the use the default value provided.
<3> This constraint only applies for these notice types. Every constraint specifies the notice types for which it applies. 
<4> This condition must evaluate to true for the constraint to be applicable. A condition is provided only when one is needed. 
<5> This is the value that the property should take if the constraint is applicable.
<6> The severity is provided for validation systems. It may be either "ERROR" or "WARN". "WARN" indicates that a notice that does not comply with the provided value is still considered valid.
<7> Multiple constraints may be provided. If none applies, then use the default value provided for the property.


For more details on the syntax of conditions, see <<Syntax for conditions>> below.

=== Field data types

The possible technical data types for a field are:

* `id`: string representing an identifier
* `id-ref`: string representing a reference to an identifier
* `indicator`: boolean (true or false)
* `integer`: whole-valued positive number
* `number`: numerical value, with optional decimal places.
* `amount`: monetary amount, comprised of a numerical value and a currency
* `measure`: numerical value associated with a measurement unit
* `code`: string representing a concept in a code list
* `internal-code`: string representing a concept in an internal code list
* `zoned-date`: date with timezone
* `zoned-time`: time with timezone
* `email`: string representing an e-mail address
* `phone`: string representing a phone number
* `url`: string representing a URL
* `text`: language independent string
* `text-multilingual`: string that can be translated in multiple languages

== Dynamic properties

=== Repeatable

The `repeatable` property indicates whether or not a field can appear more than once inside its container. The current version of the eForms SDK does not contain any fields that are only repeatable under certain conditions. However the `repeatable` property is a dynamic property so that constraints can be added to this property if needed in the future.

[source,json]
----
"repeatable" : {
  "value" : false,
  "severity" : "ERROR"
}
----

=== Forbidden

The `forbidden` property indicates whether or not the field can be used in specific notice types. 

[source,json]
----
"forbidden" : {
  "value" : false, // <1>
  "severity" : "ERROR", // <2>
  "constraints" : [ {
    "noticeTypes" : [ "38", "39", "40", "X01", "X02" ],
    "value" : true,
    "severity" : "ERROR" // <2>
  } ]
}
----
<1> Every field is allowed by default in all notice types unless a constraint forbids it.
<2> The severity can be either "ERROR" or "WARNING" and is provided for use by validation systems.

=== Mandatory

The `mandatory` property indicates whether or not a field is required to have a value. 

[source,json]
----
"mandatory" : {
  "value" : false, // <1>
  "constraints" : [ {
    "noticeTypes" : [ "1", "4", "7", "10", "14", "16", "19", "23", "29", "32", "35", "36", "CEI", "T01", "T02" ],
    "value" : true,
    "severity" : "ERROR" // <2>
  } ]
}
----
<1> Every field is optional by default in all notice types unless a constraint specifies otherwise.
<2> The severity can be either "ERROR" or "WARNING" and is provided for use by validation systems.


NOTE: The UBL specification does not permit XML documents
to contain empty elements or attributes. So if a field is not mandatory and no value has been filled in, then the corresponding XML element must be omitted from the XML notice.

CAUTION: The value of the `forbidden` property must take precedence over the value the `mandatory` property. If a field is forbidden, then it should not be present in the notice regardless of the value of its `mandatory` property. You should always check first if a field is forbidden or not. Then, consider whether the field is mandatory or optional only if the field is not forbidden.

=== Codelist

[source,json]
----
"codeList" : {
  "value" : {
    "id" : "accelerated-procedure",
    "type" : "flat", // <1>
    "parentId" : "indicator", // <2>
    "severity" : "ERROR"
  }
}
----
<1> Indicates that the codelist is a simple list of values. The few codelists that have a structure, like NUTS and CPV, are indicated as "hierarchical".
<2> Indicates the parent codelist. Provided only for tailored codelists.


=== Pattern

[source,json]
----

----



=== Syntax for conditions

The value of the `condition` property of a constraint is a string representing a boolean expression.

The syntax of the expression is based on the
https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#expressions[Spring
Expression Language (SpEL)], limited to a small number of boolean and comparison operators.

A field is referenced using its identifier: `field('BT-31-Procedure')`.
