= eForms SDK Roadmap

== eForms SDK 1.x.x

Since the release of the eForms SDK 1.0.0 in August 2022, we have continued to release updates to the SDK that incrementally improve the eForms metadata that is included in it. These updates are all backwards compatible with the SDK 1.0.0 and therefore they can be used by applications that have already been adapted to the SDK 1.0.0. At the time of updating this roadmap (April 2023), the latest version of the SDK is 1.6.0, while testing is underway for the release of 1.7.0 foreseen to be released next week.

Further updates to SDK 1.x.x will continue to be released with the frequency of roughly one update per month. We are dedicated in the continued support of the SDK 1.x.x and we will continue to update it with new minor releases as well as patches to all active SDK versions. Minor releases will introduce updates to the eForms business rules as needed, while patches will ensure updated translations and other metadata are made available to all eSender applications regardless of whether or not they are already using the latest minor version of the eForms SDK.

== eForms SDK 2.0.0

In parallel, we are working on the next major version of the eForms SDK, which we plan to release by the end of June 2023. The new version aims at improving the grammar of EFX to make it more flexible and easier to read and write. Its main goal is to improve the expressiveness of EFX Templates so that we can overcome current limitations in notice visualisation. We are also adding new functions that will allow us to better manipulate and format notice data, as well as improve our current internationalisation capabilities. 

For more details on what is coming with SDK 2.0.0, you can consult the xref:sdk2/index.adoc[SDK 2 preliminary documentation] that we have made available. You can find more xref:sdk2/efx2.adoc[details on EFX 2 here]. 

NOTE: Please note that the SDK 2 documentation is still a work in progress and that it will be updated as we make progress on the development of SDK 2.0.0. 