= eForms Preview environment
:page-aliases: home:eforms:preview/index.adoc


The Publications Office (OP) has developed a range of applications for the collection, validation, processing, visualisation and dissemination of eForms notices. These applications are collectively known as "TED Apps for eForms". 

The Preview Environment hosts early releases of TED Apps for eForms, simulating production settings for testing purposes, allowing eSenders and stakeholders to test notices, and applications’ integration without the risk of publishing notices in the OJ S. 

NOTE: Features, data, and availability might change without notice, and capacity is shared between all eSenders, supporting approximately 5000 notices per day. For terms of use, refer to the https://enotices2.preview.ted.europa.eu/terms[TED Publishing Services Terms of Service]. 

Read more about https://docs.ted.europa.eu/api/latest[TED API] and https://docs.ted.europa.eu/api/latest/index.html#_how_ted_api_links_to_ted_apps[how it links to the TED Apps]. 


== Accessing TED Apps in PREVIEW

 * https://api.preview.ted.europa.eu/swagger[API documentation]

 * https://enotices2.preview.ted.europa.eu[eNotices2 website]

 * https://developer.preview.ted.europa.eu/[TED Developer Portal]


Read more on https://docs.ted.europa.eu/api/latest/index.html#_testing_your_apps[how to test in Preview]
