= eForms SDK Roadmap
:page-aliases: eforms:ROOT:roadmap.adoc, home:eforms:roadmap/index.adoc


SDK versions are released several times per year to improve the provided metadata and implement regulatory changes. Releases are announced in the link:https://github.com/OP-TED/eForms-SDK/discussions/categories/announcements[eForms developer forum on GitHub], where you can watch for updates or follow the discussions.

This page provides an overview of the upcoming releases and the changes that are planned for them. The last revision to this page was made in September 2026.


== eForms SDK 1.16.0

SDK 1.16 is being tested and is planned for release in October 2026. Its main aim is to simplify the structure and use of undisclosed fields.

It is no longer planned to release SDK 1.16.0 in sync with the SDK 2.0.0 final version. This will be done with SDK 1.17.0 to ensure business equivalence and avoid delaying the release of SDK 1.16.0.

== eForms SDK 2.0.0

=== Overview

The goal of SDK 2 is to introduce a new version of EFX (the eForms Expression Language) that enhances the template definition vocabulary for better notice visualisation, improves the ability to express business rules with completeness and simplicity, and makes the language easier to write, read, maintain and interpret.

For details on what is new in SDK 2.0.0, consult the xref:sdk2/index.adoc[SDK 2 documentation]. You can find more xref:sdk2/efx2.adoc[details on EFX 2 here].

=== Release timeline

==== Alpha (current)

* *SDK 2.0.0-alpha* versions continue to be released, completing the EFX-2 grammar with all three language flavours (EFX Expressions, EFX Templates, and EFX Rules), as well as updated SDK metadata.

==== Beta

* *SDK 2.0.0-beta.1* will be released together with SDK 1.17.0-beta.1. Beta.1 will remove some legacy EFX-1 syntax in order to simplify parsing. After beta.1, the grammar is not expected to change significantly. Any changes after beta.1 are not expected to break compatibility with beta.1.

==== RC

* SDK 1.17.0-rc.1 will serve as the metadata baseline for SDK 2.0.0-rc.1.
* The SDK 2 beta will be reviewed together with the teams developing the OJS applications (eNotices2, TED Central Validation Service, TED API, TED Viewer, TED Monitor, and TED website) to finalise the SDK and related libraries (eforms-core-java, efx-toolkit-java) and sample applications.
* *SDK 2.0.0-rc.1* is targeted for release by the end of 2026.
* During the RC period, development of OJS applications using SDK 2 will be finalised and tested. The final version of the SDK will be released only after the applications have been fully developed and tested.

==== Final release

* *SDK 2.0* is targeted for release in early 2027, subject to how adaptation of related OJS applications evolves.

=== Feedback

During the beta and RC periods, we welcome feedback from the eSender community. Please use the link:https://github.com/OP-TED/eForms-SDK/discussions[GitHub Discussions in the SDK repository] to share your feedback.

NOTE: The SDK 2 documentation is a work in progress and will be updated as development progresses.

== Future SDK 2.x releases

A third amendment to the eForms regulation may happen in late 2027, which will be delivered through an SDK 2.x release. In the meantime, there will be at least one SDK 2.x release before the eForms amendment to deliver maintenance changes or incremental improvements and rules.

[discrete]
= Relevant links

You can find further relevant information on the following links:

* Use the xref:eforms:ROOT:versioning.adoc[SDK versioning] page to understand SDK versioning rules.
* Use xref:home:eforms:active-versions/index.adoc[SDK version lifespan] page to find out which SDK versions are currently in use.
* Use the link:https://docs.ted.europa.eu/eforms-sdk-explorer[SDK Explorer] to compare SDK versions and explore the differences between them.
