= eForms SDK Roadmap

SDK versions are released several times per year to improve the provided metadata and implement regulatory changes. Releases are announced in the link:https://github.com/OP-TED/eForms-SDK/discussions/categories/announcements[eForms developer forum on GitHub], where you can watch for updates or follow the discussions. 

This page provides an overview of the upcoming releases and the changes that are planned for them. As it is updated manually it may not always be up to date. The last revision to this page was made in March 2024.

== eForms SDK 1.x.x

Since the release of the eForms SDK 1.0.0 in August 2022, we have continued to release updates to the SDK that incrementally improve the eForms metadata that is included in it. These updates are all backwards compatible with the SDK 1.0.0 and therefore they can be used by applications that have already been adapted to the SDK 1.0.0. 

// === SDK 1.12.0
// SDK 1.12.0, which will be released shortly after SDK 1.11.0 in March 2024, will not include any metadata updates but **will extend the conceptual model** by introducing **Business Entities**  in `fields.json`. 

// This new concept will allow us to better link notice type definitions with the conceptual model. More specifically it allows us to link instances of repeatable nodes and fields with instance identifiers in cases where it was not previously possible. For example, applications will be able to provide better user experiences when filling-in change notices, as well as in other cross-referencing use cases of `id-ref` fields.

// The introduction of this new concept will not break backwards compatibility. We wil provide more details on the concept of Business Entities in the March 2024 eSender meeting. Appropriate documentation for the new feature will also be made available together with the release of SDK 1.12.0.

// === Other releases during 2024
In 2024, there will be at least two SDK releases to satisfy the changes and deadlines required by the link:https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32023R2884[December 2023 amendment to the eForms implementing regulation]. 

One SDK release, no later than May, will include the new fields for the link:https://code.europa.eu/eproc/eforms/docs/-/blob/main/guides/gde_001_fsr.pdf[Foreign Subsidies Regulation (FSR)] and link:https://code.europa.eu/eproc/eforms/docs/-/blob/main/guides/gde_002_ipi.pdf[International Procurement Instrument (IPI)] as well as the updates to exclusion and selection criteria. A further SDK release, no later than October, will include the rest of the amendment changes, notably including the six voluntary forms E1-E6. 

Other SDK improvements will be released during the year, which might be combined with these two regulatory updates. 

== eForms SDK 2.0.0

In parallel, we have been working on the next major version of the eForms SDK. We initially tried to complete and release SDK 2.0.0 by June 2023 to give enough time to eSenders to adopt it before going live with eForms on October 2023. However we realised that the timing was not right for most eSenders and decided to freeze further development until after the full roll-out of eForms across the eSender network with SDK 1. We intend to restart the effort on completing the work for SDK 2.0.0 in the second half of 2024. We are aiming to release SDK 2.0.0 by the end of 2024 or early 2025. 

The new version aims at improving the grammar of EFX to make it more flexible and easier to read and write. Its main goal is to improve the expressiveness of EFX Templates so that we can overcome current limitations in notice visualisation. We are also adding new functions that will allow us to better manipulate and format notice data, as well as improve our current internationalisation capabilities. 

For more details on what is coming with SDK 2.0.0, you can consult the xref:sdk2/index.adoc[SDK 2 preliminary documentation] that we have made available. You can find more xref:sdk2/efx2.adoc[details on EFX 2 here]. 

NOTE: Please note that the SDK 2 documentation is still a work in progress and that it will be updated as we make progress on the development of SDK 2.0.0. 

[discrete]
= Relevant links

You can find further relevant information on the following links:

* Use the xref:eforms:ROOT:versioning.adoc[SDK versioning] page to understand SDK versioning rules.
* Use xref:eforms:active-versions/index.adoc[SDK version lifespan] page to find out which SDK versions are currently in use.
* Use the link:https://docs.ted.europa.eu/eforms-sdk-explorer[SDK Explorer] to compare SDK versions and explore the differences between them.